In [1]:
!pip install -U transformers

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Collecting transformers
  Downloading transformers-5.9.0-py3-none-any.whl.metadata (33 kB)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.16.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (8.4.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.15)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
Downloading transformers-5.9.0-py3-none-any.whl (10.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 125.1 MB/s eta 0:00:00
Installing collected packages: transformers
  Attempting uninstall: transformers
    Found existing installation: transformers 5.0.0
    Uninstalling transformers-5.0.0:
      Successfully uninstalled transformers-5.0.0
Successfully installed transformers-5.9.0

## Local Inference on GPU
Model page: https://huggingface.co/Qwen/Qwen3-8B

⚠️ If the generated code snippets do not work, please open an issue on either the [model repo](https://huggingface.co/Qwen/Qwen3-8B)
			and/or on [huggingface.js](https://github.com/huggingface/huggingface.js/blob/main/packages/tasks/src/model-libraries-snippets.ts) 🙏

## Remote Inference via Inference Providers
Ensure you have a valid **HF_TOKEN** set in your environment. You can get your token from [your settings page](https://huggingface.co/settings/tokens). Note: running this may incur charges above the free tier.
The following Python example shows how to run the model remotely on HF Inference Providers, automatically selecting an available inference provider for you.
For more information on how to use the Inference Providers, please refer to our [documentation and guides](https://huggingface.co/docs/inference-providers/en/index).

In [2]:
import os
os.environ['HF_TOKEN'] = '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'

In [3]:
!pip install -q -U transformers accelerate bitsandbytes

from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
import torch

model_id = "Qwen/Qwen3-8B"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True
)

print(f"Ładuję model: {model_id}...")
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map="auto",
    low_cpu_mem_usage=True
)
print("Model gotowy do pracy!")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 28.1 MB/s eta 0:00:00
Ładuję model: Qwen/Qwen3-8B...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/728 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/9.73k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/32.9k [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 5 files:   0%|          | 0/5 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/399 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

generation_config.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

Model gotowy do pracy!

# Analiza tekstu litaryckiego

In [ ]:
!pip install -q pymupdf

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.1/24.1 MB 106.3 MB/s eta 0:00:00

In [ ]:
import fitz  # PyMuPDF
import torch
import json
from transformers import AutoModelForCausalLM, AutoTokenizer

In [ ]:
# 1. Konfiguracja modelu Qwen3
model_name = "Qwen/Qwen3-8B"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype="auto", # Qwen3 sam dobierze optymalny typ (np. bfloat16)
    device_map="auto"
).eval()

Loading weights:   0%|          | 0/399 [00:00<?, ?it/s]

In [ ]:
# 2. Przygotowanie dokumentów JSON (Standard RAG)
def prepare_rag_documents(file_path, pages_to_extract):
    documents = []
    doc_pdf = fitz.open(file_path)

    for i, pg_num in enumerate(pages_to_extract):
        if pg_num <= len(doc_pdf):
            page = doc_pdf[pg_num - 1]
            text = page.get_text().strip()

            doc_entry = {
                "doc_id": i,
                "title": f"Преступление и наказание - Страница {pg_num}",
                "content": text[:4000]
            }
            documents.append(doc_entry)

    doc_pdf.close()
    return json.dumps(documents, ensure_ascii=False)

In [ ]:
# 3. Parametry
pdf_file = "/priestuplieniie_i_nakazaniie_-_fiedor_mikhailovich_dostoievskii.pdf"
pages = [12, 13]

rag_context_json = prepare_rag_documents(pdf_file, pages)

In [ ]:
# 4. Prompt w języku rosyjskim
messages = [
    {
        "role": "system",
        "content": (
            "Вы — высококвалифицированный литературный эксперт. Используйте предоставленные "
            "данные в формате JSON для написания глубокого анализа и краткого содержания. "
            "Ваш ответ должен быть строго на РУССКОМ языке."
        )
    },
    {
        "role": "user",
        "content": f"Данные из книги в формате JSON:\n{rag_context_json}\n\nНа основе этого текста напишите подробное резюме событий на русском языке."
    }
]

# Przetwarzanie promptu (Qwen używa standardowego ChatML)
input_ids = tokenizer.apply_chat_template(
    messages,
    return_tensors="pt",
    add_generation_prompt=True
).to("cuda")

In [ ]:
# 5. Generowanie
print(f"Qwen анализирует текст (RAG)... Пожалуйста, подождите.\n")

outputs = model.generate(
    input_ids['input_ids'], # Pass the actual tensor to model.generate
    max_new_tokens=1000,
    do_sample=True,
    temperature=0.3,
    top_p=0.8 # Qwen lubi nieco niższe top_p dla większej stabilności
)

# Dekodowanie
# Corrected: Access the actual tensor for shape
summary = tokenizer.decode(outputs[0][input_ids["input_ids"].shape[-1]:], skip_special_tokens=True)

print("--- РУССКОЕ РЕЗЮМЕ (QWEN RAG) ---")
print(summary)

The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.

Qwen анализирует текст (RAG)... Пожалуйста, подождите.

--- РУССКОЕ РЕЗЮМЕ (QWEN RAG) ---
<think>
Хорошо, мне нужно создать подробное резюме событий на основе предоставленного текста из книги "Преступление и наказание". Сначала я должен понять, о чем идет речь в этих страницах.

В первом документе, страница 12, разговор происходит между Мармеладовым и молодым человеком. Мармеладов рассказывает о своей жизни, о том, как он попал в тяжелое положение. Он упоминает, что пьет, потому что ищет сострадания и чувств, но при этом чувствует себя скотом. Он говорит о своей жене Катерине Ивановне, которая, несмотря на его пьянство, старается заботиться о семье, включая детей. Он признается, что пил чулки и косыночку жены, что указывает на его пагубное поведение. Также он рассказывает о своей бывшей жене, которая умерла, и о том, как он оказал помощь бедной женщине, но затем потерял работу и теперь живет в нищете.

Во втором документе, страница 13, продолжается рассказ Мармеладова. Он подробнее описывает, как его жена воспитывалась в институте, получала медаль, но потом ушла из семьи. Он рассказывает о своей бывшей жене, которая умерла, и о том, как он помог бедной женщине, но затем потерял работу. Также упоминается, что они теперь живут в углу у хозяйки, и Мармеладов чувствует себя виноватым, потому что потерял работу по своей вине. Он выражает боль и страдание, чувствуя, что не может больше жить в таком положении.

Нужно объединить эти моменты в краткое резюме, подчеркнув основные события: бедность Мармеладова, его пьянство, отношения с женой, прошлое, потерю работы, страдания и чувство вины. Важно показать, как его жизнь развивается, начиная с рассказа о прошлом, затем о настоящем положении, и его внутренние переживания. Также стоит отметить, что он ищет сострадания, но чувствует себя неприемлемым, что создает конфликт в его характере.
</think>

**Краткое содержание:**
В тексте, взятом из романа Ф. М. Достоевского «Преступление и наказание», представлен разговор Мармеладова с молодым человеком, в ходе которого он раскрывает свою трагическую жизнь. Мармеладов, бывший офицер, оказал помощь бедной женщине, но после смерти её мужа остался с тремя детьми и впал в нищету. Он рассказывает, как его жена Катерина Ивановна, воспитанная в институте, несмотря на его пьянство, старается заботиться о семье, но страдает от его сквернословия и пагубных привычек. Мармеладов признаётся, что пил чулки и косыночку жены, что символизирует его духовное падение. Он описывает, как после потери работы из-за изменений в штатах семья оказалась в нищете, живя в углу у хозяйки Амалии Федоровны. Его внутренний конфликт — между чувством вины за своё положение и стремлением к состраданию, что подчёркивает трагизм его существования. Рассказ подчёркивает тему социального неравенства, человеческой жалости и внутреннего разрушения, характерных для романа.

**Краткое содержание:**  
В тексте, взятом из романа Ф. М. Достоевского «Преступление и наказание», представлен разговор Мармеладова с молодым человеком, в ходе которого он раскрывает свою трагическую жизнь. Мармеладов, бывший офицер, оказал помощь бедной женщине, но после смерти её мужа остался с тремя детьми и впал в нищету. Он рассказывает, как его жена Катерина Ивановна, воспитанная в институте, несмотря на его пьянство, старается заботиться о семье, но страдает от его сквернословия и пагубных привычек. Мармеладов признаётся, что пил чулки и косыночку жены, что символизирует его духовное падение. Он описывает, как после потери работы из-за изменений в штатах семья оказалась в нищете, живя в углу у хозяйки Амалии Федоровны. Его внутренний конфликт — между чувством вины за своё положение и стремлением к состраданию, что подчёркивает трагизм его существования. Рассказ подчёркивает тему социального неравенства, человеческой жалости и внутреннего разрушения, характерных для романа.

In [ ]:
# 2. Przygotowanie dokumentów JSON (Standard RAG)
def prepare_rag_documents(file_path, pages_to_extract):
    documents = []
    doc_pdf = fitz.open(file_path)

    for i, pg_num in enumerate(pages_to_extract):
        if pg_num <= len(doc_pdf):
            page = doc_pdf[pg_num - 1]
            text = page.get_text().strip()

            doc_entry = {
                "doc_id": i,
                "title": f"Janko Muzykant - Strona {pg_num}",
                "content": text[:4000]
            }
            documents.append(doc_entry)

    doc_pdf.close()
    return json.dumps(documents, ensure_ascii=False)

In [ ]:
# 3. Parametry
pdf_file = "/janko-muzykant.pdf"
pages = [2, 3]

rag_context_json = prepare_rag_documents(pdf_file, pages)

In [ ]:
# 4. Prompt w języku rosyjskim (Qwen doskonale radzi sobie z cyrylicą)
messages = [
{
"role": "system",
"content": (
"Jesteś ekspertem od literatury polskiej. Twoim zadaniem jest analiza "
"tekstu noweli Henryka Sienkiewicza dostarczonego w formacie JSON i "
"przygotowanie szczegółowego, rzetelnego streszczenia w języku polskim. "
"Skup się na faktach i emocjonalnym wydźwięku utworu."
)
},
{
"role": "user",
"content": f"Oto treść noweli w formacie JSON:\n{rag_context_json}\n\nNa podstawie tych stron napisz szczegółowe streszczenie po polsku."
}
]


# Przetwarzanie promptu (Qwen używa standardowego ChatML)
input_ids = tokenizer.apply_chat_template(
    messages,
    return_tensors="pt",
    add_generation_prompt=True
).to("cuda")

In [ ]:
# 5. Generowanie
print(f"Qwen analizuje tekst (RAG)... Пожалуйста, подождите.\n")

outputs = model.generate(
    input_ids['input_ids'], # Pass the actual tensor to model.generate
    max_new_tokens=1000,
    do_sample=True,
    temperature=0.3,
    top_p=0.8 # Qwen lubi nieco niższe top_p dla większej stabilności
)

# Dekodowanie
# Corrected: Access the actual tensor for shape
summary = tokenizer.decode(outputs[0][input_ids["input_ids"].shape[-1]:], skip_special_tokens=True)

print("--- POLSKIE STRESZCZENIE (QWEN RAG) ---")
print(summary)

Qwen analizuje tekst (RAG)... Пожалуйста, подождите.

--- POLSKIE STRESZCZENIE (QWEN RAG) ---
<think>
Okay, I need to create a detailed summary of the short story "Janko Muzykant" by Henryk Sienkiewicz based on the provided JSON content. Let me start by reading through the text carefully.

First, the story begins with the birth of a weak and sickly child, Janko. The villagers are worried, but the midwife reassures them, and they perform a baptism. Janko is described as frail, with a big belly and sunken cheeks. He's often hungry, and his mother, a poor woman, struggles to feed him. Despite his poverty, Janko has a unique ability to hear music in nature—like the wind in trees, the sounds of animals, and even the echo of songs. This makes him different from other children.

As he grows, Janko is called "Janko Muzykant" because he's always listening to the music around him. He doesn't go to school, but he's fascinated by the sounds of the world. He often goes to the village tavern, where he listens to the musicians playing. The music is so captivating that he can't sleep, and he's drawn to the sounds of the fiddles and other instruments. However, he can't afford to buy his own instruments, so he makes his own from materials like birch bark, but they don't sound as good as the ones in the tavern.

Janko's obsession with music leads him to long for the chance to play the fiddles himself. He watches the musicians in the tavern, especially the fiddler, and dreams of playing. His desire for the fiddles is so strong that he even risks his health to get close to them. However, his poverty and lack of resources prevent him from achieving his dream. The story ends with Janko still longing for the music, even as he becomes more emaciated and his body weakens.

I need to make sure the summary includes the key elements: the birth of Janko, his physical appearance, his unique ability to hear music, his interactions with the village, his fascination with the tavern musicians, his attempts to create his own instruments, and his unfulfilled desire to play. Also, the emotional tone of his longing and the contrast between his inner world of music and his harsh reality should be highlighted. I should avoid any personal opinions and stick to the facts presented in the text. Let me structure this into a coherent summary in Polish.
</think>

**Streszczenie noweli „Janko Muzykant” Henryka Sienkiewicza**

Nowela opowiada o urodzeniu chłopaka, Janka, który od pierwszych dni życia był słaby i wątły. Wspólnota wsi, zaniepokojona jego stanem zdrowia, przeprowadza ceremonię chrztu, by zasłonić go przed grzechami. Janko rośnie w biedzie – ma wydęty brzuch, spadające policzki i oczy wpatrzone w dalekość, jakby patrzył na świat z niezmiernego odległości. Jego matka, biedna komornica, żywi go z dnia na dzień, często bijąc go i nazywając „odmieńcem”. Choć chłopak nie ma zdolności do roboty, jego największe marzenie to słuchanie muzyki, którą słyszy w naturze: wiatr w drzewach, śpiew ptaków, echo w polu, a nawet głosy ludzi.

Janko nie potrafi grać na instrumenty, ale jego umysł jest otwarty na dźwięki świata. Wiosną ucieka z domu, by słuchać muzyki w karczmie, gdzie ludzie tańczą i grają. Skrzypki i basety wypowiadają muzykę, która zasłania mu sen i zniechęca jego duszę. Chce jednak grać sam, więc zaczyna tworzyć własne instrumenty z drewna i skóry, ale ich brzmienie jest ciche i nieskuteczne. Jego marzenie to posiadanie prawdziwych skrzypiec, które grają „cienko” – jak w karczmie.

Jego ciekawość i pożądanie prowadzą go do skrzywdzenia: podczołga się do drzwi kredensu, by przypatrzeć się instrumentom, które są dla niego świętością. Wspomnienia muzyki w karczmie stają się jego jedynym uciecz

**Streszczenie noweli „Janko Muzykant” Henryka Sienkiewicza**  

Nowela opowiada o urodzeniu chłopaka, Janka, który od pierwszych dni życia był słaby i wątły. Wspólnota wsi, zaniepokojona jego stanem zdrowia, przeprowadza ceremonię chrztu, by zasłonić go przed grzechami. Janko rośnie w biedzie – ma wydęty brzuch, spadające policzki i oczy wpatrzone w dalekość, jakby patrzył na świat z niezmiernego odległości. Jego matka, biedna komornica, żywi go z dnia na dzień, często bijąc go i nazywając „odmieńcem”. Choć chłopak nie ma zdolności do roboty, jego największe marzenie to słuchanie muzyki, którą słyszy w naturze: wiatr w drzewach, śpiew ptaków, echo w polu, a nawet głosy ludzi.  

Janko nie potrafi grać na instrumenty, ale jego umysł jest otwarty na dźwięki świata. Wiosną ucieka z domu, by słuchać muzyki w karczmie, gdzie ludzie tańczą i grają. Skrzypki i basety wypowiadają muzykę, która zasłania mu sen i zniechęca jego duszę. Chce jednak grać sam, więc zaczyna tworzyć własne instrumenty z drewna i skóry, ale ich brzmienie jest ciche i nieskuteczne. Jego marzenie to posiadanie prawdziwych skrzypiec, które grają „cienko” – jak w karczmie.  

Jego ciekawość i pożądanie prowadzą go do skrzywdzenia: podczołga się do drzwi kredensu, by przypatrzeć się instrumentom, które są dla niego świętością. Wspomnienia muzyki w karczmie stają się jego jedynym uciecz

In [ ]:
# 2. Przygotowanie dokumentów JSON (Standard RAG)
def prepare_rag_documents(file_path, pages_to_extract):
    documents = []
    doc_pdf = fitz.open(file_path)

    for i, pg_num in enumerate(pages_to_extract):
        if pg_num <= len(doc_pdf):
            page = doc_pdf[pg_num - 1]
            text = page.get_text().strip()

            doc_entry = {
                "doc_id": i,
                "title": f"Hobbit - Page {pg_num}",
                "content": text[:4000]
            }
            documents.append(doc_entry)

    doc_pdf.close()
    return json.dumps(documents, ensure_ascii=False)

In [ ]:
# 3. Parametry
pdf_file = "/the-hobbit-1.pdf"
pages = [67, 68]

rag_context_json = prepare_rag_documents(pdf_file, pages)

In [ ]:
messages = [
    {
        "role": "system",
        "content": (
            "You are a professional literary expert. Your task is to analyze "
            "the provided text fragment delivered in JSON format and prepare "
            "a detailed, reliable summary in English."
        )
    },
    {
        "role": "user",
        "content": f"Here is the book content in JSON format:\n{rag_context_json}\n\nBased on these pages, please write a comprehensive summary in English."
    }
]

# Przetwarzanie promptu (Qwen używa standardowego ChatML)
input_ids = tokenizer.apply_chat_template(
    messages,
    return_tensors="pt",
    add_generation_prompt=True
).to("cuda")

In [ ]:
# 5. Generation
print(f"Qwen is analyzing the document via RAG pipeline... Please wait.\n")

outputs = model.generate(
    input_ids['input_ids'], # Corrected: Pass the actual tensor to model.generate
    max_new_tokens=1000,
    do_sample=True,
    temperature=0.3,
    top_p=0.8,
    repetition_penalty=1.1
)

# Decoding the response
summary = tokenizer.decode(outputs[0][input_ids['input_ids'].shape[-1]:], skip_special_tokens=True) # Corrected: Access the actual tensor for shape

print("--- ENGLISH RAG SUMMARY ---")
print(summary)

Qwen is analyzing the document via RAG pipeline... Please wait.

--- ENGLISH RAG SUMMARY ---
<think>
Okay, let's tackle this query. The user wants a comprehensive summary of the provided JSON content from "The Hobbit" pages 67 and 68.

First, I need to parse the JSON data correctly. There are two documents: page 67 and 68. Each has a title and content. The main character here is Bilbo, who's in a dark tunnel after falling into a goblin trap.

Starting with page 67: Bilbo wakes up in total darkness, feels disoriented, and can't find anyone. He tries moving around but finds nothing. He discovers a ring, puts it in his pocket, and then sits down feeling miserable. He thinks about home and food, which adds to his despair. He's confused about his situation—why he's left behind, why he isn't captured, etc. The key points here are his fear, confusion, discovery of the ring, and his emotional state.

Moving to page 68: After some time, Bilbo searches for his pipe and tobacco, but can't find matches, which makes him feel hopeless. However, he finds his sword from the trolls, which gives him hope. He realizes the sword might be elvish and useful against goblins. He decides to keep moving forward despite the danger. The text contrasts hobbits' abilities with regular humans, highlighting their resilience and skills in dark environments.

I need to ensure the summary covers both pages, mentions the ring's significance, the discovery of the sword, Bilbo's internal struggles, and the comparison between hobbits and others. Also, note the themes of survival, resourcefulness, and the impact of the magical items (ring and sword). Avoid spoilers beyond what's given. Check for coherence and make sure the flow connects both pages smoothly.
</think>

**Summary of *The Hobbit* Pages 67–68:**

In Chapter V, *"Riddles in the Dark,"* Bilbo Gandalf’s journey through the dark tunnels of the goblin realm takes a pivotal turn. After falling into a trap and being left behind by the goblins, Bilbo awakens in utter darkness, disoriented and terrified. He cannot see, hear, or feel anything except the cold stone floor. Desperate, he crawls on hands and knees, eventually touching the tunnel walls but finding no signs of goblins or dwarves. His confusion deepens as he questions why he was abandoned and whether the goblins have already captured him.

A critical moment occurs when Bilbo’s hand brushes against a small, cold metal ring on the tunnel floor. Though he does not recognize its significance at first, he instinctively pockets it, unaware it will later become a vital tool. Frustrated and exhausted, he sinks into despair, longing for the comforts of home—imagining himself frying breakfast in his kitchen. This contrast between his current plight and his normal life intensifies his misery.

On page 68, Bilbo’s resolve begins to shift. He searches for his belongings, discovering his pipe and pouch of tobacco intact—a small comfort—but fails to find matches, crushing his hope of lighting a fire. However, he accidentally uncovers his hidden dagger, gifted by trolls earlier, which he had forgotten. Recognizing its potential as an elvish weapon, he feels a surge of courage. Though uncertain of his path, he resolves to press forward, using the dagger as a deterrent against goblins.

Bilbo’s determination highlights his growing adaptability. Despite his fear, he acknowledges his unique strengths as a hobbit: resilience, quiet movement, and an innate ability to navigate darkness. The chapter underscores themes of survival, self-reliance, and the unexpected power of seemingly mundane objects (like the ring and dagger) in dire circumstances. These moments set the stage for Bilbo’s transformation from a timid hobbit into a resourceful hero.

**Summary of *The Hobbit* Pages 67–68:**  

In Chapter V, *"Riddles in the Dark,"* Bilbo Gandalf’s journey through the dark tunnels of the goblin realm takes a pivotal turn. After falling into a trap and being left behind by the goblins, Bilbo awakens in utter darkness, disoriented and terrified. He cannot see, hear, or feel anything except the cold stone floor. Desperate, he crawls on hands and knees, eventually touching the tunnel walls but finding no signs of goblins or dwarves. His confusion deepens as he questions why he was abandoned and whether the goblins have already captured him.  

A critical moment occurs when Bilbo’s hand brushes against a small, cold metal ring on the tunnel floor. Though he does not recognize its significance at first, he instinctively pockets it, unaware it will later become a vital tool. Frustrated and exhausted, he sinks into despair, longing for the comforts of home—imagining himself frying breakfast in his kitchen. This contrast between his current plight and his normal life intensifies his misery.  

On page 68, Bilbo’s resolve begins to shift. He searches for his belongings, discovering his pipe and pouch of tobacco intact—a small comfort—but fails to find matches, crushing his hope of lighting a fire. However, he accidentally uncovers his hidden dagger, gifted by trolls earlier, which he had forgotten. Recognizing its potential as an elvish weapon, he feels a surge of courage. Though uncertain of his path, he resolves to press forward, using the dagger as a deterrent against goblins.  

Bilbo’s determination highlights his growing adaptability. Despite his fear, he acknowledges his unique strengths as a hobbit: resilience, quiet movement, and an innate ability to navigate darkness. The chapter underscores themes of survival, self-reliance, and the unexpected power of seemingly mundane objects (like the ring and dagger) in dire circumstances. These moments set the stage for Bilbo’s transformation from a timid hobbit into a resourceful hero.

# Analiza tekstu technicznego

Analiza tekstu technicznego polegała na sprawdzeniu jak dobrze model rozumie restrykcje zawarte w tekstu i skomplikowane definicje

In [ ]:
# 2. Funkcja przygotowująca dokumenty JSON
def prepare_rag_documents(file_path, pages_to_extract):
    documents = []
    doc_pdf = fitz.open(file_path)

    for i, pg_num in enumerate(pages_to_extract):
        if pg_num <= len(doc_pdf):
            page = doc_pdf[pg_num - 1]
            text = page.get_text().strip()

            doc_entry = {
                "doc_id": i,
                "title": f"Hager Instrukcja - Strona {pg_num}",
                "content": text[:4000]
            }
            documents.append(doc_entry)

    doc_pdf.close()
    return json.dumps(documents, ensure_ascii=False)

In [ ]:
# 3. Parametry wejściowe
pdf_file = "/content/19PL004_HAAG_BR_Handbuch_Schutz_vers_PL_2019.pdf"

In [ ]:
# --- ZADANIE 2: Zasady bezpieczeństwa (Strona 23) ---
strony_safety = [23]
context_safety = prepare_rag_documents(pdf_file, strony_safety)

prompt_safety = [
    {"role": "system", "content": "You are a professional electrical engineer. Answer in Polish based ONLY on the provided JSON data."},
    {"role": "user", "content": f"Oto dokumentacja techniczna Hager:\n{context_safety}\n\nZadanie: Wypunktuj 5 najważniejszych zasad bezpieczeństwa opisanych w tym fragmencie. Skup się na tym, czego kategorycznie zabrania instrukcja."}
]

In [ ]:
# --- ZADANIE 3: Wyjaśnienie terminologii (Strona 4) ---
strony_defs = [4]
context_defs = prepare_rag_documents(pdf_file, strony_defs)

prompt_defs = [
    {"role": "system", "content": "You are a professional electrical engineer. Answer in Polish based ONLY on the provided JSON data."},
    {"role": "user", "content": f"Oto dokumentacja techniczna Hager:\n{context_defs}\n\nZadanie: Zidentyfikuj 3 skróty techniczne w tekście (np. RCD, RCCB, RCBO) i wyjaśnij ich znaczenie na podstawie dokumentu."}
]

In [ ]:
# 4. Funkcja do generowania odpowiedzi
def generate_response(messages):
    input_ids_batch = tokenizer.apply_chat_template(messages, return_tensors="pt", add_generation_prompt=True).to("cuda")
    outputs = model.generate(input_ids_batch['input_ids'], max_new_tokens=1000, temperature=0.3, top_p=0.8)
    return tokenizer.decode(outputs[0][input_ids_batch['input_ids'].shape[-1]:], skip_special_tokens=True)

In [ ]:
# 5. Uruchomienie analizy
print("--- WYNIK ZADANIA 2 (BEZPIECZEŃSTWO) ---")
print(generate_response(prompt_safety))

print("\n" + "="*50 + "\n")

print("--- WYNIK ZADANIA 3 (DEFINICJE) ---")
print(generate_response(prompt_defs))

The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.

--- WYNIK ZADANIA 2 (BEZPIECZEŃSTWO) ---
<think>
Okay, I need to extract the 5 most important safety rules from the provided Hager technical documentation fragment. The user wants to know what the instructions strictly prohibit. Let me go through the content carefully.

First, looking at the sections mentioned. Each entry has a section number and a description. The key here is to identify prohibitions or strict rules. Let me list out each point:

1. **7.01.4.1.5.1 and 7.01.5.2**: Places with a bathtub or shower – all electrical circuits must be protected with 30 mA. So, no using circuits without this protection here.

2. **7.01.5.53**: Heating surfaces (floor or ceiling) – 30 mA. So, no using lower-rated protection here.

3. **7.02**: Swimming pools and similar – SELV sources must be 30 mA. So, no using other ratings for these areas.

4. **7.03.4.1.5.1**: Saunas with electric heaters – all circuits must be 30 mA. Prohibits using other values.

5. **7.04.4.1.0.10**: Construction sites – sockets and tools up to 32A must be 30 mA. So, no higher ratings here.

Wait, but the user wants the prohibitions. So, each of these sections is stating that certain areas require specific RCDs (30 mA). The prohibitions would be using different values in these areas. For example, in places with a bathtub, you can't use a 100 mA RCD. Similarly, for saunas, you can't use a higher than 30 mA.

Another point is in 7.05.4.1.1.1 for agriculture: sockets are 300 mA, but tools are 30 mA. So, the prohibition here is using 300 mA for tools. Wait, but the user wants what's strictly prohibited. So, in agriculture, the instruction says all installations (sockets) are 300 mA, but tools are 30 mA. So, using 300 mA for tools would be prohibited. But the user might be looking for the main prohibitions.

Also, in 7.12.4.1.1.3.2 for photovoltaic systems: if there's no separation between DC and AC, then 30 mA Type B. So, not separating DC and AC would be prohibited.

Another point is 7.14.4.1.1.3.3 for outdoor lighting: 30 mA. So, using other values here is prohibited.

But the user wants the top 5. Let me check each section again. The main prohibitions are:

1. In areas with bathtubs, showers, or heating surfaces, using RCDs other than 30 mA is prohibited.

2. In swimming pools, using SELV sources without 30 mA RCDs is prohibited.

3. In saunas with electric heaters, using RCDs other than 30 mA is prohibited.

4. In construction sites, using RCDs higher than 30 mA for sockets and tools is prohibited.

5. In photovoltaic systems without DC/AC separation, using RCDs other than 30 mA Type B is prohibited.

Wait, but the user might be looking for the most critical ones. Also, in 7.05.4.1.1.1, agriculture: sockets are 300 mA, but tools are 30 mA. So, using 300 mA for tools is prohibited. But that's a different scenario.

I need to make sure each of the 5 points is a strict prohibition. Let me structure the answer with these points, highlighting the prohibited actions.
</think>

1. **Zabronione stosowanie różnicowoprądowych bezpieczników (RCD) o wartości 100 mA w miejscach z wanną lub prysznicem** (np. sekcja 7.01.5.2).
2. **Zabronione stosowanie RCD o wartości 100 mA w miejscach z ogrzewaniem podłogowym lub sufitowym** (sekcja 7.01.5.53).
3. **Zabronione stosowanie RCD o wartości >30 mA w basenach i zbiornikach z SELV** (sekcja 7.02).
4. **Zabronione stosowanie RCD o wartości >30 mA w saunach z piecami elek

==================================================

--- WYNIK ZADANIA 3 (DEFINICJE) ---
<think>
Okay, the user provided a technical document from Hager, and they want me to identify three technical abbreviations from the text and explain their meanings based on the document. Let me start by looking at the given JSON data.

The content is "Wyłączniki różnicowoprądowe". Translating that, "Wyłączniki" means switches, and "różnicowoprądowe" translates to differential current. So the main term here is "różnicowoprądowe", which is the Polish term for "residual current device" or "RCD".

Now, the user is asking for three technical abbreviations. The example given includes RCD, RCCB, and RCBO. But in the provided text, the only term mentioned is "różnicowoprądowe". However, since the user is expecting three abbreviations, I need to think if there are other possible abbreviations related to this context.

In Polish technical documents, common abbreviations related to RCDs include RCD (Residual Current Device), RCCB (Residual Current Circuit Breaker), and RCBO (Residual Current Breaker with Overcurrent protection). Even though the text only mentions "różnicowoprądowe", which directly translates to RCD, the other abbreviations are standard in the field.

The user might be expecting these standard abbreviations even if they aren't explicitly mentioned in the given text. Since the document's title is "Hager Instrukcja - Strona 4" and the content is about differential switches, it's safe to assume that the document refers to RCDs. Therefore, the three abbreviations would be RCD, RCCB, and RCBO.

I need to explain each abbreviation based on the document. Since the document only mentions "różnicowoprądowe", which is RCD, but the other abbreviations are related. For example, RCCB is a type of RCD that also functions as a circuit breaker, and RCBO combines RCD with overcurrent protection. Even though the text doesn't explicitly state these, they are standard terms in electrical engineering, so it's reasonable to include them as the user might be referring to common industry abbreviations.
</think>

**Skróty techniczne w tekście:**
1. **RCD** – *Residual Current Device* (Wyłącznik różnicowoprądowy).
   - Znaczenie: Urządzenie ochronne, które wykrywa prąd różnicowy (niewykorzystany prąd w obwodzie) i automatycznie wyłącza zasilanie, aby zapobiec porażeniom prądem elektrycznym.

2. **RCCB** – *Residual Current Circuit Breaker* (Wyłącznik różnicowoprądowy z nadmiarowym prądem).
   - Znaczenie: Wyłącza zasilanie zarówno przy prądzie różnicowym, jak i przy przewyższeniach prądu (np. przepięciach).

3. **RCBO** – *Residual Current Breaker with Overcurrent protection* (Wyłącznik różnicowoprądowy z ochroną przed nadmiarowym prądem).
   - Znaczenie: Kombinacja RCD i wyłącznika nadmiarowym prądem (np. przeciążeniem), zapewniająca ochronę przed porażeniem oraz uszkodzeniami obwodu.

**Uwaga:** Tekst dokumentu odnosi się do "wyłączników różnicowoprądowych", co odpowiada skrótowi **RCD**, ale w praktyce w branży elektrycznej często stosuje się również skróty **RCCB** i **RCBO** do opisu różnych typów tych urządzeń.

# Zadanie bezpieczeństwa
1. **Zabronione stosowanie różnicowoprądowych bezpieczników (RCD) o wartości 100 mA w miejscach z wanną lub prysznicem** (np. sekcja 7.01.5.2).  
2. **Zabronione stosowanie RCD o wartości 100 mA w miejscach z ogrzewaniem podłogowym lub sufitowym** (sekcja 7.01.5.53).  
3. **Zabronione stosowanie RCD o wartości >30 mA w basenach i zbiornikach z SELV** (sekcja 7.02).  
4. **Zabronione stosowanie RCD o wartości >30 mA w saunach z piecami elek

# Zadanie wyjaśnienie terminologii

**Skróty techniczne w tekście:**  
1. **RCD** – *Residual Current Device* (Wyłącznik różnicowoprądowy).  
   - Znaczenie: Urządzenie ochronne, które wykrywa prąd różnicowy (niewykorzystany prąd w obwodzie) i automatycznie wyłącza zasilanie, aby zapobiec porażeniom prądem elektrycznym.  

2. **RCCB** – *Residual Current Circuit Breaker* (Wyłącznik różnicowoprądowy z nadmiarowym prądem).  
   - Znaczenie: Wyłącza zasilanie zarówno przy prądzie różnicowym, jak i przy przewyższeniach prądu (np. przepięciach).  

3. **RCBO** – *Residual Current Breaker with Overcurrent protection* (Wyłącznik różnicowoprądowy z ochroną przed nadmiarowym prądem).  
   - Znaczenie: Kombinacja RCD i wyłącznika nadmiarowym prądem (np. przeciążeniem), zapewniająca ochronę przed porażeniem oraz uszkodzeniami obwodu.  

**Uwaga:** Tekst dokumentu odnosi się do "wyłączników różnicowoprądowych", co odpowiada skrótowi **RCD**, ale w praktyce w branży elektrycznej często stosuje się również skróty **RCCB** i **RCBO** do opisu różnych typów tych urządzeń.

In [ ]:
# 2. RAG Document Preparation Function
def prepare_rag_documents(file_path, pages_to_extract):
    documents = []
    doc_pdf = fitz.open(file_path)

    for i, pg_num in enumerate(pages_to_extract):
        if pg_num <= len(doc_pdf):
            page = doc_pdf[pg_num - 1]
            text = page.get_text().strip()

            doc_entry = {
                "doc_id": i,
                "title": f"ICAO Technical Instructions - Page {pg_num}",
                "content": text[:4000]
            }
            documents.append(doc_entry)

    doc_pdf.close()
    return json.dumps(documents, ensure_ascii=False)

In [ ]:
# 3. Parameters
pdf_file = "/content/english instruction.pdf"

In [ ]:
# --- TASK 2: Safety Procedures (Prohibitions - Page 1-1-1) ---
# Note: Page numbering in ICAO docs often uses section-page format (e.g., 1-1-1).
# You need to find the absolute page number in your PDF reader.
safety_pages = [24] # Example absolute page number for General Prohibitions
context_safety = prepare_rag_documents(pdf_file, safety_pages)

prompt_safety = [
    {"role": "system", "content": "You are a specialized dangerous goods aviation inspector. Use ONLY the provided JSON context."},
    {"role": "user", "content": f"Here is the ICAO technical data:\n{context_safety}\n\nTask: List the 5 most critical safety rules or prohibitions described in this section. Focus specifically on what is strictly forbidden."}
]

# --- TASK 3: Technical Terminology (Definitions - Page 1-3-1) ---
def_pages = [34] # Example absolute page number for Terminology/Definitions
context_defs = prepare_rag_documents(pdf_file, def_pages)

prompt_defs = [
    {"role": "system", "content": "You are a specialized dangerous goods aviation inspector. Use ONLY the provided JSON context."},
    {"role": "user", "content": f"Here is the ICAO technical data:\n{context_defs}\n\nTask: Identify 3 technical abbreviations or terms from the text and explain their meaning based on the document."}
]

In [ ]:
# 4. Generation Function
def generate_response(messages):
    input_ids = tokenizer.apply_chat_template(messages, return_tensors="pt", add_generation_prompt=True).to("cuda")
    outputs = model.generate(input_ids['input_ids'], max_new_tokens=1000, temperature=0.3, top_p=0.8)
    return tokenizer.decode(outputs[0][input_ids['input_ids'].shape[-1]:], skip_special_tokens=True)

In [ ]:
# 5. Execution
print("--- TASK 2 RESULT (SAFETY & PROHIBITIONS) ---")
print(generate_response(prompt_safety))

print("\n" + "="*50 + "\n")

print("--- TASK 3 RESULT (DEFINITIONS & TERMINOLOGY) ---")
print(generate_response(prompt_defs))

--- TASK 2 RESULT (SAFETY & PROHIBITIONS) ---
<think>
Okay, let's tackle this query. The user wants the 5 most critical safety rules or prohibitions from the provided ICAO technical data section. They specifically mentioned focusing on what's strictly forbidden.

First, I need to parse the given JSON content. The main section is about exceptions to the dangerous goods regulations under ICAO Technical Instructions. The user is asking for prohibitions, so I should look for rules that explicitly state what's not allowed.

Looking at the content, the exceptions (1.1.5.1 a) to g)) outline situations where the usual rules don't apply. But the prohibitions would be the opposite—what's not allowed even in these exceptions. However, the text is about exceptions, so the main rules (the usual ones) would prohibit certain things, but the exceptions are exceptions to those rules. Wait, the user is asking about the section provided, which is the exceptions. So the prohibitions here would be the restrictions within these exceptions. But the user might be confused. Let me clarify.

The section lists exceptions where the Instructions do not apply. So the usual rules (which are not mentioned here) would prohibit certain things, but in these exceptions, those prohibitions are waived. However, the user is asking for prohibitions described in this section. So maybe the prohibitions are the conditions that must be met, and if they aren't met, it's forbidden. For example, in exception a), if the gas cylinders aren't specifically manufactured, they can't be carried. So the prohibition here is that they must be specifically manufactured. Similarly, for the wet cell batteries, they must be secured upright. If they aren't, it's prohibited.

So the task is to identify the strict prohibitions within these exceptions. Let me go through each part:

1.1.5.1 a) says that dangerous goods must be placed on board with operator approval or be part of the aircraft's permanent equipment. If they don't meet these, they can't be carried. So the prohibition here is not having operator approval or not being part of the equipment.

Similarly, for gas cylinders, they must be specifically manufactured for the gas. If not, they can't be carried. So that's a prohibition.

For wet cell batteries, they must be kept upright and secured. If not, prohibited.

In 1.1.5.1 b), veterinary aid or humane killers must be for animals. If not, prohibited.

In 1.1.5.1 c), dropping for specific purposes. If not, prohibited.

In 1.1.5.1 d), aid for search and rescue. If not, prohibited.

In 1.1.5.1 e), vehicles must meet specific conditions. If not, prohibited.

In 1.1.5.1 g), excess baggage must be marked and meet conditions. If not, prohibited.

Additionally, 1.1.5.2 requires stowing and securing during takeoff/landing. If not, prohibited.

1.1.5.3 requires trained personnel control. If not, prohibited.

1.1.5.4 has conditions for carrying before/after flights. If not met, prohibited.

So the prohibitions are the conditions that must be strictly met. The user wants the most critical ones. Let me list the key prohibitions:

1. Dangerous goods must be approved by the operator (a) or part of the aircraft's equipment (a). If not, prohibited.

2. Gas cylinders must be specifically manufactured for the gas. Otherwise, prohibited.

3. Wet cell batteries must be secured upright. Otherwise, prohibited.

4. Vehicles must be authorized, secured upright, fuel tanks properly filled, and adequate ventilation. If any of these are missing, prohibited.

5. Excess baggage must be marked and meet conditions. Otherwise, prohibited.

Also, the need for stowing and securing during flight, and trained personnel control. But the user wants the top 5. Let me check the content again. The user might be looking for the most critical prohibitions. The key ones are the ones that are strict conditions. The gas cylinders and wet cell batteries are specific. Also, the vehicles and excess baggage conditions. The stowing and personnel control are also prohibitions if not met. But the user might prioritize the most critical ones. Let me structure the answer with the top 5 prohibitions based on the text.
</think>

**5 Most Critical Safety Rules/Prohibitions from ICAO Technical Instructions (Section 1.1.5):**

1. **Unauthorized Dangerous Goods in Medical Aid (1.1.5.1 a)**
   - **Prohibition:** Dangerous goods used for medical aid **must** be **approved by the operator** or part of the aircraft’s permanent equipment. **Carrying unapproved items** is strictly forbidden.

2. **Gas

==================================================

--- TASK 3 RESULT (DEFINITIONS & TERMINOLOGY) ---
<think>
Okay, let's tackle this query. The user wants me to identify three technical abbreviations or terms from the provided ICAO technical data and explain their meanings based on the document.

First, I need to go through the given JSON content carefully. The text is a section from the ICAO Technical Instructions, so I should look for any abbreviations or terms that are defined here. Let me scan through the content again.

Looking at the content, there are several terms mentioned. Let me list them out:

1. **GHS**: The text mentions "GHS. The fourth revised edition of the Globally Harmonized System of Classification and Labelling of Chemicals..." So GHS is an abbreviation for Globally Harmonized System.

2. **UN number**: There's a mention of "ID number. A temporary identification number for entries in Table 3-1 — Dangerous Goods List — which have not been assigned a UN number." So UN number refers to the United Nations number, which is a unique identifier for dangerous goods.

3. **IBC**: The term "Intermediate Bulk Containers (IBCs)" is defined as "Any rigid or flexible portable packaging... designed for mechanical handling..." So IBC stands for Intermediate Bulk Container.

Wait, are there any other terms? Let me check again. There's also "IEC" and "IMO" mentioned, but those are organizations, not abbreviations for terms. The user asked for technical abbreviations or terms. The term "UN number" is a standard term, but the document refers to it as a UN number. Also, "ID number" is mentioned as a temporary identification number. But the user might be looking for terms that are abbreviations.

Alternatively, "GHS" is an abbreviation, "UN number" is a term, and "IBC" is an abbreviation. Let me confirm each of these.

Yes, GHS is an abbreviation. UN number is a term. IBC is an abbreviation. So those three would be the correct answers.

I need to make sure that each term is explained based on the document. For example, GHS is defined in the text. The UN number is mentioned in the context of the ID number. IBC is defined in the section about Intermediate Bulk Containers.

I think that's it. Let me structure the answer with each term and its explanation as per the document.
</think>

**1. GHS**
**Meaning**: GHS stands for *Globally Harmonized System of Classification and Labelling of Chemicals*. It is a UN-published system (document ST/SG/AC.10/30/Rev. 4) that standardizes the classification, labeling, and safety data sheet requirements for hazardous chemicals.

**2. UN Number**
**Meaning**: The *UN number* is a unique four-digit identifier assigned to dangerous goods under the ICAO Technical Instructions. It is used to classify and identify hazardous materials for transport. The document mentions "ID number" as a temporary identifier for entries in the Dangerous Goods List that lack a UN number.

**3. IBC**
**Meaning**: *IBC* stands for *Intermediate Bulk Container*. It refers to rigid or flexible portable packaging designed for mechanical handling, resistant to stresses during transport, and authorized for specific hazardous substances (e.g., UN 3077). The document notes that IBCs are only permitted for certain environmentally hazardous substances under Packing Instruction 956.

Zadanie prohibitions

**5 Most Critical Safety Rules/Prohibitions from ICAO Technical Instructions (Section 1.1.5):**  

1. **Unauthorized Dangerous Goods in Medical Aid (1.1.5.1 a)**  
   - **Prohibition:** Dangerous goods used for medical aid **must** be **approved by the operator** or part of the aircraft’s permanent equipment. **Carrying unapproved items** is strictly forbidden.  

2. **Gas

Zadanie terminology definitions

**1. GHS**  
**Meaning**: GHS stands for *Globally Harmonized System of Classification and Labelling of Chemicals*. It is a UN-published system (document ST/SG/AC.10/30/Rev. 4) that standardizes the classification, labeling, and safety data sheet requirements for hazardous chemicals.  

**2. UN Number**  
**Meaning**: The *UN number* is a unique four-digit identifier assigned to dangerous goods under the ICAO Technical Instructions. It is used to classify and identify hazardous materials for transport. The document mentions "ID number" as a temporary identifier for entries in the Dangerous Goods List that lack a UN number.  

**3. IBC**  
**Meaning**: *IBC* stands for *Intermediate Bulk Container*. It refers to rigid or flexible portable packaging designed for mechanical handling, resistant to stresses during transport, and authorized for specific hazardous substances (e.g., UN 3077). The document notes that IBCs are only permitted for certain environmentally hazardous substances under Packing Instruction 956.

In [ ]:
# 2. Функция подготовки документов JSON (Стандарт RAG)
def prepare_rag_documents(file_path, pages_to_extract):
    documents = []
    doc_pdf = fitz.open(file_path)

    for i, pg_num in enumerate(pages_to_extract):
        if pg_num <= len(doc_pdf):
            page = doc_pdf[pg_num - 1]
            text = page.get_text().strip()

            doc_entry = {
                "doc_id": i,
                "title": f"Техническая инструкция - Страница {pg_num}",
                "content": text[:4000] # Ограничение длины чанка
            }
            documents.append(doc_entry)

    doc_pdf.close()
    return json.dumps(documents, ensure_ascii=False)

In [ ]:
# 3. Входные параметры
pdf_file = "/content/geokniga-tehnicheskayainstrukciyapoprovedeniyugeofizicheskihissledovaniyvskvazhinah.pdf"

In [ ]:
# --- ЗАДАНИЕ 2: Техника безопасности и аварии (Страница 290) ---
safety_pages = [290]
context_safety = prepare_rag_documents(pdf_file, safety_pages)

prompt_safety = [
    {
        "role": "system",
        "content": "Вы — ведущий инженер-геофизик. Отвечайте строго на основе предоставленных данных в формате JSON на РУССКОМ языке."
    },
    {
        "role": "user",
        "content": f"Данные из инструкции:\n{context_safety}\n\nЗадание: Перечислите 5 наиболее важных правил техники безопасности или действий при авариях. Сосредоточьтесь на том, что категорически запрещено инструкцией."
    }
]

# --- ЗАДАНИЕ 3: Техническая терминология и сокращения (Страница 293) ---
def_pages = [15]
context_defs = prepare_rag_documents(pdf_file, def_pages)

prompt_defs = [
    {
        "role": "system",
        "content": "Вы — ведущий инженер-геофизик. Отвечайте строго на основе предоставленных данных в формате JSON на РУССКОМ языке."
    },
    {
        "role": "user",
        "content": f"Данные из инструкции:\n{context_defs}\n\nЗадание: Найдите в тексте 3 технических сокращения (например, ГИС, КС, ПС) и объясните их значение на основе предоставленного документа."
    }
]

In [ ]:
# 4. Funkcja generacji odpowiedzi
def generate_response(messages):
    input_ids = tokenizer.apply_chat_template(
        messages,
        return_tensors="pt",
        add_generation_prompt=True
    ).to("cuda")

    outputs = model.generate(
        input_ids['input_ids'], # Corrected: Access the actual tensor for shape
        max_new_tokens=1000,
        temperature=0.3,
        top_p=0.8,
        repetition_penalty=1.1
    )
    return tokenizer.decode(outputs[0][input_ids['input_ids'].shape[-1]:], skip_special_tokens=True) # Corrected: Access the actual tensor for shape

In [ ]:
# 5. Выполнение анализа
print("--- РЕЗУЛЬТАТ ЗАДАНИЯ 2 (БЕЗОПАСНОСТЬ) ---")
print(generate_response(prompt_safety))

print("\n" + "="*50 + "\n")

print("--- РЕЗУЛЬТАТ ЗАДАНИЯ 3 (ТЕРМИНЫ И СОКРАЩЕНИЯ) ---")
print(generate_response(prompt_defs))

--- РЕЗУЛЬТАТ ЗАДАНИЯ 2 (БЕЗОПАСНОСТЬ) ---
<think>
Хорошо, мне нужно перечислить 5 наиболее важных правил техники безопасности или действий при авариях, основываясь на предоставленной инструкции. Важно сосредоточиться на том, что категорически запрещено.

Сначала прочитаю текст инструкции внимательно. Вижу, что говорится о классификации аварий: сложные и простые. Для сложных аварий есть требования к извещению вышестоящих организаций, органов надзора и т.д. Также упоминается, что после аварии должен быть составлен акт, который определяет причины и виновников. Если есть разногласия, то прибегают к экспертизе.

Теперь нужно найти запрещенные действия. Например, в пункте 6 говорится, что на все аварии, включая случаи оставления грузов и зондов, составляется акт. Возможно, запрещено не составлять акт? Но это не совсем запрет, а требование.

Пункт 7 говорит, что комиссия должна установить причины, виновников и рекомендовать меры. Может быть, запрещено не проводить расследование? Нет, это требуется.

В пункте 5 упоминается, что данные о простых авариях передаются в вышестоящую организацию вместе с отчетами. Возможно, запрещено не сообщать о них? Тоже требование, но не запрет.

Есть пункт 4, где говорится, что сложные аварии и с жертвами должны быть немедленно извещены в определенные органы. Запрещено не сообщать? Да, возможно. То есть запрещено не отправлять извещения. Это первый запрет.

В пункте 6: если есть разногласия, то стороны прибегают к экспертизе. Запрещено не проводить экспертизу? Нет, это обязательное условие. То есть если возникают разногласия, то экспертиза обязательна. Значит, запрещено игнорировать экспертизу при спорах.

В пункте 7: комиссия обязана установить причины, виновников и рекомендовать меры. Запрещено не проводить расследование? Нет, это обязанность. Но если не провести, то это запрет?

Нужно обратить внимание на формулировки "категорически запрещено". Например, в пункте 6: если есть разногласия, то стороны прибегают к экспертизе. То есть, если не провести экспертизу, это запрет.

Также в пункте 4: сложные аварии и с жертвами должны быть немедленно извещены. Запрещено не извещать эти органы.

Еще в пункте 6: если не составить акт, то это запрет? Пункт 6 говорит, что на все аварии составляется акт. То есть запрещено не составлять акт.

Итак, возможные запреты:

1. Не извещать вышестоящие органы, органы надзора и т.д. при сложных авариях.
2. Не составлять акт в случаях аварий.
3. Не проводить экспертизу при разногласиях.
4. Не сообщать о простых авариях в вышестоящую организацию.
5. Не проводить расследование комиссии при сложных авариях.

Нужно проверить, какие из этих пунктов действительно являются запретами. Например, пункт 6 требует составления акта, значит, его не составление запрещено. Пункт 4 требует извещения, поэтому не извещение запрещено. Пункт 5 требует передачи данных о простых авариях, значит, не передача запрещена. Пункт 7 требует проведения расследования, поэтому не проведение запрещено. Пункт 6 также требует экспертизы

==================================================

--- РЕЗУЛЬТАТ ЗАДАНИЯ 3 (ТЕРМИНЫ И СОКРАЩЕНИЯ) ---
<think>
Хорошо, пользователь попросил найти три технических сокращения в данном документе и объяснить их значения. Давайте начну с анализа текста.

Первое, что бросается в глаза — упоминание "ПС". В тексте говорится, что стандартный электрический каротаж включает замер кажущегося удельного сопротивления и запись кривой ПС. Значит, ПС здесь должно быть "кривая потенциалов" или "потенциальная кривая". Но точнее, вероятно, это "потенциалы скважины" или просто "кривая ПС" как общепринятое обозначение.

Далее, в разделе о боковом каротажном зондировании (БКЗ) упоминается, что при БКЗ измеряют кажущееся удельное сопротивление и записывают кривую ПС в масштабе глубин. Это подтверждает, что ПС — это кривая потенциалов или аналогичная величина. Возможно, это "потенциал скважины".

Второе сокращение — БКЗ. В тексте прямо указано, что это "боковое каротажное зондирование". То есть БКЗ расшифровывается как боковое каротажное зондирование, метод исследования скважины для определения свойств пород.

Третье сокращение — НГК. В тексте говорится о нейтронном гамма-каротаже, и сокращение НГК используется. Значит, НГК — это нейтронный гамма-каротаж, метод определения плотности и содержания горючих веществ в породах.

Нужно проверить, нет ли других сокращений. Например, ГК — гамма-каротаж, но это уже не сокращение, а полное название. Также есть "ГИС" в примере пользователя, но в тексте его нет. Поэтому три сокращения: ПС, БКЗ, НГК.
</think>

**1. ПС**
**Значение:** Сокращение от "кривая потенциалов скважины" (или "потенциал скважины"). Используется в контексте записи результатов электрического каротажа, где измеряются кажущиеся удельные сопротивления пород и флюидов.

**2. БКЗ**
**Значение:** Сокращение от "боковое каротажное зондирование". Метод исследования ствола скважины с использованием серии градиент-зондов и микрозондов для определения удельного сопротивления пород и бурового раствора.

**3. НГК**
**Значение:** Сокращение от "нейтронный гамма-каротаж". Метод определения плотности пород и содержания легких элементов (например, углеводородов) через измерение взаимодействия нейтронов и гамма-излучения с образцами пород.

# Zadanie bezpieczeństwa

Итак, возможные запреты:

1. Не извещать вышестоящие органы, органы надзора и т.д. при сложных авариях.
2. Не составлять акт в случаях аварий.
3. Не проводить экспертизу при разногласиях.
4. Не сообщать о простых авариях в вышестоящую организацию.
5. Не проводить расследование комиссии при сложных авариях.

Нужно проверить, какие из этих пунктов действительно являются запретами. Например, пункт 6 требует составления акта, значит, его не составление запрещено. Пункт 4 требует извещения, поэтому не извещение запрещено. Пункт 5 требует передачи данных о простых авариях, значит, не передача запрещена. Пункт 7 требует проведения расследования, поэтому не проведение запрещено. Пункт 6 также требует экспертизы


# Zadanie sprawdzenia terminologii

**1. ПС**  
**Значение:** Сокращение от "кривая потенциалов скважины" (или "потенциал скважины"). Используется в контексте записи результатов электрического каротажа, где измеряются кажущиеся удельные сопротивления пород и флюидов.  

**2. БКЗ**  
**Значение:** Сокращение от "боковое каротажное зондирование". Метод исследования ствола скважины с использованием серии градиент-зондов и микрозондов для определения удельного сопротивления пород и бурового раствора.  

**3. НГК**  
**Значение:** Сокращение от "нейтронный гамма-каротаж". Метод определения плотности пород и содержания легких элементов (например, углеводородов) через измерение взаимодействия нейтронов и гамма-излучения с образцами пород.

# **Iłościowa analiza porównawcza**

**6 prostych zadań**

English version

In [4]:
import pandas as pd
import torch
import time

# 1. Load dataset
df = pd.read_csv("/content/tiktok_instagram_global_100countries.csv")

print("Dataset shape:", df.shape)
print(df.columns.tolist())
df.head()

Dataset shape: (10000, 23)
['user_id', 'country', 'age', 'year', 'internet_penetration', 'mental_health_support_index', 'gdp_index', 'youth_population_ratio', 'baseline_addiction_pressure', 'tiktok_minutes_daily', 'instagram_minutes_daily', 'night_usage_ratio', 'scroll_velocity', 'addiction_pressure', 'attention_span_score', 'dopamine_dependency_score', 'impulsivity_index', 'sleep_hours', 'sleep_quality_index', 'ASI', 'MHRI', 'addiction_score', 'addiction_level']

,user_id,country,age,year,internet_penetration,mental_health_support_index,gdp_index,youth_population_ratio,baseline_addiction_pressure,tiktok_minutes_daily,...,addiction_pressure,attention_span_score,dopamine_dependency_score,impulsivity_index,sleep_hours,sleep_quality_index,ASI,MHRI,addiction_score,addiction_level
0,1,Philippines,59,2050,88.895513,64.347080,0.312067,0.310389,64.762693,242.853130,...,69.981792,77.479304,27.024835,60.044856,6.561778,7.912360,100.0,40.460626,63.512418,High
1,2,Netherlands,23,2035,57.950292,76.257045,0.460320,0.293134,37.592646,98.599951,...,56.862382,78.852713,25.376744,81.769114,9.400197,2.292106,100.0,79.424028,62.688372,High
2,3,Laos,26,2060,40.325805,55.846514,0.893658,0.183055,22.589595,127.221573,...,41.817693,83.573012,19.712386,99.613065,7.810417,2.308761,100.0,88.262729,59.856193,High
3,4,Bulgaria,50,2046,43.838044,28.390576,0.661523,0.155038,57.093084,140.528514,...,70.811984,83.437675,19.874790,86.935944,7.020033,4.512440,100.0,70.905771,59.937395,High
4,5,Zambia,24,2045,43.749943,81.413755,0.275186,0.457115,57.653485,187.748696,...,71.990949,71.993561,33.607727,45.275020,7.900621,4.265014,100.0,51.312439,66.803864,High

In [28]:
correct_answers = {
    "E1": df.loc[df["addiction_score"].idxmax(), "country"],
    "E2": round(df["addiction_score"].mean(), 2),
    "E3": df.groupby("year")["tiktok_minutes_daily"].mean().idxmax(),
    "E4": int((df["addiction_level"] == "High").sum()),
    "E5": round(df["sleep_hours"].min(), 2),
    "E6": df.groupby("country")["instagram_minutes_daily"].mean().idxmax()
}

correct_answers

{'E1': 'Ghana',
 'E2': np.float64(58.55),
 'E3': np.int64(2044),
 'E4': 8680,
 'E5': 3.0,
 'E6': 'UK'}

In [29]:
simple_tasks = [
    {
        "task_id": "E1",
        "difficulty": "easy",
        "question": "Which country has the highest addiction_score in the provided table?",
        "data": df[["country", "addiction_score"]]
            .sort_values("addiction_score", ascending=False)
            .head(30)
    },
    {
        "task_id": "E2",
        "difficulty": "easy",
        "question": "What is the average addiction_score in the provided table? Round the answer to two decimal places.",
        "data": pd.DataFrame({
            "average_addiction_score": [round(df["addiction_score"].mean(), 2)]
        })
    },
    {
        "task_id": "E3",
        "difficulty": "easy",
        "question": "Which year has the highest average tiktok_minutes_daily in the provided table?",
        "data": df.groupby("year", as_index=False)["tiktok_minutes_daily"]
            .mean()
            .sort_values("tiktok_minutes_daily", ascending=False)
    },
    {
        "task_id": "E4",
        "difficulty": "easy",
        "question": "How many observations have addiction_level equal to High?",
        "data": pd.DataFrame({
            "addiction_level": ["High"],
            "number_of_observations": [int((df["addiction_level"] == "High").sum())]
        })
    },
    {
        "task_id": "E5",
        "difficulty": "easy",
        "question": "What is the minimum sleep_hours value in the provided table? Round the answer to two decimal places.",
        "data": pd.DataFrame({
            "minimum_sleep_hours": [round(df["sleep_hours"].min(), 2)]
        })
    },
    {
        "task_id": "E6",
        "difficulty": "easy",
        "question": "Which country has the highest average instagram_minutes_daily in the provided table?",
        "data": df.groupby("country", as_index=False)["instagram_minutes_daily"]
            .mean()
            .sort_values("instagram_minutes_daily", ascending=False)
            .head(30)
    }
]

In [30]:
def generate_response(messages, max_new_tokens=100):
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer(
        text,
        return_tensors="pt"
    ).to(model.device)

    start_time = time.time()

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,  # Изменили тут: temperature=0.0 убран
            pad_token_id=tokenizer.eos_token_id
        )

    end_time = time.time()

    response = tokenizer.decode(
        outputs[0][inputs["input_ids"].shape[-1]:],
        skip_special_tokens=True
    )

    return response.strip(), round(end_time - start_time, 3)

In [31]:
results = []

for task in simple_tasks:
    table_text = task["data"].to_string(index=False)

    messages = [
        {
            "role": "system",
            "content": (
                "You are a data analyst. "
                "Use only the provided table. "
                "Return only the final answer. "
                "Do not explain your reasoning."
            )
        },
        {
            "role": "user",
            "content": f"""
Here is the table:

{table_text}

Task:
{task["question"]}
"""
        }
    ]

    answer, response_time = generate_response(messages)

    results.append({
        "model": "Qwen3-8B",
        "task_id": task["task_id"],
        "difficulty": task["difficulty"],
        "question": task["question"],
        "model_answer": answer,
        "correct_answer": correct_answers[task["task_id"]],
        "response_time_sec": response_time
    })

results_df = pd.DataFrame(results)
results_df

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

,model,task_id,difficulty,question,model_answer,correct_answer,response_time_sec
0,Qwen3-8B,E1,easy,Which country has the highest addiction_score ...,<think>\n</think>\n\nGhana,Ghana,0.701
1,Qwen3-8B,E2,easy,What is the average addiction_score in the pro...,<think>\n</think>\n\n58.55,58.55,0.990
2,Qwen3-8B,E3,easy,Which year has the highest average tiktok_minu...,<think>\n</think>\n\n2044,2044,0.895
3,Qwen3-8B,E4,easy,How many observations have addiction_level equ...,<think>\n</think>\n\n8680,8680,0.894
4,Qwen3-8B,E5,easy,What is the minimum sleep_hours value in the p...,<think>\n</think>\n\n3.00,3.0,0.886
5,Qwen3-8B,E6,easy,Which country has the highest average instagra...,<think>\n</think>\n\nUK,UK,0.610

In [32]:
import re

def clean_answer(x):
    x = str(x)

    x = re.sub(r"<think>.*?</think>", "", x, flags=re.DOTALL)

    x = x.strip()

    return x.lower()


def compare_answers(model_answer, correct_answer):

    model_answer = clean_answer(model_answer)
    correct_answer = clean_answer(correct_answer)

    try:
        model_num = float(model_answer)
        correct_num = float(correct_answer)

        return abs(model_num - correct_num) < 0.001

    except:
        return model_answer == correct_answer


results_df["is_correct"] = results_df.apply(
    lambda row: compare_answers(
        row["model_answer"],
        row["correct_answer"]
    ),
    axis=1
)

accuracy = results_df["is_correct"].mean()

print("Accuracy:", round(accuracy * 100, 2), "%")

Accuracy: 100.0 %

Polska wersja

In [47]:
simple_tasks_pl = [
    {
        "task_id": "E1",
        "difficulty": "easy",
        "language": "PL",
        "question": "Który kraj ma najwyższą wartość addiction_score w podanej tabeli?",
        "data": df[["country", "addiction_score"]]
            .sort_values("addiction_score", ascending=False)
            .head(30)
    },
    {
        "task_id": "E2",
        "difficulty": "easy",
        "language": "PL",
        "question": "Jaka jest średnia wartość addiction_score w podanej tabeli? Zaokrąglij odpowiedź do dwóch miejsc po przecinku.",
        "data": pd.DataFrame({
            "average_addiction_score": [round(df["addiction_score"].mean(), 2)]
        })
    },
    {
        "task_id": "E3",
        "difficulty": "easy",
        "language": "PL",
        "question": "W którym roku średnia wartość tiktok_minutes_daily była najwyższa w podanej tabeli?",
        "data": df.groupby("year", as_index=False)["tiktok_minutes_daily"]
            .mean()
            .sort_values("tiktok_minutes_daily", ascending=False)
    },
    {
        "task_id": "E4",
        "difficulty": "easy",
        "language": "PL",
        "question": "Ile obserwacji ma addiction_level równy High?",
        "data": pd.DataFrame({
            "addiction_level": ["High"],
            "number_of_observations": [int((df["addiction_level"] == "High").sum())]
        })
    },
    {
        "task_id": "E5",
        "difficulty": "easy",
        "language": "PL",
        "question": "Jaka jest minimalna wartość sleep_hours w podanej tabeli? Zaokrąglij odpowiedź do dwóch miejsc po przecinku.",
        "data": pd.DataFrame({
            "minimum_sleep_hours": [round(df["sleep_hours"].min(), 2)]
        })
    },
    {
        "task_id": "E6",
        "difficulty": "easy",
        "language": "PL",
        "question": "Który kraj ma najwyższą średnią wartość instagram_minutes_daily w podanej tabeli?",
        "data": df.groupby("country", as_index=False)["instagram_minutes_daily"]
            .mean()
            .sort_values("instagram_minutes_daily", ascending=False)
            .head(30)
    }
]

In [48]:
def generate_response(messages, max_new_tokens=100, enable_thinking=False):
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
        enable_thinking=enable_thinking  # <-- correct Qwen3 parameter
    )
    inputs = tokenizer(
        text,
        return_tensors="pt"
    ).to(model.device)

    start_time = time.time()
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id
        )
    end_time = time.time()

    response = tokenizer.decode(
        outputs[0][inputs["input_ids"].shape[-1]:],
        skip_special_tokens=True
    )
    return response.strip(), round(end_time - start_time, 3)

In [49]:
for task in simple_tasks_pl:
    table_text = task["data"].to_string(index=False)

    messages = [
        {
            "role": "system",
            "content": (
                "Jesteś analitykiem danych. "
                "Korzystaj wyłącznie z podanej tabeli. "
                "Twój proces myślenia (think) oraz odpowiedź MUSZĄ być w języku polskim. " # Заставляем думать по-польsky, это сократит текст
                "Zwróć tylko końcową odpowiedź. "
                "Nie wyjaśniaj toku rozumowania w końcowej odpowiedzi."
            )
        },
        {
            "role": "user",
            "content": f"Oto tabela:\n\n{table_text}\n\nZadanie:\n{task['question']}"
        }
    ]

    # Если модель всё равно пишет гигантские тексты в <think>,
    # можно уменьшить max_new_tokens в generate_response, например до 50.
    answer, response_time = generate_response(messages, max_new_tokens=50, enable_thinking=False)

    # ... (дальше твой код добавления в results_pl)


results_pl = []

for task in simple_tasks_pl:
    table_text = task["data"].to_string(index=False)

    messages = [
        {
            "role": "system",
            "content": (
                "Jesteś analitykiem danych. "
                "Korzystaj wyłącznie z podanej tabeli. "
                "Zwróć tylko końcową odpowiedź. "
                "Nie wyjaśniaj toku rozumowania."
            )
        },
        {
            "role": "user",
            "content": f"""
Oto tabela:

{table_text}

Zadanie:
{task["question"]}
"""
        }
    ]

    answer, response_time = generate_response(messages, max_new_tokens=100)

    results_pl.append({
        "model": "Qwen3-8B",
        "task_id": task["task_id"],
        "difficulty": task["difficulty"],
        "language": task["language"],
        "question": task["question"],
        "model_answer": answer,
        "correct_answer": correct_answers[task["task_id"]],
        "response_time_sec": response_time
    })

results_pl_df = pd.DataFrame(results_pl)
results_pl_df

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

      model task_id difficulty language                                                                                             question model_answer correct_answer  response_time_sec
0  Qwen3-8B      E1       easy       PL                                    Który kraj ma najwyższą wartość addiction_score w podanej tabeli?        Ghana          Ghana              0.322
1  Qwen3-8B      E2       easy       PL  Jaka jest średnia wartość addiction_score w podanej tabeli? Zaokrąglij odpowiedź do dwóch miejsc...        58.55          58.55              0.611
2  Qwen3-8B      E3       easy       PL                  W którym roku średnia wartość tiktok_minutes_daily była najwyższa w podanej tabeli?         2044           2044              0.510
3  Qwen3-8B      E4       easy       PL                                                        Ile obserwacji ma addiction_level równy High?         8680           8680              0.513
4  Qwen3-8B      E5       easy       PL  Jaka jest minimalna wartość sleep_hours w podanej tabeli? Zaokrąglij odpowiedź do dwóch miejsc p...         3.00            3.0              0.534
5  Qwen3-8B      E6       easy       PL                    Który kraj ma najwyższą średnią wartość instagram_minutes_daily w podanej tabeli?           UK             UK              0.232

In [50]:
import re

def clean_answer(x):
    x = str(x)
    x = re.sub(r"<think>.*?</think>", "", x, flags=re.DOTALL)  # closed blocks
    x = re.sub(r"<think>.*", "", x, flags=re.DOTALL)            # unclosed/truncated
    x = x.strip()
    return x.lower()


def compare_answers(model_answer, correct_answer):

    model_answer = clean_answer(model_answer)
    correct_answer = clean_answer(correct_answer)

    try:
        model_num = float(model_answer)
        correct_num = float(correct_answer)

        return abs(model_num - correct_num) < 0.001

    except:
        return model_answer == correct_answer

# Применяем проверку строго к ПОЛЬСКОМУ датафрейму results_pl_df
results_pl_df["is_correct"] = results_pl_df.apply(
    lambda row: compare_answers(
        row["model_answer"],
        row["correct_answer"]
    ),
    axis=1
)

accuracy_pl = results_pl_df["is_correct"].mean()

print("Polish Prompts Accuracy:", round(accuracy_pl * 100, 2), "%")

Polish Prompts Accuracy: 100.0 %

Rosyjska wersja

In [51]:
simple_tasks_ru = [
    {
        "task_id": "E1",
        "difficulty": "easy",
        "language": "RU",
        "question": "Какая страна имеет самое высокое значение addiction_score в предоставленной таблице?",
        "data": df[["country", "addiction_score"]]
            .sort_values("addiction_score", ascending=False)
            .head(30)
    },
    {
        "task_id": "E2",
        "difficulty": "easy",
        "language": "RU",
        "question": "Каково среднее значение addiction_score в предоставленной таблице? Округли ответ до двух знаков после запятой.",
        "data": pd.DataFrame({
            "average_addiction_score": [round(df["addiction_score"].mean(), 2)]
        })
    },
    {
        "task_id": "E3",
        "difficulty": "easy",
        "language": "RU",
        "question": "В каком году среднее значение tiktok_minutes_daily было самым высоким в предоставленной таблице?",
        "data": df.groupby("year", as_index=False)["tiktok_minutes_daily"]
            .mean()
            .sort_values("tiktok_minutes_daily", ascending=False)
    },
    {
        "task_id": "E4",
        "difficulty": "easy",
        "language": "RU",
        "question": "Сколько наблюдений имеют значение addiction_level, равное High?",
        "data": pd.DataFrame({
            "addiction_level": ["High"],
            "number_of_observations": [int((df["addiction_level"] == "High").sum())]
        })
    },
    {
        "task_id": "E5",
        "difficulty": "easy",
        "language": "RU",
        "question": "Каково минимальное значение sleep_hours в предоставленной таблице? Округли ответ до двух знаков после запятой.",
        "data": pd.DataFrame({
            "minimum_sleep_hours": [round(df["sleep_hours"].min(), 2)]
        })
    },
    {
        "task_id": "E6",
        "difficulty": "easy",
        "language": "RU",
        "question": "Какая страна имеет самое высокое среднее значение instagram_minutes_daily в предоставленной таблице?",
        "data": df.groupby("country", as_index=False)["instagram_minutes_daily"]
            .mean()
            .sort_values("instagram_minutes_daily", ascending=False)
            .head(30)
    }
]

In [52]:
def generate_response(messages, max_new_tokens=100, enable_thinking=False):
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
        enable_thinking=enable_thinking  # <-- correct Qwen3 parameter
    )
    inputs = tokenizer(
        text,
        return_tensors="pt"
    ).to(model.device)

    start_time = time.time()
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id
        )
    end_time = time.time()

    response = tokenizer.decode(
        outputs[0][inputs["input_ids"].shape[-1]:],
        skip_special_tokens=True
    )
    return response.strip(), round(end_time - start_time, 3)

In [57]:
results_ru = []
for task in simple_tasks_ru:
    table_text = task["data"].to_string(index=False)
    messages = [                          # <-- must be indented inside loop
        {
            "role": "system",
            "content": (
                "Ты аналитик данных. "
                "Используй только предоставленную таблицу. "
                "Верни только итоговый ответ. "
                "Не объясняй ход рассуждений."
            )
        },
        {
            "role": "user",
            "content": f"""
Вот таблица:
{table_text}

Задание:
{task["question"]}
"""
        }
    ]
    answer, response_time = generate_response(messages, max_new_tokens=50, enable_thinking=False)
    results_ru.append({                   # <-- must be indented inside loop
        "model": "Qwen3-8B",
        "task_id": task["task_id"],
        "difficulty": task["difficulty"],
        "language": task["language"],
        "question": task["question"],
        "model_answer": answer,
        "correct_answer": correct_answers[task["task_id"]],
        "response_time_sec": response_time
    })

results_ru_df = pd.DataFrame(results_ru)
results_ru_df

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

      model task_id difficulty language                                                                                             question model_answer correct_answer  response_time_sec
0  Qwen3-8B      E1       easy       RU                 Какая страна имеет самое высокое значение addiction_score в предоставленной таблице?        Ghana          Ghana              0.323
1  Qwen3-8B      E2       easy       RU  Каково среднее значение addiction_score в предоставленной таблице? Округли ответ до двух знаков ...        58.55          58.55              0.615
2  Qwen3-8B      E3       easy       RU     В каком году среднее значение tiktok_minutes_daily было самым высоким в предоставленной таблице?         2044           2044              0.516
3  Qwen3-8B      E4       easy       RU                                      Сколько наблюдений имеют значение addiction_level, равное High?         8680           8680              0.515
4  Qwen3-8B      E5       easy       RU  Каково минимальное значение sleep_hours в предоставленной таблице? Округли ответ до двух знаков ...         3.00            3.0              0.514
5  Qwen3-8B      E6       easy       RU  Какая страна имеет самое высокое среднее значение instagram_minutes_daily в предоставленной табл...           UK             UK              0.226

In [58]:
import re

def clean_answer(x):
    x = str(x)
    x = re.sub(r"<think>.*?</think>", "", x, flags=re.DOTALL)  # closed blocks
    x = re.sub(r"<think>.*", "", x, flags=re.DOTALL)            # unclosed/truncated
    x = x.strip()
    return x.lower()


def compare_answers(model_answer, correct_answer):

    model_answer = clean_answer(model_answer)
    correct_answer = clean_answer(correct_answer)

    try:
        model_num = float(model_answer)
        correct_num = float(correct_answer)

        return abs(model_num - correct_num) < 0.001

    except:
        return model_answer == correct_answer

# Применяем проверку строго к russian датафрейму results_ru_df
results_ru_df["is_correct"] = results_ru_df.apply(
    lambda row: compare_answers(
        row["model_answer"],
        row["correct_answer"]
    ),
    axis=1
)

accuracy_ru = results_ru_df["is_correct"].mean()

print("Russian Prompts Accuracy:", round(accuracy_ru * 100, 2), "%")

Russian Prompts Accuracy: 100.0 %

**6 medium tasks**

english prompt

In [67]:
# =========================
# MEDIUM TASKS — QWEN
# =========================

medium_correct_answers = {
    "M1": round(
        (
            df[df["year"] == 2030]["tiktok_minutes_daily"].mean()
            - df[df["year"] == 2020]["tiktok_minutes_daily"].mean()
        )
        / df[df["year"] == 2020]["tiktok_minutes_daily"].mean()
        * 100,
        2
    ),

    "M2": (
        df.groupby("country")[["tiktok_minutes_daily", "instagram_minutes_daily"]]
        .mean()
        .assign(diff=lambda x: abs(x["tiktok_minutes_daily"] - x["instagram_minutes_daily"]))
        .sort_values("diff", ascending=False)
        .index[0]
    ),

    "M3": (
        df.groupby("country")["addiction_score"]
        .mean()
        .idxmax()
    ),

    "M4": round(
        (df["sleep_quality_index"] < df["sleep_quality_index"].mean()).mean() * 100,
        2
    ),

    "M5": round(
        df[df["addiction_level"] == "High"]["MHRI"].mean()
        - df[df["addiction_level"] == "Low"]["MHRI"].mean(),
        2
    ),

    "M6": (
        df.groupby("country")["dopamine_dependency_score"]
        .mean()
        .sort_values(ascending=False)
        .head(3)
        .index.tolist()
    )
}

medium_correct_answers

{'M1': np.float64(4.45),
 'M2': 'Maldives',
 'M3': 'Tanzania',
 'M4': np.float64(49.99),
 'M5': np.float64(6.82),
 'M6': ['Tanzania', 'Argentina', 'Malaysia']}

In [68]:
medium_tasks_en = [
    {
        "task_id": "M1",
        "difficulty": "medium",
        "language": "EN",
        "question": "By what percentage did the average tiktok_minutes_daily increase or decrease between 2020 and 2030? Round the answer to two decimal places.",
        "data": df[df["year"].isin([2020, 2030])]
            .groupby("year", as_index=False)["tiktok_minutes_daily"]
            .mean()
    },
    {
        "task_id": "M2",
        "difficulty": "medium",
        "language": "EN",
        "question": "Which country has the largest absolute difference between average tiktok_minutes_daily and average instagram_minutes_daily?",
        "data": df.groupby("country", as_index=False)[["tiktok_minutes_daily", "instagram_minutes_daily"]]
            .mean()
            .assign(diff=lambda x: abs(x["tiktok_minutes_daily"] - x["instagram_minutes_daily"]))
            .sort_values("diff", ascending=False)
            .head(30)
    },
    {
        "task_id": "M3",
        "difficulty": "medium",
        "language": "EN",
        "question": "Which country has the highest average addiction_score?",
        "data": df.groupby("country", as_index=False)["addiction_score"]
            .mean()
            .sort_values("addiction_score", ascending=False)
            .head(30)
    },
    {
        "task_id": "M4",
        "difficulty": "medium",
        "language": "EN",
        "question": "What percentage of observations have sleep_quality_index below the overall average? Round the answer to two decimal places.",
        "data": pd.DataFrame({
            "overall_average_sleep_quality_index": [df["sleep_quality_index"].mean()],
            "observations_below_average": [(df["sleep_quality_index"] < df["sleep_quality_index"].mean()).sum()],
            "total_observations": [len(df)],
            "percentage_below_average": [round((df["sleep_quality_index"] < df["sleep_quality_index"].mean()).mean() * 100, 2)]
        })
    },
    {
        "task_id": "M5",
        "difficulty": "medium",
        "language": "EN",
        "question": "What is the difference between the average MHRI for High addiction_level and Low addiction_level? Round the answer to two decimal places.",
        "data": df[df["addiction_level"].isin(["High", "Low"])]
            .groupby("addiction_level", as_index=False)["MHRI"]
            .mean()
    },
    {
        "task_id": "M6",
        "difficulty": "medium",
        "language": "EN",
        "question": "Which three countries have the highest average dopamine_dependency_score? Return the country names only.",
        "data": df.groupby("country", as_index=False)["dopamine_dependency_score"]
            .mean()
            .sort_values("dopamine_dependency_score", ascending=False)
            .head(10)
    }
]

In [69]:
def generate_response(messages, max_new_tokens=50, enable_thinking=False):
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
        enable_thinking=enable_thinking  # <-- correct Qwen3 parameter
    )
    inputs = tokenizer(
        text,
        return_tensors="pt"
    ).to(model.device)

    start_time = time.time()
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id
        )
    end_time = time.time()

    response = tokenizer.decode(
        outputs[0][inputs["input_ids"].shape[-1]:],
        skip_special_tokens=True
    )
    return response.strip(), round(end_time - start_time, 3)

In [70]:
results_medium_en = []

for task in medium_tasks_en:
    table_text = task["data"].to_string(index=False)

    messages = [
        {
            "role": "system",
            "content": (
                "You are a data analyst. "
                "Use only the provided table. "
                "Return only the final answer. "
                "Do not explain your reasoning."
            )
        },
        {
            "role": "user",
            "content": f"""
Here is the table:

{table_text}

Task:
{task["question"]}
"""
        }
    ]

    answer, response_time = generate_response(messages, max_new_tokens=50, enable_thinking=False)

    results_medium_en.append({
        "model": "Qwen3-8B",
        "task_id": task["task_id"],
        "difficulty": task["difficulty"],
        "language": task["language"],
        "question": task["question"],
        "model_answer": answer,
        "correct_answer": medium_correct_answers[task["task_id"]],
        "response_time_sec": response_time
    })

results_medium_en_df = pd.DataFrame(results_medium_en)
results_medium_en_df

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

      model task_id difficulty language                                                                                             question                                                                                         model_answer                   correct_answer  response_time_sec
0  Qwen3-8B      M1     medium       EN  By what percentage did the average tiktok_minutes_daily increase or decrease between 2020 and 20...  To calculate the percentage change in the average `tiktok_minutes_daily` between 2020 and 2030, ...                             4.45              4.913
1  Qwen3-8B      M2     medium       EN  Which country has the largest absolute difference between average tiktok_minutes_daily and avera...                                                                                             Maldives                         Maldives              0.331
2  Qwen3-8B      M3     medium       EN                                               Which country has the highest average addiction_score?                                                                                             Tanzania                         Tanzania              0.417
3  Qwen3-8B      M4     medium       EN  What percentage of observations have sleep_quality_index below the overall average? Round the an...                                                                                               49.99%                            49.99              0.695
4  Qwen3-8B      M5     medium       EN  What is the difference between the average MHRI for High addiction_level and Low addiction_level...                                                                                                 5.82                             6.82              0.510
5  Qwen3-8B      M6     medium       EN  Which three countries have the highest average dopamine_dependency_score? Return the country nam...                                                                        Tanzania, Argentina, Malaysia  [Tanzania, Argentina, Malaysia]              0.793

English prompt medium accuracy: 66,66%

polish prompt

In [71]:
medium_tasks_pl = [
    {
        "task_id": "M1",
        "difficulty": "medium",
        "language": "PL",
        "question": "O ile procent wzrosła lub spadła średnia wartość tiktok_minutes_daily między 2020 a 2030 rokiem? Zaokrąglij odpowiedź do dwóch miejsc po przecinku.",
        "data": df[df["year"].isin([2020, 2030])]
                    .groupby("year", as_index=False)["tiktok_minutes_daily"]
                    .mean()
    },
    {
        "task_id": "M2",
        "difficulty": "medium",
        "language": "PL",
        "question": "Który kraj ma największą bezwzględną różnicę między średnią wartością tiktok_minutes_daily a średnią wartością instagram_minutes_daily?",
        "data": df.groupby("country", as_index=False)[["tiktok_minutes_daily", "instagram_minutes_daily"]]
                    .mean()
                    .assign(diff=lambda x: abs(x["tiktok_minutes_daily"] - x["instagram_minutes_daily"]))
                    .sort_values("diff", ascending=False)
                    .head(30)
    },
    {
        "task_id": "M3",
        "difficulty": "medium",
        "language": "PL",
        "question": "Który kraj ma najwyższą średnią wartość addiction_score?",
        "data": df.groupby("country", as_index=False)["addiction_score"]
                    .mean()
                    .sort_values("addiction_score", ascending=False)
                    .head(30)
    },
    {
        "task_id": "M4",
        "difficulty": "medium",
        "language": "PL",
        "question": "Jaki procent obserwacji ma wartość sleep_quality_index poniżej ogólnej średniej? Zaokrąglij odpowiedź do dwóch miejsc po przecinku.",
        "data": pd.DataFrame({
            "overall_average_sleep_quality_index": [df["sleep_quality_index"].mean()],
            "observations_below_average": [(df["sleep_quality_index"] < df["sleep_quality_index"].mean()).sum()],
            "total_observations": [len(df)],
            "percentage_below_average": [round((df["sleep_quality_index"] < df["sleep_quality_index"].mean()).mean() * 100, 2)]
        })
    },
    {
        "task_id": "M5",
        "difficulty": "medium",
        "language": "PL",
        "question": "Jaka jest różnica między średnią wartością MHRI dla poziomu uzależnienia High a Low? Zaokrąglij odpowiedź do dwóch miejsc po przecinku.",
        "data": df[df["addiction_level"].isin(["High", "Low"])]
                    .groupby("addiction_level", as_index=False)["MHRI"]
                    .mean()
    },
    {
        "task_id": "M6",
        "difficulty": "medium",
        "language": "PL",
        "question": "Które trzy kraje mają najwyższą średnią wartość dopamine_dependency_score? Podaj tylko nazwy krajów.",
        "data": df.groupby("country", as_index=False)["dopamine_dependency_score"]
                    .mean()
                    .sort_values("dopamine_dependency_score", ascending=False)
                    .head(10)
    }
]

In [72]:
def generate_response(messages, max_new_tokens=50, enable_thinking=False):
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
        enable_thinking=enable_thinking  # <-- correct Qwen3 parameter
    )
    inputs = tokenizer(
        text,
        return_tensors="pt"
    ).to(model.device)

    start_time = time.time()
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id
        )
    end_time = time.time()

    response = tokenizer.decode(
        outputs[0][inputs["input_ids"].shape[-1]:],
        skip_special_tokens=True
    )
    return response.strip(), round(end_time - start_time, 3)

In [73]:
results_medium_pl = []
for task in medium_tasks_pl:
    table_text = task["data"].to_string(index=False)
    messages = [
        {
            "role": "system",
            "content": (
                "Jesteś analitykiem danych. "
                "Korzystaj wyłącznie z podanej tabeli. "
                "Zwróć tylko końcową odpowiedź. "
                "Nie wyjaśniaj toku rozumowania."
            )
        },
        {
            "role": "user",
            "content": f"Oto tabela:\n\n{table_text}\n\nZadanie:\n{task['question']}"
        }
    ]
    answer, response_time = generate_response(messages, max_new_tokens=50, enable_thinking=False)
    results_medium_pl.append({
        "model": "Qwen3-8B",
        "task_id": task["task_id"],
        "difficulty": task["difficulty"],
        "language": task["language"],
        "question": task["question"],
        "model_answer": answer,
        "correct_answer": medium_correct_answers[task["task_id"]],
        "response_time_sec": response_time
    })

results_medium_pl_df = pd.DataFrame(results_medium_pl)
results_medium_pl_df

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

      model task_id difficulty language                                                                                             question                                              model_answer                   correct_answer  response_time_sec
0  Qwen3-8B      M1     medium       PL  O ile procent wzrosła lub spadła średnia wartość tiktok_minutes_daily między 2020 a 2030 rokiem?...                                                    12,99%                             4.45              0.711
1  Qwen3-8B      M2     medium       PL  Który kraj ma największą bezwzględną różnicę między średnią wartością tiktok_minutes_daily a śre...                                                  Maldives                         Maldives              0.344
2  Qwen3-8B      M3     medium       PL                                             Który kraj ma najwyższą średnią wartość addiction_score?                                                  Tanzania                         Tanzania              0.422
3  Qwen3-8B      M4     medium       PL  Jaki procent obserwacji ma wartość sleep_quality_index poniżej ogólnej średniej? Zaokrąglij odpo...                                                    49.99%                            49.99              0.710
4  Qwen3-8B      M5     medium       PL  Jaka jest różnica między średnią wartością MHRI dla poziomu uzależnienia High a Low? Zaokrąglij ...  45.803085 - 38.980749 = 6.822336  \nRóżnica wynosi 6.82.                             6.82              4.196
5  Qwen3-8B      M6     medium       PL  Które trzy kraje mają najwyższą średnią wartość dopamine_dependency_score? Podaj tylko nazwy kra...                             Tanzania, Argentina, Malaysia  [Tanzania, Argentina, Malaysia]              0.808

Polish prompt medium accuracy = 83,33%

Russian prompt

In [74]:
medium_tasks_ru = [
    {
        "task_id": "M1",
        "difficulty": "medium",
        "language": "RU",
        "question": "На сколько процентов увеличилось или уменьшилось среднее значение tiktok_minutes_daily между 2020 и 2030 годами? Округли ответ до двух знаков после запятой.",
        "data": df[df["year"].isin([2020, 2030])]
                    .groupby("year", as_index=False)["tiktok_minutes_daily"]
                    .mean()
    },
    {
        "task_id": "M2",
        "difficulty": "medium",
        "language": "RU",
        "question": "Какая страна имеет наибольшую абсолютную разницу между средним значением tiktok_minutes_daily и средним значением instagram_minutes_daily?",
        "data": df.groupby("country", as_index=False)[["tiktok_minutes_daily", "instagram_minutes_daily"]]
                    .mean()
                    .assign(diff=lambda x: abs(x["tiktok_minutes_daily"] - x["instagram_minutes_daily"]))
                    .sort_values("diff", ascending=False)
                    .head(30)
    },
    {
        "task_id": "M3",
        "difficulty": "medium",
        "language": "RU",
        "question": "Какая страна имеет наибольшее среднее значение addiction_score?",
        "data": df.groupby("country", as_index=False)["addiction_score"]
                    .mean()
                    .sort_values("addiction_score", ascending=False)
                    .head(30)
    },
    {
        "task_id": "M4",
        "difficulty": "medium",
        "language": "RU",
        "question": "Какой процент наблюдений имеет значение sleep_quality_index ниже общего среднего? Округли ответ до двух знаков после запятой.",
        "data": pd.DataFrame({
            "overall_average_sleep_quality_index": [df["sleep_quality_index"].mean()],
            "observations_below_average": [(df["sleep_quality_index"] < df["sleep_quality_index"].mean()).sum()],
            "total_observations": [len(df)],
            "percentage_below_average": [round((df["sleep_quality_index"] < df["sleep_quality_index"].mean()).mean() * 100, 2)]
        })
    },
    {
        "task_id": "M5",
        "difficulty": "medium",
        "language": "RU",
        "question": "Какова разница между средним значением MHRI для уровня зависимости High и Low? Округли ответ до двух знаков после запятой.",
        "data": df[df["addiction_level"].isin(["High", "Low"])]
                    .groupby("addiction_level", as_index=False)["MHRI"]
                    .mean()
    },
    {
        "task_id": "M6",
        "difficulty": "medium",
        "language": "RU",
        "question": "Какие три страны имеют наибольшее среднее значение dopamine_dependency_score? Укажи только названия стран.",
        "data": df.groupby("country", as_index=False)["dopamine_dependency_score"]
                    .mean()
                    .sort_values("dopamine_dependency_score", ascending=False)
                    .head(10)
    }
]

In [75]:
def generate_response(messages, max_new_tokens=50, enable_thinking=False):
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
        enable_thinking=enable_thinking  # <-- correct Qwen3 parameter
    )
    inputs = tokenizer(
        text,
        return_tensors="pt"
    ).to(model.device)

    start_time = time.time()
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id
        )
    end_time = time.time()

    response = tokenizer.decode(
        outputs[0][inputs["input_ids"].shape[-1]:],
        skip_special_tokens=True
    )
    return response.strip(), round(end_time - start_time, 3)

In [76]:
results_medium_ru = []
for task in medium_tasks_ru:
    table_text = task["data"].to_string(index=False)
    messages = [
        {
            "role": "system",
            "content": (
                "Ты аналитик данных. "
                "Используй только предоставленную таблицу. "
                "Верни только итоговый ответ. "
                "Не объясняй ход рассуждений."
            )
        },
        {
            "role": "user",
            "content": f"Вот таблица:\n\n{table_text}\n\nЗадание:\n{task['question']}"
        }
    ]
    answer, response_time = generate_response(messages, max_new_tokens=50, enable_thinking=False)
    results_medium_ru.append({
        "model": "Qwen3-8B",
        "task_id": task["task_id"],
        "difficulty": task["difficulty"],
        "language": task["language"],
        "question": task["question"],
        "model_answer": answer,
        "correct_answer": medium_correct_answers[task["task_id"]],
        "response_time_sec": response_time
    })

results_medium_ru_df = pd.DataFrame(results_medium_ru)
results_medium_ru_df

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

      model task_id difficulty language                                                                                             question                   model_answer                   correct_answer  response_time_sec
0  Qwen3-8B      M1     medium       RU  На сколько процентов увеличилось или уменьшилось среднее значение tiktok_minutes_daily между 202...                          1.18%                             4.45              0.610
1  Qwen3-8B      M2     medium       RU  Какая страна имеет наибольшую абсолютную разницу между средним значением tiktok_minutes_daily и ...                       Maldives                         Maldives              0.346
2  Qwen3-8B      M3     medium       RU                                      Какая страна имеет наибольшее среднее значение addiction_score?                       Tanzania                         Tanzania              0.424
3  Qwen3-8B      M4     medium       RU  Какой процент наблюдений имеет значение sleep_quality_index ниже общего среднего? Округли ответ ...                          49.99                            49.99              0.618
4  Qwen3-8B      M5     medium       RU  Какова разница между средним значением MHRI для уровня зависимости High и Low? Округли ответ до ...                           4.82                             6.82              0.507
5  Qwen3-8B      M6     medium       RU  Какие три страны имеют наибольшее среднее значение dopamine_dependency_score? Укажи только назва...  Tanzania, Argentina, Malaysia  [Tanzania, Argentina, Malaysia]              0.810

In [78]:
results_medium_ru_df["is_correct"] = results_medium_ru_df.apply(
    lambda row: compare_answers_flexible(row["model_answer"], row["correct_answer"]),
    axis=1
)

accuracy_medium_ru = results_medium_ru_df["is_correct"].mean()
print("Russian Medium Accuracy:", round(accuracy_medium_ru * 100, 2), "%")

Russian Medium Accuracy: 66.67 %

4 hard level questions

English prompt

In [5]:
# =========================
# HARD TASKS — QWEN — EN
# =========================

import numpy as np
from sklearn.linear_model import LinearRegression

In [6]:
# H1
sleep_mean = df["sleep_hours"].mean()

h1_base = df[
    (df["age"] < 25) &
    (df["sleep_hours"] < sleep_mean)
]

h1_answer = (
    h1_base.groupby("country")["addiction_score"]
    .mean()
    .idxmax()
)

# H2
dopamine_median = df["dopamine_dependency_score"].median()
mhri_median = df["MHRI"].median()

h2_base = df[
    (df["dopamine_dependency_score"] > dopamine_median) &
    (df["MHRI"] > mhri_median)
]

h2_answer = (
    h2_base.groupby("country")["addiction_score"]
    .mean()
    .idxmax()
)

# H3
risk_df = df.copy()
risk_df["combined_risk_score"] = (
    risk_df["addiction_score"]
    + risk_df["dopamine_dependency_score"]
    - risk_df["sleep_hours"]
)

h3_answer = (
    risk_df.groupby("country")["combined_risk_score"]
    .mean()
    .idxmax()
)

# H4
h4_base = df[df["sleep_hours"] < sleep_mean]

h4_answer_df = (
    h4_base.groupby(["country", "age"], as_index=False)["addiction_score"]
    .mean()
    .sort_values("addiction_score", ascending=False)
    .head(3)
)

h4_answer = [
    f"{row['country']}-{int(row['age'])}"
    for _, row in h4_answer_df.iterrows()
]

hard_correct_answers = {
    "H1": h1_answer,
    "H2": h2_answer,
    "H3": h3_answer,
    "H4": h4_answer
}

hard_correct_answers

{'H1': 'Morocco',
 'H2': 'Pakistan',
 'H3': 'Tanzania',
 'H4': ['Bulgaria-32', 'Vietnam-58', 'Paraguay-41']}

In [11]:
hard_tasks_en = [
    {
        "task_id": "H1",
        "difficulty": "hard",
        "language": "EN",
        "question": (
            "Among users younger than 25 years old and with sleep_hours below "
            "the overall dataset average, which country has the highest average "
            "addiction_score? Return only the country name."
        ),
        "data": (
            h1_base.groupby("country", as_index=False)["addiction_score"]
            .mean()
            .sort_values("addiction_score", ascending=False)
            .head(30)
        )
    },
    {
        "task_id": "H2",
        "difficulty": "hard",
        "language": "EN",
        "question": (
            "Among users whose dopamine_dependency_score and MHRI are both above "
            "their respective dataset medians, which country has the highest average "
            "addiction_score? Return only the country name."
        ),
        "data": (
            h2_base.groupby("country", as_index=False)["addiction_score"]
            .mean()
            .sort_values("addiction_score", ascending=False)
            .head(30)
        )
    },
    {
        "task_id": "H3",
        "difficulty": "hard",
        "language": "EN",
        "question": (
            "Using the combined digital risk score defined as addiction_score + "
            "dopamine_dependency_score - sleep_hours, which country has the highest "
            "average combined digital risk? Return only the country name."
        ),
        "data": (
            risk_df.groupby("country", as_index=False)["combined_risk_score"]
            .mean()
            .sort_values("combined_risk_score", ascending=False)
            .head(30)
        )
    },
    {
        "task_id": "H4",
        "difficulty": "hard",
        "language": "EN",
        "question": (
            "Rank the three most vulnerable user groups, defined as country-age "
            "combinations, according to average addiction_score, considering only "
            "groups with below-average sleep_hours. Return only the top three "
            "country-age groups."
        ),
        "data": (
            h4_base.groupby(["country", "age"], as_index=False)["addiction_score"]
            .mean()
            .sort_values("addiction_score", ascending=False)
            .head(20)
        )
    }
]

In [12]:
def generate_response(messages, max_new_tokens=100, enable_thinking=False):
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
        enable_thinking=enable_thinking
    )

    inputs = tokenizer(
        text,
        return_tensors="pt"
    ).to(model.device)

    start_time = time.time()

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            temperature=0.0,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id
        )

    end_time = time.time()

    response = tokenizer.decode(
        outputs[0][inputs["input_ids"].shape[-1]:],
        skip_special_tokens=True
    )

    response = response.strip()

    return response, round(end_time - start_time, 3)

In [13]:
results_hard_en = []

for task in hard_tasks_en:
    table_text = task["data"].to_string(index=False)

    messages = [
        {
            "role": "system",
            "content": (
                "You are a data analyst. "
                "Use only the provided table. "
                "Return only the final answer. "
                "Do not explain your reasoning."
            )
        },
        {
            "role": "user",
            "content": f"""
Here is the table:

{table_text}

Task:
{task["question"]}
"""
        }
    ]

    answer, response_time = generate_response(messages)

    results_hard_en.append({
        "model": "Qwen3-8B",
        "task_id": task["task_id"],
        "difficulty": task["difficulty"],
        "language": task["language"],
        "question": task["question"],
        "model_answer": answer,
        "correct_answer": hard_correct_answers[task["task_id"]],
        "response_time_sec": response_time
    })

results_hard_en_df = pd.DataFrame(results_hard_en)
results_hard_en_df

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

,model,task_id,difficulty,language,question,model_answer,correct_answer,response_time_sec
0,Qwen3-8B,H1,hard,EN,Among users younger than 25 years old and with...,Philippines,Morocco,0.316
1,Qwen3-8B,H2,hard,EN,Among users whose dopamine_dependency_score an...,Netherlands,Pakistan,0.316
2,Qwen3-8B,H3,hard,EN,Using the combined digital risk score defined ...,Tanzania,Tanzania,0.412
3,Qwen3-8B,H4,hard,EN,"Rank the three most vulnerable user groups, de...","Costa Rica-17, USA-14, UAE-35","[Bulgaria-32, Vietnam-58, Paraguay-41]",1.628

polish prompt

In [8]:
hard_tasks_pl = [
    {
        "task_id": "H1",
        "difficulty": "hard",
        "language": "PL",
        "question": (
            "Wśród użytkowników poniżej 25 roku życia oraz z wartością sleep_hours "
            "niższą niż średnia w całym zbiorze danych, który kraj ma najwyższą "
            "średnią wartość addiction_score? Zwróć tylko nazwę kraju."
        ),
        "data": (
            h1_base.groupby("country", as_index=False)["addiction_score"]
            .mean()
            .sort_values("addiction_score", ascending=False)
            .head(30)
        )
    },
    {
        "task_id": "H2",
        "difficulty": "hard",
        "language": "PL",
        "question": (
            "Wśród użytkowników, których dopamine_dependency_score oraz MHRI są wyższe "
            "od odpowiednich median w zbiorze danych, który kraj ma najwyższą średnią "
            "wartość addiction_score? Zwróć tylko nazwę kraju."
        ),
        "data": (
            h2_base.groupby("country", as_index=False)["addiction_score"]
            .mean()
            .sort_values("addiction_score", ascending=False)
            .head(30)
        )
    },
    {
        "task_id": "H3",
        "difficulty": "hard",
        "language": "PL",
        "question": (
            "Korzystając ze złożonego wskaźnika ryzyka cyfrowego zdefiniowanego jako "
            "addiction_score + dopamine_dependency_score - sleep_hours, który kraj ma "
            "najwyższą średnią wartość tego wskaźnika? Zwróć tylko nazwę kraju."
        ),
        "data": (
            risk_df.groupby("country", as_index=False)["combined_risk_score"]
            .mean()
            .sort_values("combined_risk_score", ascending=False)
            .head(30)
        )
    },
    {
        "task_id": "H4",
        "difficulty": "hard",
        "language": "EN",
        "question": (
            "Uszereguj trzy najbardziej narażone grupy użytkowników, zdefiniowane jako "
            "kombinacje country-age, według średniej wartości addiction_score, uwzględniając "
            "tylko grupy z sleep_hours poniżej średniej. Zwróć tylko trzy najlepsze grupy country-age."
        ),
        "data": (
            h4_base.groupby(["country", "age"], as_index=False)["addiction_score"]
            .mean()
            .sort_values("addiction_score", ascending=False)
            .head(20)
        )
    }
]

In [9]:
def generate_response(messages, max_new_tokens=100, enable_thinking=False):
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
        enable_thinking=enable_thinking
    )

    inputs = tokenizer(
        text,
        return_tensors="pt"
    ).to(model.device)

    start_time = time.time()

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            temperature=0.0,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id
        )

    end_time = time.time()

    response = tokenizer.decode(
        outputs[0][inputs["input_ids"].shape[-1]:],
        skip_special_tokens=True
    )

    response = response.strip()

    return response, round(end_time - start_time, 3)

In [10]:
results_hard_pl = []

for task in hard_tasks_pl:
    table_text = task["data"].to_string(index=False)

    messages = [
        {
            "role": "system",
            "content": (
                "Jesteś analitykiem danych. "
                "Korzystaj wyłącznie z podanej tabeli. "
                "Zwróć tylko końcową odpowiedź. "
                "Nie wyjaśniaj toku rozumowania."
            )
        },
        {
            "role": "user",
            "content": f"""
Oto tabela:

{table_text}

Zadanie:
{task["question"]}
"""
        }
    ]

    answer, response_time = generate_response(messages)

    results_hard_pl.append({
        "model": "Qwen3-8B",
        "task_id": task["task_id"],
        "difficulty": task["difficulty"],
        "language": task["language"],
        "question": task["question"],
        "model_answer": answer,
        "correct_answer": hard_correct_answers[task["task_id"]],
        "response_time_sec": response_time
    })

results_hard_pl_df = pd.DataFrame(results_hard_pl)
results_hard_pl_df

[transformers] The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

,model,task_id,difficulty,language,question,model_answer,correct_answer,response_time_sec
0,Qwen3-8B,H1,hard,PL,Wśród użytkowników poniżej 25 roku życia oraz ...,Morocco,Morocco,1.301
1,Qwen3-8B,H2,hard,PL,"Wśród użytkowników, których dopamine_dependenc...",Pakistan,Pakistan,0.229
2,Qwen3-8B,H3,hard,PL,Korzystając ze złożonego wskaźnika ryzyka cyfr...,Netherlands,Tanzania,0.324
3,Qwen3-8B,H4,hard,EN,Uszereguj trzy najbardziej narażone grupy użyt...,"Bulgaria-32, Vietnam-58, Paraguay-41","[Bulgaria-32, Vietnam-58, Paraguay-41]",1.721

russian prompt

In [14]:
hard_tasks_ru = [
    {
        "task_id": "H1",
        "difficulty": "hard",
        "language": "RU",
        "question": (
            "Среди пользователей младше 25 лет и с количеством sleep_hours ниже "
            "среднего значения по всему датасету, какая страна имеет самое высокое "
            "среднее значение addiction_score? Верни только название страны."
        ),
        "data": (
            h1_base.groupby("country", as_index=False)["addiction_score"]
            .mean()
            .sort_values("addiction_score", ascending=False)
            .head(30)
        )
    },
    {
        "task_id": "H2",
        "difficulty": "hard",
        "language": "RU",
        "question": (
            "Среди пользователей, у которых dopamine_dependency_score и MHRI выше "
            "соответствующих медианных значений по датасету, какая страна имеет самое "
            "высокое среднее значение addiction_score? Верни только название страны."

        ),
        "data": (
            h2_base.groupby("country", as_index=False)["addiction_score"]
            .mean()
            .sort_values("addiction_score", ascending=False)
            .head(30)
        )
    },
    {
        "task_id": "H3",
        "difficulty": "hard",
        "language": "RU",
        "question": (
            "Используя комбинированный цифровой риск, определённый как "
            "addiction_score + dopamine_dependency_score - sleep_hours, какая страна "
            "имеет самый высокий средний комбинированный цифровой риск? Верни только название страны."
        ),
        "data": (
            risk_df.groupby("country", as_index=False)["combined_risk_score"]
            .mean()
            .sort_values("combined_risk_score", ascending=False)
            .head(30)
        )
    },
    {
        "task_id": "H4",
        "difficulty": "hard",
        "language": "RU",
        "question": (
            "Ранжируй три наиболее уязвимые группы пользователей, определённые как "
            "комбинации country-age, по среднему значению addiction_score, учитывая "
            "только группы с sleep_hours ниже среднего значения. Верни только три лучшие группы country-age."
        ),
        "data": (
            h4_base.groupby(["country", "age"], as_index=False)["addiction_score"]
            .mean()
            .sort_values("addiction_score", ascending=False)
            .head(20)
        )
    }
]

In [15]:
def generate_response(messages, max_new_tokens=100, enable_thinking=False):
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
        enable_thinking=enable_thinking
    )

    inputs = tokenizer(
        text,
        return_tensors="pt"
    ).to(model.device)

    start_time = time.time()

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            temperature=0.0,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id
        )

    end_time = time.time()

    response = tokenizer.decode(
        outputs[0][inputs["input_ids"].shape[-1]:],
        skip_special_tokens=True
    )

    response = response.strip()

    return response, round(end_time - start_time, 3)

In [16]:
results_hard_ru = []

for task in hard_tasks_ru:
    table_text = task["data"].to_string(index=False)

    messages = [
        {
            "role": "system",
            "content": (
                "Ты аналитик данных. "
                "Используй только предоставленную таблицу. "
                "Верни только итоговый ответ. "
                "Не объясняй ход рассуждений."
            )
        },
        {
            "role": "user",
            "content": f"""
Вот таблица:

{table_text}

Задание:
{task["question"]}
"""
        }
    ]

    answer, response_time = generate_response(messages)

    results_hard_ru.append({
        "model": "Qwen3-8B",
        "task_id": task["task_id"],
        "difficulty": task["difficulty"],
        "language": task["language"],
        "question": task["question"],
        "model_answer": answer,
        "correct_answer": hard_correct_answers[task["task_id"]],
        "response_time_sec": response_time
    })

results_hard_ru_df = pd.DataFrame(results_hard_ru)
results_hard_ru_df

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

,model,task_id,difficulty,language,question,model_answer,correct_answer,response_time_sec
0,Qwen3-8B,H1,hard,RU,Среди пользователей младше 25 лет и с количест...,Philippines,Morocco,0.320
1,Qwen3-8B,H2,hard,RU,"Среди пользователей, у которых dopamine_depend...",Netherlands,Pakistan,0.321
2,Qwen3-8B,H3,hard,RU,"Используя комбинированный цифровой риск, опред...",Tanzania,Tanzania,0.414
3,Qwen3-8B,H4,hard,RU,Ранжируй три наиболее уязвимые группы пользова...,"USA-14, USA-38, Vietnam-58","[Bulgaria-32, Vietnam-58, Paraguay-41]",1.465

**Forecast tasks**

English prompt

In [17]:
# =========================
# FORECAST TASKS — QWEN — EN
# WITH PREDICTION + JUSTIFICATION
# =========================

import pandas as pd
import numpy as np
import re
from sklearn.linear_model import LinearRegression

In [18]:
# 1. Prepare yearly data

yearly_addiction = (
    df.groupby("year", as_index=False)["addiction_score"]
    .mean()
    .sort_values("year")
)

train_forecast = yearly_addiction[yearly_addiction["year"] <= 2040].copy()

X_train = train_forecast[["year"]]
y_train = train_forecast["addiction_score"]

forecast_model = LinearRegression()
forecast_model.fit(X_train, y_train)

# Correct answer for F1
f1_answer = round(
    float(forecast_model.predict(pd.DataFrame({"year": [2045]}))[0]),
    2
)

# Correct answer for F2
pred_2040 = round(
    float(forecast_model.predict(pd.DataFrame({"year": [2040]}))[0]),
    2
)

pred_2050 = round(
    float(forecast_model.predict(pd.DataFrame({"year": [2050]}))[0]),
    2
)

f2_answer = "Increase" if pred_2050 > pred_2040 else "Decrease"

forecast_correct_answers = {
    "F1": f1_answer,
    "F2": f2_answer
}

forecast_correct_answers

{'F1': 58.37, 'F2': 'Decrease'}

In [19]:
# 2. Forecast tasks in English

forecast_tasks_en = [
    {
        "task_id": "F1",
        "difficulty": "forecast",
        "language": "EN",
        "question": (
            "Using a simple linear trend based on the data from 2015 to 2040, "
            "predict the average addiction_score for year 2045. "
            "Return your answer in this exact format:\n"
            "Prediction: <number>\n"
            "Justification: <one short sentence>"
        ),
        "data": train_forecast
    },
    {
        "task_id": "F2",
        "difficulty": "forecast",
        "language": "EN",
        "question": (
            "Using a simple linear trend based on the data from 2015 to 2040, "
            "determine whether the average addiction_score in 2050 is expected "
            "to increase or decrease compared to 2040. "
            "Return your answer in this exact format:\n"
            "Prediction: <Increase or Decrease>\n"
            "Justification: <one short sentence>"
        ),
        "data": train_forecast
    }
]

In [20]:
def generate_response(messages, max_new_tokens=150, enable_thinking=False):
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
        enable_thinking=enable_thinking
    )

    inputs = tokenizer(
        text,
        return_tensors="pt"
    ).to(model.device)

    start_time = time.time()

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            temperature=0.0,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id
        )

    end_time = time.time()

    response = tokenizer.decode(
        outputs[0][inputs["input_ids"].shape[-1]:],
        skip_special_tokens=True
    )

    response = response.strip()

    return response, round(end_time - start_time, 3)

In [21]:
# 3. Run forecast tasks

results_forecast_en = []

for task in forecast_tasks_en:
    table_text = task["data"].to_string(index=False)

    messages = [
        {
            "role": "system",
            "content": (
                "You are a data analyst. "
                "Use only the provided table. "
                "Use a simple linear trend when forecasting. "
                "Return the answer exactly in the requested format. "
                "Do not add anything else."
            )
        },
        {
            "role": "user",
            "content": f"""
Here is the table:

{table_text}

Task:
{task["question"]}
"""
        }
    ]

    answer, response_time = generate_response(
        messages,
        max_new_tokens=120,
        enable_thinking=False
    )

    results_forecast_en.append({
        "model": "Qwen3-8B",
        "task_id": task["task_id"],
        "difficulty": task["difficulty"],
        "language": task["language"],
        "question": task["question"],
        "model_answer": answer,
        "correct_answer": forecast_correct_answers[task["task_id"]],
        "response_time_sec": response_time
    })

results_forecast_en_df = pd.DataFrame(results_forecast_en)
results_forecast_en_df

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

,model,task_id,difficulty,language,question,model_answer,correct_answer,response_time_sec
0,Qwen3-8B,F1,forecast,EN,Using a simple linear trend based on the data ...,Prediction: 57.34\nJustification: The linear t...,58.37,4.127
1,Qwen3-8B,F2,forecast,EN,Using a simple linear trend based on the data ...,Prediction: Decrease\nJustification: The linea...,Decrease,2.076

polish prompt

In [22]:
forecast_tasks_pl = [
    {
        "task_id": "F1",
        "difficulty": "forecast",
        "language": "PL",
        "question": (
            "Na podstawie prostego trendu liniowego wyznaczonego z danych "
            "z lat 2015–2040 przewidź średnią wartość addiction_score dla roku 2045. "
            "Zwróć odpowiedź dokładnie w następującym formacie:\n"
            "Prediction: <liczba>\n"
            "Justification: <jedno krótkie zdanie>"
        ),
        "data": train_forecast
    },
    {
        "task_id": "F2",
        "difficulty": "forecast",
        "language": "PL",
        "question": (
            "Na podstawie prostego trendu liniowego wyznaczonego z danych "
            "z lat 2015–2040 określ, czy średnia wartość addiction_score "
            "w roku 2050 będzie wyższa czy niższa niż w roku 2040. "
            "Zwróć odpowiedź dokładnie w następującym formacie:\n"
            "Prediction: <Increase lub Decrease>\n"
            "Justification: <jedno krótkie zdanie>"
        ),
        "data": train_forecast
    }
]

In [23]:
def generate_response(messages, max_new_tokens=150, enable_thinking=False):
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
        enable_thinking=enable_thinking
    )

    inputs = tokenizer(
        text,
        return_tensors="pt"
    ).to(model.device)

    start_time = time.time()

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            temperature=0.0,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id
        )

    end_time = time.time()

    response = tokenizer.decode(
        outputs[0][inputs["input_ids"].shape[-1]:],
        skip_special_tokens=True
    )

    response = response.strip()

    return response, round(end_time - start_time, 3)

In [24]:
results_forecast_pl = []

for task in forecast_tasks_pl:

    table_text = task["data"].to_string(index=False)

    messages = [
        {
            "role": "system",
            "content": (
                "Jesteś analitykiem danych. "
                "Korzystaj wyłącznie z podanej tabeli. "
                "Do prognozowania użyj prostego trendu liniowego. "
                "Zwróć odpowiedź dokładnie w wymaganym formacie. "
                "Nie dodawaj nic więcej."
            )
        },
        {
            "role": "user",
            "content": f"""
Oto tabela:

{table_text}

Zadanie:
{task["question"]}
"""
        }
    ]

    answer, response_time = generate_response(
        messages,
        max_new_tokens=120,
        enable_thinking=False
    )

    results_forecast_pl.append({
        "model": "Qwen3-8B",
        "task_id": task["task_id"],
        "difficulty": task["difficulty"],
        "language": task["language"],
        "question": task["question"],
        "model_answer": answer,
        "correct_answer": forecast_correct_answers[task["task_id"]],
        "response_time_sec": response_time
    })

results_forecast_pl_df = pd.DataFrame(results_forecast_pl)
results_forecast_pl_df

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

,model,task_id,difficulty,language,question,model_answer,correct_answer,response_time_sec
0,Qwen3-8B,F1,forecast,PL,Na podstawie prostego trendu liniowego wyznacz...,Prediction: 57.54 \nJustification: Trend lini...,58.37,3.894
1,Qwen3-8B,F2,forecast,PL,Na podstawie prostego trendu liniowego wyznacz...,Prediction: Decrease \nJustification: Trend l...,Decrease,3.434

russian prompt

In [25]:
forecast_tasks_ru = [
    {
        "task_id": "F1",
        "difficulty": "forecast",
        "language": "RU",
        "question": (
            "Используя простой линейный тренд на основе данных за период "
            "2015–2040 годов, спрогнозируй среднее значение addiction_score "
            "для 2045 года. "
            "Верни ответ строго в следующем формате:\n"
            "Prediction: <число>\n"
            "Justification: <одно короткое предложение>"
        ),
        "data": train_forecast
    },
    {
        "task_id": "F2",
        "difficulty": "forecast",
        "language": "RU",
        "question": (
            "Используя простой линейный тренд на основе данных за период "
            "2015–2040 годов, определи, будет ли среднее значение "
            "addiction_score в 2050 году выше или ниже, чем в 2040 году. "
            "Верни ответ строго в следующем формате:\n"
            "Prediction: <Increase или Decrease>\n"
            "Justification: <одно короткое предложение>"
        ),
        "data": train_forecast
    }
]

In [26]:
def generate_response(messages, max_new_tokens=150, enable_thinking=False):
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
        enable_thinking=enable_thinking
    )

    inputs = tokenizer(
        text,
        return_tensors="pt"
    ).to(model.device)

    start_time = time.time()

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            temperature=0.0,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id
        )

    end_time = time.time()

    response = tokenizer.decode(
        outputs[0][inputs["input_ids"].shape[-1]:],
        skip_special_tokens=True
    )

    response = response.strip()

    return response, round(end_time - start_time, 3)

In [27]:
results_forecast_ru = []

for task in forecast_tasks_ru:

    table_text = task["data"].to_string(index=False)

    messages = [
        {
            "role": "system",
            "content": (
                "Ты аналитик данных. "
                "Используй только предоставленную таблицу. "
                "Для прогнозирования используй простой линейный тренд. "
                "Верни ответ строго в требуемом формате. "
                "Не добавляй ничего лишнего."
            )
        },
        {
            "role": "user",
            "content": f"""
Вот таблица:

{table_text}

Задание:
{task["question"]}
"""
        }
    ]

    answer, response_time = generate_response(
        messages,
        max_new_tokens=120,
        enable_thinking=False
    )

    results_forecast_ru.append({
        "model": "Qwen3-8B",
        "task_id": task["task_id"],
        "difficulty": task["difficulty"],
        "language": task["language"],
        "question": task["question"],
        "model_answer": answer,
        "correct_answer": forecast_correct_answers[task["task_id"]],
        "response_time_sec": response_time
    })

results_forecast_ru_df = pd.DataFrame(results_forecast_ru)
results_forecast_ru_df

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

,model,task_id,difficulty,language,question,model_answer,correct_answer,response_time_sec
0,Qwen3-8B,F1,forecast,RU,Используя простой линейный тренд на основе дан...,Prediction: 57.54 \nJustification: Линейный т...,58.37,4.545
1,Qwen3-8B,F2,forecast,RU,Используя простой линейный тренд на основе дан...,Prediction: Decrease \nJustification: Линейны...,Decrease,2.524