In [3]:
!pip install -U transformers

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.10.1)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.16.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (8.4.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.15)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)

In [4]:
from huggingface_hub import login
login("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")  # get from huggingface.co/settings/tokens

In [5]:
!pip install -q -U transformers accelerate bitsandbytes

from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
import torch

model_id = "Vikhrmodels/Vikhr-Nemo-12B-Instruct-R-21-09-24"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True
)

print(f"Ładuję model: {model_id}...")
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map="auto",
    low_cpu_mem_usage=True
)
print("Model gotowy do pracy!")

Ładuję model: Vikhrmodels/Vikhr-Nemo-12B-Instruct-R-21-09-24...

[transformers] The tokenizer you are loading from 'Vikhrmodels/Vikhr-Nemo-12B-Instruct-R-21-09-24' with an incorrect regex pattern: https://huggingface.co/mistralai/Mistral-Small-3.1-24B-Instruct-2503/discussions/84#69121093e8b480e709447d5e. This will lead to incorrect tokenization. You should set the `fix_mistral_regex=True` flag when loading this tokenizer to fix this issue.

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 5 files:   0%|          | 0/5 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/363 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

generation_config.json:   0%|          | 0.00/111 [00:00<?, ?B/s]

Model gotowy do pracy!

# Analiza tekstu litareckiego (streszczenie)

In [ ]:
!pip install -q pymupdf

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.1/24.1 MB 111.5 MB/s eta 0:00:00

In [ ]:
import fitz  # PyMuPDF
import torch
import json
from transformers import AutoModelForCausalLM, AutoTokenizer

In [ ]:
# 1. Konfiguracja modelu Vikhr-Nemo
model_name = "Vikhrmodels/Vikhr-Nemo-12B-Instruct-R-21-09-24"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto",
    torch_dtype=torch.bfloat16,
    load_in_4bit=True  # Oszczędność pamięci VRAM
)

The tokenizer you are loading from 'Vikhrmodels/Vikhr-Nemo-12B-Instruct-R-21-09-24' with an incorrect regex pattern: https://huggingface.co/mistralai/Mistral-Small-3.1-24B-Instruct-2503/discussions/84#69121093e8b480e709447d5e. This will lead to incorrect tokenization. You should set the `fix_mistral_regex=True` flag when loading this tokenizer to fix this issue.
`torch_dtype` is deprecated! Use `dtype` instead!

TypeError: MistralForCausalLM.__init__() got an unexpected keyword argument 'load_in_4bit'

In [ ]:
# 2. Funkcja przygotowująca dokumenty w Twoim formacie JSON
def prepare_rag_documents(file_path, pages_to_extract):
    """
    Pobiera wybrane strony i tworzy listę słowników JSON.
    pages_to_extract: lista numerów stron (np. [5, 6])
    """
    documents = []
    doc_pdf = fitz.open(file_path)

    for i, pg_num in enumerate(pages_to_extract):
        # Sprawdzenie czy strona istnieje w PDF
        if pg_num <= len(doc_pdf):
            page = doc_pdf[pg_num - 1]
            text = page.get_text().strip()

            # Tworzenie struktury zgodnej z Twoim wymaganiem
            doc_entry = {
                "doc_id": i,
                "title": f"Dostojewski - Strona {pg_num}",
                "content": text[:4000] # Ograniczenie do 4k znaków zgodnie z wymogiem
            }
            documents.append(doc_entry)

    doc_pdf.close()
    # Konwersja do JSON z zachowaniem znaków narodowych
    return json.dumps(documents, ensure_ascii=False)

In [ ]:
# 3. Parametry wejściowe
pdf_file = "/content/priestuplieniie_i_nakazaniie_-_fiedor_mikhailovich_dostoievskii.pdf"
wybrane_strony = [12, 13]

# Przygotowanie kontekstu RAG
rag_context_json = prepare_rag_documents(pdf_file, wybrane_strony)

In [ ]:
# 4. Przygotowanie promptu Instruct
messages = [
    {
        "role": "system",
        "content": (
            "Вы — эксперт по творчеству Достоевского. Используйте предоставленные ниже документы в формате JSON "
            "в качестве контекста для создания подробного резюме. Ответ напишите на русском языке."
        )
    },
    {
        "role": "user",
        "content": f"Вот документы с текстом:\n{rag_context_json}\n\nProszę, napisz szczegółowe streszczenie tych dwóch stron po polsku."
    }
]

# Zastosowanie szablonu chatu
input_ids = tokenizer.apply_chat_template(
    messages,
    return_tensors="pt",
    add_generation_prompt=True
).to("cuda")

In [ ]:
# 5. Generowanie streszczenia
print(f"Vikhr-Nemo analizuje strony {wybrane_strony}... Proszę czekać.\n")

# Extract the input_ids tensor and attention_mask tensor from the BatchEncoding object
input_ids_tensor = input_ids['input_ids']
attention_mask_tensor = input_ids['attention_mask']

outputs = model.generate(
    input_ids_tensor, # Use the extracted input_ids tensor
    attention_mask=attention_mask_tensor, # Pass the attention_mask tensor for better generation
    max_new_tokens=1000,
    do_sample=True,
    temperature=0.3,
    top_p=0.9,
    repetition_penalty=1.1
)

# Dekodowanie i wyświetlenie wyniku
# Use input_ids_tensor.shape[-1] as input_ids_tensor is now the actual tensor
summary = tokenizer.decode(outputs[0][input_ids_tensor.shape[-1]:], skip_special_tokens=True)

print("--- STRESZCZENIE RAG ---")
print(summary)

Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.

Vikhr-Nemo analizuje strony [12, 13]... Proszę czekać.

--- STRESZCZENIE RAG ---
Данные документы представляют собой отрывки из произведений Фёдора Михайловича Достоевского, написанные на немецком языке. Однако, поскольку вы запросили ответ на русском языке, я предоставлю резюме на этом языке.

### Резюме страницы 12:

Текст описывает диалог между Мармеладовым и молодым человеком в трактире. Мармеладов рассказывает о своем унизительном положении, несмотря на то, что его жена, Катерина Ивановна, является образованной женщиной из дворянской семьи. Он признаёт своё алкогольное пристрастие и говорит о том, как Катерина Ивановна, несмотря на своё высокомерие и гордость, терпит его и заботится о детях, работая с утра до ночи. Мармеладов также упоминает, что даже чулки своей жены пропивал, несмотря на её болезненное состояние и необходимость в тепле.

### Резюме страницы 13:

Этот текст продолжает историю Мармеладова. Он делится своими переживаниями относительно своего пьянства, утверждая, что пьёт, чтобы страдать. Мармеладов рассказывает о прошлом Катерины Ивановны, её образовании и золотой медали, которую она получила. Он также упоминает о её первом браке с офицером, который умер, оставив её одну с тремя детьми. Мармеладов предлагает ей руку, и она соглашается, будучи в отчаянии и без средств. Они переживают множество трудностей, включая потерю работы и вынужденное проживание в углу у хозяйки. Мармеладов завершает свой рассказ описанием их текущего положения в столице, где они живут среди множества людей в условиях содомии и безобразия.

Эти отрывки демонстрируют типичные для Достоевского темы: борьбу с пороком, социальное неравенство и внутренние конфликты персонажей.

--- STRESZCZENIE RAG ---

Данные документы представляют собой отрывки из произведений Фёдора Михайловича Достоевского, написанные на немецком языке. Однако, поскольку вы запросили ответ на русском языке, я предоставлю резюме на этом языке.

### Резюме страницы 12:

Текст описывает диалог между Мармеладовым и молодым человеком в трактире. Мармеладов рассказывает о своем унизительном положении, несмотря на то, что его жена, Катерина Ивановна, является образованной женщиной из дворянской семьи. Он признаёт своё алкогольное пристрастие и говорит о том, как Катерина Ивановна, несмотря на своё высокомерие и гордость, терпит его и заботится о детях, работая с утра до ночи. Мармеладов также упоминает, что даже чулки своей жены пропивал, несмотря на её болезненное состояние и необходимость в тепле.

### Резюме страницы 13:

Этот текст продолжает историю Мармеладова. Он делится своими переживаниями относительно своего пьянства, утверждая, что пьёт, чтобы страдать. Мармеладов рассказывает о прошлом Катерины Ивановны, её образовании и золотой медали, которую она получила. Он также упоминает о её первом браке с офицером, который умер, оставив её одну с тремя детьми. Мармеладов предлагает ей руку, и она соглашается, будучи в отчаянии и без средств. Они переживают множество трудностей, включая потерю работы и вынужденное проживание в углу у хозяйки. Мармеладов завершает свой рассказ описанием их текущего положения в столице, где они живут среди множества людей в условиях содомии и безобразия.

Эти отрывки демонстрируют типичные для Достоевского темы: борьбу с пороком, социальное неравенство и внутренние конфликты персонажей.

In [ ]:
# 2. Function to prepare documents in JSON format (RAG structure)
def prepare_rag_documents(file_path, pages_to_extract):
    """
    Extracts text from specific pages and returns a JSON string.
    """
    documents = []
    doc_pdf = fitz.open(file_path)

    for i, pg_num in enumerate(pages_to_extract):
        if pg_num <= len(doc_pdf):
            page = doc_pdf[pg_num - 1]
            text = page.get_text().strip()

            # Creating structure as per your requirements
            doc_entry = {
                "doc_id": i,
                "title": f"The Hobbit - Page {pg_num}",
                "content": text[:4000] # Chunk limit
            }
            documents.append(doc_entry)

    doc_pdf.close()
    return json.dumps(documents, ensure_ascii=False)

In [ ]:
# 3. Execution Parameters
pdf_file = "/content/the-hobbit-1.pdf"
selected_pages = [67, 68]

# Prepare RAG Context
rag_context_json = prepare_rag_documents(pdf_file, selected_pages)

In [ ]:
# 4. Prepare English Prompt (ChatML)
messages = [
    {
        "role": "system",
        "content": (
            "You are a professional literary assistant. Your task is to provide high-quality "
            "summaries based on the provided JSON documents. Focus on accuracy and key plot points."
        )
    },
    {
        "role": "user",
        "content": f"Reference Documents (JSON):\n{rag_context_json}\n\nPlease read these pages from 'The Hobbit' and write a concise, professional summary in English."
    }
]

# Apply chat template
input_ids = tokenizer.apply_chat_template(
    messages,
    return_tensors="pt",
    add_generation_prompt=True
).to("cuda")

In [ ]:
# 5. Generowanie streszczenia
print(f"Vikhr-Nemo analizuje strony {selected_pages}... Proszę czekać.\n")

# Extract the input_ids tensor and attention_mask tensor from the BatchEncoding object
input_ids_tensor = input_ids['input_ids']
attention_mask_tensor = input_ids['attention_mask']

outputs = model.generate(
    input_ids_tensor, # Use the extracted input_ids tensor
    attention_mask=attention_mask_tensor, # Pass the attention_mask tensor for better generation
    max_new_tokens=1000,
    do_sample=True,
    temperature=0.3,
    top_p=0.9,
    repetition_penalty=1.1
)

# Dekodowanie i wyświetlenie wyniku
# Use input_ids_tensor.shape[-1] as input_ids_tensor is now the actual tensor
summary = tokenizer.decode(outputs[0][input_ids_tensor.shape[-1]:], skip_special_tokens=True)

print("--- STRESZCZENIE RAG ---")
print(summary)

Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.

Vikhr-Nemo analizuje strony [67, 68]... Proszę czekać.

--- STRESZCZENIE RAG ---
### Summary of Pages 67-68 from "The Hobbit"

In Chapter V titled "Riddles in the Dark," Bilbo Baggins awakens in total darkness following his fall in the goblin tunnels. Disoriented and alone, Bilbo struggles to find any signs of life or direction. After groping around, he discovers a small metal ring on the tunnel floor, which he pockets without much thought.

Feeling lost and miserable, Bilbo sits down, contemplating his situation and wishing for a meal. He reflects on his confusion regarding how he was left behind by both the goblins and the dwarves, and why his head aches so severely.

Later, Bilbo searches for his pipe and tobacco, finding some solace in their intact condition despite lacking matches. This disappointment is soon alleviated when he finds his elvish dagger, which he had forgotten and which the goblins had overlooked. The weapon's presence offers him comfort, knowing its reputation among goblins.

With renewed determination, Bilbo decides to press forward, grasping his sword and using the wall to guide him through the darkness. Despite the perilous circumstances, Bilbo's hobbit nature provides him with advantages in navigating subterranean environments, giving him a better chance of survival in this "tight place."

### Summary of Pages 67-68 from "The Hobbit"

In Chapter V titled "Riddles in the Dark," Bilbo Baggins awakens in total darkness following his fall in the goblin tunnels. Disoriented and alone, Bilbo struggles to find any signs of life or direction. After groping around, he discovers a small metal ring on the tunnel floor, which he pockets without much thought.

Feeling lost and miserable, Bilbo sits down, contemplating his situation and wishing for a meal. He reflects on his confusion regarding how he was left behind by both the goblins and the dwarves, and why his head aches so severely.

Later, Bilbo searches for his pipe and tobacco, finding some solace in their intact condition despite lacking matches. This disappointment is soon alleviated when he finds his elvish dagger, which he had forgotten and which the goblins had overlooked. The weapon's presence offers him comfort, knowing its reputation among goblins.

With renewed determination, Bilbo decides to press forward, grasping his sword and using the wall to guide him through the darkness. Despite the perilous circumstances, Bilbo's hobbit nature provides him with advantages in navigating subterranean environments, giving him a better chance of survival in this "tight place."

In [ ]:
def prepare_rag_documents(file_path, pages_to_extract):
    """
    Ekstrahuje tekst z wybranych stron i tworzy listę dokumentów JSON.
    """
    documents = []
    doc_pdf = fitz.open(file_path)

    for i, pg_num in enumerate(pages_to_extract):
        if pg_num <= len(doc_pdf):
            page = doc_pdf[pg_num - 1]
            text = page.get_text().strip()

            # Budowanie słownika zgodnie ze specyfikacją
            doc_entry = {
                "doc_id": i,
                "title": f"Janko Muzykant - Strona {pg_num}",
                "content": text[:4000] # Limit 4k znaków na chunk
            }
            documents.append(doc_entry)

    doc_pdf.close()
    return json.dumps(documents, ensure_ascii=False)

In [ ]:
# 3. Parametry wejściowe
pdf_file = "/content/janko-muzykant.pdf"
strony_do_analizy = [2, 3]

# Generowanie kontekstu JSON
rag_context_json = prepare_rag_documents(pdf_file, strony_do_analizy)

In [ ]:
# 4. Prompt w języku polskim (ChatML)
messages = [
    {
        "role": "system",
        "content": (
            "Jesteś ekspertem od literatury polskiej i nowelistyki Henryka Sienkiewicza. "
            "Twoim zadaniem jest stworzenie rzetelnego i emocjonalnego streszczenia na podstawie "
            "dostarczonych dokumentów w formacie JSON."
        )
    },
    {
        "role": "user",
        "content": f"Oto treść dokumentów źródłowych:\n{rag_context_json}\n\nNa podstawie powyższych stron noweli 'Janko Muzykant', przygotuj szczegółowe streszczenie po polsku, zwracając uwagę na losy głównego bohatera."
    }
]

# Konwersja na format akceptowany przez model
input_ids = tokenizer.apply_chat_template(
    messages,
    return_tensors="pt",
    add_generation_prompt=True
).to("cuda")

In [ ]:
# 5. Generowanie streszczenia
print(f"Vikhr-Nemo analizuje strony {strony_do_analizy}... Proszę czekać.\n")

# Extract the input_ids tensor and attention_mask tensor from the BatchEncoding object
input_ids_tensor = input_ids['input_ids']
attention_mask_tensor = input_ids['attention_mask']

outputs = model.generate(
    input_ids_tensor, # Use the extracted input_ids tensor
    attention_mask=attention_mask_tensor, # Pass the attention_mask tensor for better generation
    max_new_tokens=1000,
    do_sample=True,
    temperature=0.3,
    top_p=0.9,
    repetition_penalty=1.1
)

# Dekodowanie i wyświetlenie wyniku
# Use input_ids_tensor.shape[-1] as input_ids_tensor is now the actual tensor
summary = tokenizer.decode(outputs[0][input_ids_tensor.shape[-1]:], skip_special_tokens=True)

print("--- STRESZCZENIE RAG ---")
print(summary)

Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.

Vikhr-Nemo analizuje strony [2, 3]... Proszę czekać.

--- STRESZCZENIE RAG ---
### Streszczenie noweli "Janko Muzykant"

Nowela "Janko Muzykant" opisuje losy chłopaka o imieniu Janko, który przyszedł na świat w trudnych okolicznościach. Po jego narodzinach, matka, chcąc ochronić syna przed złymi duchami, "ochrzca" go, nadając mu imię Jan. Janko jest słaby i chudy, ale posiada silną wolę do życia, pomimo że dusza jego "chrześcijańska" nie chce opuszczać ciała.

Wychowywany w biedzie, Janko nigdy nie poznał miłości matecznej, gdyż ta go często bijała i nazywała "odmieńcem". Od najmłodszych lat Janko jest przyciągany do muzyki – słucha i obserwuje, jak cały świat go otaczający "gra". Gdy jest mały, słyszy muzykę w dźwiękach natury i w hałasie wsi. Nie może spać, gdy nocą worlda się dźwięki, i marzy o własnych skrzypcach.

Janko jest niezdolny do pracy, ale gdy do niej wysyłają, nawet wiatr gra w jego widłach. Pracodawca, zauważając jego oddanie do muzyki, nazywa go "muzykantem". Wiosną Janko ucieka z domu, by słuchać strumieni, a nocami słuchać świata. Nie może iść do kościoła, gdyż muzyka tam zaczyna go zachwycać. Pod karczmą słucha tanczącej muzyki, a jego marzenia o własnych skrzypcach stają się coraz silniejsze.

Janko tworzy skrzypce z gontu i włosienia, ale one brzmią chaotycznie. On gra na nich od rannego ranka do późnego wieczoru, ale jest głodny i ubogi. Marzy o prawdziwych skrzypcach, które widzi w pańskiej rezydencji, a jego serce bije w nadziei, że kiedyś je zdobędzie.

W końcu, jego marzenia nie spełniają się. Nowela kończy się, gdy Janko, pełen pragnienia posiadania skrzypiec, ogląda je w domostwie pana, który jest poza krajem. Janko siedzi w łopuchach przed otwartymi drzwiami kredensa, gdzie wiszą skrzypce, i marzy o tym, jakby je miał w ręku. To jest moment, w którym Janko, pełen pasji, zaczyna rozumieć, że jego marzenia mogą być nieosiągalne.

### Streszczenie noweli "Janko Muzykant"

Nowela "Janko Muzykant" opisuje losy chłopaka o imieniu Janko, który przyszedł na świat w trudnych okolicznościach. Po jego narodzinach, matka, chcąc ochronić syna przed złymi duchami, "ochrzca" go, nadając mu imię Jan. Janko jest słaby i chudy, ale posiada silną wolę do życia, pomimo że dusza jego "chrześcijańska" nie chce opuszczać ciała.

Wychowywany w biedzie, Janko nigdy nie poznał miłości matecznej, gdyż ta go często bijała i nazywała "odmieńcem". Od najmłodszych lat Janko jest przyciągany do muzyki – słucha i obserwuje, jak cały świat go otaczający "gra". Gdy jest mały, słyszy muzykę w dźwiękach natury i w hałasie wsi. Nie może spać, gdy nocą worlda się dźwięki, i marzy o własnych skrzypcach.

Janko jest niezdolny do pracy, ale gdy do niej wysyłają, nawet wiatr gra w jego widłach. Pracodawca, zauważając jego oddanie do muzyki, nazywa go "muzykantem". Wiosną Janko ucieka z domu, by słuchać strumieni, a nocami słuchać świata. Nie może iść do kościoła, gdyż muzyka tam zaczyna go zachwycać. Pod karczmą słucha tanczącej muzyki, a jego marzenia o własnych skrzypcach stają się coraz silniejsze.

Janko tworzy skrzypce z gontu i włosienia, ale one brzmią chaotycznie. On gra na nich od rannego ranka do późnego wieczoru, ale jest głodny i ubogi. Marzy o prawdziwych skrzypcach, które widzi w pańskiej rezydencji, a jego serce bije w nadziei, że kiedyś je zdobędzie.

W końcu, jego marzenia nie spełniają się. Nowela kończy się, gdy Janko, pełen pragnienia posiadania skrzypiec, ogląda je w domostwie pana, który jest poza krajem. Janko siedzi w łopuchach przed otwartymi drzwiami kredensa, gdzie wiszą skrzypce, i marzy o tym, jakby je miał w ręku. To jest moment, w którym Janko, pełen pasji, zaczyna rozumieć, że jego marzenia mogą być nieosiągalne.

# Analiza tekstu technicznego

Analiza tekstu technicznego polegała na sprawdzeniu jak dobrze model rozumie restrykcje zawarte w tekstu i skomplikowane definicje

In [ ]:
# 2. Funkcja przygotowująca dokumenty JSON (Standard RAG)
def prepare_rag_documents(file_path, pages_to_extract):
    documents = []
    doc_pdf = fitz.open(file_path)

    for i, pg_num in enumerate(pages_to_extract):
        if pg_num <= len(doc_pdf):
            page = doc_pdf[pg_num - 1]
            text = page.get_text().strip()

            # Tworzenie słownika zgodnie ze specyfikacją RAG
            doc_entry = {
                "doc_id": i,
                "title": f"Hager - Instrukcja Techniczna - Strona {pg_num}",
                "content": text[:4000]
            }
            documents.append(doc_entry)

    doc_pdf.close()
    return json.dumps(documents, ensure_ascii=False)

In [ ]:
# 3. Ścieżka do pliku
pdf_file = "/content/19PL004_HAAG_BR_Handbuch_Schutz_vers_PL_2019.pdf"

In [ ]:
# --- ZADANIE 2: Zasady bezpieczeństwa ---
strony_safety = [23]
context_safety = prepare_rag_documents(pdf_file, strony_safety)

messages_safety = [
    {
        "role": "system",
        "content": "Jesteś ekspertem technika-elektryka. Odpowiadaj wyłącznie na podstawie dostarczonych danych JSON w języku polskim."
    },
    {
        "role": "user",
        "content": f"Oto dokumentacja Hager w formacie JSON:\n{context_safety}\n\nZadanie: Wypunktuj 5 najważniejszych zasad bezpieczeństwa opisanych w tym fragmencie. Skup się na tym, czego kategorycznie zabrania instrukcja."
    }
]

# --- ZADANIE 3: Terminologia ---
strony_defs = [4]
context_defs = prepare_rag_documents(pdf_file, strony_defs)

messages_defs = [
    {
        "role": "system",
        "content": "Jesteś ekspertem technika-elektryka. Odpowiadaj wyłącznie na podstawie dostarczonych danych JSON w języku polskim."
    },
    {
        "role": "user",
        "content": f"Oto dokumentacja Hager w formacie JSON:\n{context_defs}\n\nZadanie: Zidentyfikuj 3 skróty techniczne w tekście (np. RCD, RCCB, RCBO) i wyjaśnij ich znaczenie na podstawie dokumentu."
    }
]

In [ ]:
# 4. Funkcja do generowania odpowiedzi
def generate_response(messages):
    encoded_input = tokenizer.apply_chat_template(
        messages,
        return_tensors="pt",
        add_generation_prompt=True
    )
    input_ids = encoded_input['input_ids'].to("cuda")

    outputs = model.generate(
        input_ids,
        max_new_tokens=1000,
        do_sample=True,
        temperature=0.3,
        top_p=0.9,
        repetition_penalty=1.1
    )
    return tokenizer.decode(outputs[0][input_ids.shape[-1]:], skip_special_tokens=True)

In [ ]:
# 5. Uruchomienie zadań
print("--- VIKHR-NEMO: WYNIK ZADANIA 2 (BEZPIECZEŃSTWO) ---")
print(generate_response(messages_safety))

print("\n" + "="*50 + "\n")

print("--- VIKHR-NEMO: WYNIK ZADANIA 3 (TERMINOLOGIA) ---")
print(generate_response(messages_defs))

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.

--- VIKHR-NEMO: WYNIK ZADANIA 2 (BEZPIECZEŃSTWO) ---

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.

Na podstawie dostarczonych danych JSON, poniżej wymieniam 5 najważniejszych zasad bezpieczeństwa opisanych w instrukcji technicznej firmy Hager:

1. **Ograniczenia prądowe**: W wielu miejscach, takich jak pomieszczenia z wanną lub prysznicem, sauny z piecami elektrycznymi, ograniczone przestrzenie przewodzące oraz pomieszczenia medyczne, dopuszczalne jest tylko 30 mA prądu. To oznacza, że obwody elektryczne muszą być zaprojektowane tak, aby maksymalny prąd uderzeniowy był niższy niż 30 mA.

2. **Zasady dla miejsc o wysokim ryzyku**: W przypadku miejsc budowy, ograniczonych przestrzeni przewodzących oraz miejsc o zagrożeniu wybuchowym, stosowanie ręcznych urządzeń elektrycznych ≤ 32 A jest zabronione, co sugeruje, że należy używać urządzeń z odpowiednią klasą ochrony lub stosować inne środki bezpieczeństwa.

3. **Użycie SELV**: W przypadku bazenów i innych zbiorników, źródła prądu muszą być typu SELV (Safe Extra Low Voltage), co wskazuje na konieczność stosowania niskiego napięcia, aby zwiększyć poziom bezpieczeństwa.

4. **Oddzielne gniazda elektryczne**: W portach jachtowych, przyczepach kempingowych i domach przewoznych, wszystkie gniazda elektryczne oraz stałe połączenia zasilające pojazd muszą być oddzielne, co jest wymagane dla zapewnienia izolicacji i minimalizacji ryzyka elektrycznego.

5. **Ograniczenia dla instalacji oświetlenia**: W systemach oświetlenia zewnętrznych, takich jak budki telefoniczne, przystanki autobusowe, itp., końcowe obwody elektryczne ≤ 32 A mogą być stosowane, z wyłączeniem oświetlenia awaryjnego, co może wskazywać na konieczność specjalnych rozwiązań dla sytuacji awaryjnych.

Te zasady są kluczowe dla projektowania i utrzymywania bezpiecznej instalacji elektrycznej w różnych miejscach i warunkach.

==================================================

--- VIKHR-NEMO: WYNIK ZADANIA 3 (TERMINOLOGIA) ---
W podanym dokumencie nie ma żadnych skrótów technicznych. Tekst zawiera tylko słowo "wyłączniki" oraz "różnicoprzewodowe". Jeśli chciałbyś więcej informacji o wyłącznikach różnicoprzewodowych lub innych skrótach technicznych związanych z elektryką, musiałbymić mi dostęp do odpowiednich dokumentów, które zawierają te skróty. Wyłączniki różnicoprzewodowe to urządzenia ochrony, które odczynają obciążenie w przypadku wykrycia prądu różnicowego, co może wskazywać na usterkę w instalacji elektrycznej.

Na podstawie dostarczonych danych JSON, poniżej wymieniam 5 najważniejszych zasad bezpieczeństwa opisanych w instrukcji technicznej firmy Hager:

1. **Ograniczenia prądowe**: W wielu miejscach, takich jak pomieszczenia z wanną lub prysznicem, sauny z piecami elektrycznymi, ograniczone przestrzenie przewodzące oraz pomieszczenia medyczne, dopuszczalne jest tylko 30 mA prądu. To oznacza, że obwody elektryczne muszą być zaprojektowane tak, aby maksymalny prąd uderzeniowy był niższy niż 30 mA.

2. **Zasady dla miejsc o wysokim ryzyku**: W przypadku miejsc budowy, ograniczonych przestrzeni przewodzących oraz miejsc o zagrożeniu wybuchowym, stosowanie ręcznych urządzeń elektrycznych ≤ 32 A jest zabronione, co sugeruje, że należy używać urządzeń z odpowiednią klasą ochrony lub stosować inne środki bezpieczeństwa.

3. **Użycie SELV**: W przypadku bazenów i innych zbiorników, źródła prądu muszą być typu SELV (Safe Extra Low Voltage), co wskazuje na konieczność stosowania niskiego napięcia, aby zwiększyć poziom bezpieczeństwa.

4. **Oddzielne gniazda elektryczne**: W portach jachtowych, przyczepach kempingowych i domach przewoznych, wszystkie gniazda elektryczne oraz stałe połączenia zasilające pojazd muszą być oddzielne, co jest wymagane dla zapewnienia izolicacji i minimalizacji ryzyka elektrycznego.

5. **Ograniczenia dla instalacji oświetlenia**: W systemach oświetlenia zewnętrznych, takich jak budki telefoniczne, przystanki autobusowe, itp., końcowe obwody elektryczne ≤ 32 A mogą być stosowane, z wyłączeniem oświetlenia awaryjnego, co może wskazywać na konieczność specjalnych rozwiązań dla sytuacji awaryjnych.

Te zasady są kluczowe dla projektowania i utrzymywania bezpiecznej instalacji elektrycznej w różnych miejscach i warunkach.

==================================================

--- VIKHR-NEMO: WYNIK ZADANIA 3 (TERMINOLOGIA) ---

W podanym dokumencie nie ma żadnych skrótów technicznych. Tekst zawiera tylko słowo "wyłączniki" oraz "różnicoprzewodowe". Jeśli chciałbyś więcej informacji o wyłącznikach różnicoprzewodowych lub innych skrótach technicznych związanych z elektryką, musiałbymić mi dostęp do odpowiednich dokumentów, które zawierają te skróty. Wyłączniki różnicoprzewodowe to urządzenia ochrony, które odczynają obciążenie w przypadku wykrycia prądu różnicowego, co może wskazywać na usterkę w instalacji elektrycznej.

In [ ]:
# 2. Funkcja przygotowująca dane JSON (Standard RAG)
def prepare_rag_documents(file_path, pages_to_extract):
    documents = []
    doc_pdf = fitz.open(file_path)

    for i, pg_num in enumerate(pages_to_extract):
        if pg_num <= len(doc_pdf):
            page = doc_pdf[pg_num - 1]
            text = page.get_text().strip()

            doc_entry = {
                "doc_id": i,
                "title": f"ICAO Technical Instructions - Page {pg_num}",
                "content": text[:4000]
            }
            documents.append(doc_entry)

    doc_pdf.close()
    return json.dumps(documents, ensure_ascii=False)

In [ ]:
# 3. Parametry pliku
pdf_file = "/content/english instruction.pdf"

In [ ]:
# --- TASK 2: Safety & Prohibitions (Absolute page 45) ---
safety_pages = [24]
context_safety = prepare_rag_documents(pdf_file, safety_pages)

messages_safety = [
    {
        "role": "system",
        "content": "You are an aviation safety expert. Your task is to analyze ICAO technical instructions. Answer strictly based on the provided JSON data in English."
    },
    {
        "role": "user",
        "content": f"Here is the ICAO documentation in JSON format:\n{context_safety}\n\nTask: List the 5 most critical safety rules or prohibitions described in this section. Focus specifically on what is strictly forbidden for air transport."
    }
]

# --- TASK 3: Terminology (Absolute page 55) ---
def_pages = [34]
context_defs = prepare_rag_documents(pdf_file, def_pages)

messages_defs = [
    {
        "role": "system",
        "content": "You are an aviation safety expert. Your task is to analyze ICAO technical instructions. Answer strictly based on the provided JSON data in English."
    },
    {
        "role": "user",
        "content": f"Here is the ICAO documentation in JSON format:\n{context_defs}\n\nTask: Identify 3 technical abbreviations or terms (e.g., UN number, ICAO, PSN) and explain their meaning based on the document."
    }
]

In [ ]:
# 4. Funkcja do generowania odpowiedzi (zintegrowana z szablonem Bielika)
def generate_response(messages):
    encoded_input = tokenizer.apply_chat_template(
        messages,
        return_tensors="pt",
        add_generation_prompt=True
    )
    input_ids = encoded_input['input_ids'].to("cuda")

    outputs = model.generate(
        input_ids,
        max_new_tokens=1000,
        do_sample=True,
        temperature=0.3,
        top_p=0.9,
        repetition_penalty=1.1
    )
    return tokenizer.decode(outputs[0][input_ids.shape[-1]:], skip_special_tokens=True)

In [ ]:
# 5. Uruchomienie analizy
print("--- VIKHR-NEMO: TASK 2 RESULT (SAFETY & PROHIBITIONS) ---")
print(generate_response(messages_safety))

print("\n" + "="*50 + "\n")

print("--- VIKHR-NEMO: TASK 3 RESULT (TERMINOLOGY) ---")
print(generate_response(messages_defs))

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.

--- VIKHR-NEMO: TASK 2 RESULT (SAFETY & PROHIBITIONS) ---

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.

Based on the provided ICAO technical instructions from page 24, here are the five most critical safety rules or prohibitions related to dangerous goods transportation:

1. **Prohibition on Unapproved Goods**: These Instructions do not apply to dangerous goods unless they meet specific criteria, such as having been approved by the operator or forming part of the aircraft's permanent equipment.

2. **Securing Equipment During Flight**: Dangerous goods used for medical aid (with batteries) must be kept and secured upright to prevent electrolyte spillage.

3. **No Spillage of Fuel**: Vehicles carried in aircraft for ferry operations must have their fuel tanks filled to prevent any spillage during loading, unloading, and transit.

4. **Ventilation Requirements**: Adequate ventilation rates must be maintained in the aircraft compartment where vehicles or other specialized equipment are carried.

5. **Stowing and Securing Dangerous Goods**: There must be provision to stow and secure dangerous goods during take-off, landing, and whenever necessary as determined by the pilot-in-command.

These rules emphasize the importance of proper securing, ventilation, and prevention of hazardous material spills to ensure safety during air transport. They also highlight the need for operator approval and supervision of dangerous goods handling.

==================================================

--- VIKHR-NEMO: TASK 3 RESULT (TERMINOLOGY) ---
### Analysis of ICAO Technical Instructions - Page 34

From the provided JSON data containing extracts from the ICAO Technical Instructions, we can identify three technical abbreviations or terms:

1. **UN Number**
   - The UN Number is a unique identifier assigned to each class of dangerous goods for transportation purposes. It is used internationally to ensure consistency and safety when shipping hazardous materials.

2. **IATA Dangerous Goods Regulations (DGR)**
   - Although not explicitly mentioned with the abbreviation "DGR," the context implies references to regulations governing the transport of dangerous goods, which aligns with the IATA Dangerous Goods Regulations. These regulations provide guidance on the safe transportation of hazardous materials by air, including packaging, labeling, and documentation requirements.

3. **Packing Group**
   - While not an abbreviation, "Packing Group" refers to categories within the classification of dangerous goods that determine the level of risk associated with the material. There are typically three packing groups (I, II, and III), where I represents the highest risk and III the lowest. This categorization helps in establishing the appropriate packaging standards and handling procedures for different classes of dangerous goods.

These terms and abbreviations are crucial for ensuring the safe transportation of hazardous materials by air, as they provide a standardized framework for identifying, classifying, and handling such materials. Understanding these concepts is essential for aviation safety experts and personnel involved in the logistics and transportation of dangerous goods.

Based on the provided ICAO technical instructions from page 24, here are the five most critical safety rules or prohibitions related to dangerous goods transportation:

1. **Prohibition on Unapproved Goods**: These Instructions do not apply to dangerous goods unless they meet specific criteria, such as having been approved by the operator or forming part of the aircraft's permanent equipment.

2. **Securing Equipment During Flight**: Dangerous goods used for medical aid (with batteries) must be kept and secured upright to prevent electrolyte spillage.

3. **No Spillage of Fuel**: Vehicles carried in aircraft for ferry operations must have their fuel tanks filled to prevent any spillage during loading, unloading, and transit.

4. **Ventilation Requirements**: Adequate ventilation rates must be maintained in the aircraft compartment where vehicles or other specialized equipment are carried.

5. **Stowing and Securing Dangerous Goods**: There must be provision to stow and secure dangerous goods during take-off, landing, and whenever necessary as determined by the pilot-in-command.

These rules emphasize the importance of proper securing, ventilation, and prevention of hazardous material spills to ensure safety during air transport. They also highlight the need for operator approval and supervision of dangerous goods handling.

==================================================

--- VIKHR-NEMO: TASK 3 RESULT (TERMINOLOGY) ---
### Analysis of ICAO Technical Instructions - Page 34

From the provided JSON data containing extracts from the ICAO Technical Instructions, we can identify three technical abbreviations or terms:

1. **UN Number**
   - The UN Number is a unique identifier assigned to each class of dangerous goods for transportation purposes. It is used internationally to ensure consistency and safety when shipping hazardous materials.

2. **IATA Dangerous Goods Regulations (DGR)**
   - Although not explicitly mentioned with the abbreviation "DGR," the context implies references to regulations governing the transport of dangerous goods, which aligns with the IATA Dangerous Goods Regulations. These regulations provide guidance on the safe transportation of hazardous materials by air, including packaging, labeling, and documentation requirements.

3. **Packing Group**
   - While not an abbreviation, "Packing Group" refers to categories within the classification of dangerous goods that determine the level of risk associated with the material. There are typically three packing groups (I, II, and III), where I represents the highest risk and III the lowest. This categorization helps in establishing the appropriate packaging standards and handling procedures for different classes of dangerous goods.

These terms and abbreviations are crucial for ensuring the safe transportation of hazardous materials by air, as they provide a standardized framework for identifying, classifying, and handling such materials. Understanding these concepts is essential for aviation safety experts and personnel involved in the logistics and transportation of dangerous goods.

In [ ]:
# 2. Функция подготовки данных JSON (Стандарт RAG)
def prepare_rag_documents(file_path, pages_to_extract):
    documents = []
    doc_pdf = fitz.open(file_path)

    for i, pg_num in enumerate(pages_to_extract):
        if pg_num <= len(doc_pdf):
            page = doc_pdf[pg_num - 1]
            text = page.get_text().strip()

            doc_entry = {
                "doc_id": i,
                "title": f"Техническая инструкция ГИС - Страница {pg_num}",
                "content": text[:4000]
            }
            documents.append(doc_entry)

    doc_pdf.close()
    return json.dumps(documents, ensure_ascii=False)

In [ ]:
# 3. Путь к файлу
pdf_file = "/content/geokniga-tehnicheskayainstrukciyapoprovedeniyugeofizicheskihissledovaniyvskvazhinah.pdf"

In [ ]:
# --- ЗАДАНИЕ 2: Техника безопасности и аварии ---
safety_pages = [290]
context_safety = prepare_rag_documents(pdf_file, safety_pages)

messages_safety = [
    {
        "role": "system",
        "content": "Вы — эксперт-геофизик с многолетним стажем. Ваша задача — анализировать старые технические инструкции. Ответы должны базироваться исключительно на предоставленных данных JSON."
    },
    {
        "role": "user",
        "content": f"Вот фрагмент инструкции в формате JSON:\n{context_safety}\n\nЗадание: На основе этого текста перечислите 5 наиболее важных правил техники безопасности или действий при возникновении аварий. Укажите, что именно строго запрещено."
    }
]

# --- ЗАДАНИЕ 3: Терминология и сокращения ---
def_pages = [15]
context_defs = prepare_rag_documents(pdf_file, def_pages)

messages_defs = [
    {
        "role": "system",
        "content": "Вы — эксперт-геофизик. Ваша задача — расшифровать технические термины и сокращения из предоставленного текста."
    },
    {
        "role": "user",
        "content": f"Вот фрагмент инструкции в формате JSON:\n{context_defs}\n\nЗадание: Найдите и объясните значение 3 технических сокращений (например, ГИС, КС, ПС), опираясь только на предоставленный документ."
    }
]

In [ ]:
# 4. Funkcja do generowania odpowiedzi (zintegrowana z szablonem Bielika)
def generate_response(messages):
    encoded_input = tokenizer.apply_chat_template(
        messages,
        return_tensors="pt",
        add_generation_prompt=True
    )
    input_ids = encoded_input['input_ids'].to("cuda")

    outputs = model.generate(
        input_ids,
        max_new_tokens=1000,
        do_sample=True,
        temperature=0.3,
        top_p=0.9,
        repetition_penalty=1.1
    )
    return tokenizer.decode(outputs[0][input_ids.shape[-1]:], skip_special_tokens=True)

In [ ]:
# 5. Выполнение задач
print("--- VIKHR-NEMO: РЕЗУЛЬТАТ ЗАДАНИЯ 2 (БЕЗОПАСНОСТЬ) ---")
print(generate_response(messages_safety))

print("\n" + "="*50 + "\n")

print("--- VIKHR-NEMO: РЕЗУЛЬТАТ ЗАДАНИЯ 3 (ТЕРМИНОЛОГИЯ) ---")
print(generate_response(messages_defs))

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.

--- VIKHR-NEMO: РЕЗУЛЬТАТ ЗАДАНИЯ 2 (БЕЗОПАСНОСТЬ) ---

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.

На основе представленного фрагмента инструкции можно выделить следующие пять важных правил техники безопасности или действий при возникновении аварий:

1. **Необходимость составления акта** – на все происшедшие в скважинах аварии, включая случаи оставления грузов, зондов и т.п., должен составляться акт главным инженером предприятия, начальником партии (отряда) и другими уполномоченными лицами.

2. **Обязанность сообщать о сложных авариях** – при возникновении сложных аварий или аварий с человеческими жертвами необходимо немедленно отправлять извещения в вышестоящие организации, органы горно-технического надзора, технический инспектор профсоюза и органы милиции.

3. **Расследование сложных аварий** – сложные аварии должны расследоваться комиссией, включающей главного инженера предприятия, начальника партии, представителей надзорных органов и других специалистов. Комиссия обязана установить причины аварии, определить виновников и предложить меры по предотвращению подобных ситуаций в будущем.

4. **Представление информации о простых авариях** – данные о простых авариях должны представляться вышестоящей организации вместе с информационно-техническими отчетами.

5. **Установление причин аварии и виновников** – в акте о случившемся инциденте должна быть четко указана причина аварии и определены виновники. В случае споров между сторонами проводится техническая экспертиза, решение которой обязательно для всех участников.

Что касается строгих запретов, то в данном тексте они не упоминаются напрямую. Однако подразумевается, что игнорирование этих правил может привести к серьезным последствиям, включая юридическую ответственность за нарушение техники безопасности и возможное несоблюдение законодательства.

==================================================

--- VIKHR-NEMO: РЕЗУЛЬТАТ ЗАДАНИЯ 3 (ТЕРМИНОЛОГИЯ) ---
Из предоставленного текста можно выделить три технических сокращения:

1. **ГИС** - это аббревиатура от "геофизические исследования". Это общее понятие, которое охватывает различные методы и технологии, используемые для изучения подземных слоев Земли без необходимости физического доступа к ним.

2. **ПС** - это сокращение от "профильная скорость" или "профильный сигнал". В контексте стандартного электрического каротажа упоминается запись кривой ПС, что может означать графическое представление данных, полученных в процессе каротажа, где по оси абсцисс откладывается глубина, а по оси ординат – значения удельного сопротивления или другие параметры.

3. **БКЗ** - это сокращение от "боковое каротажное зондирование". Этот метод используется для получения информации о свойствах пород вокруг скважины путем измерения их удельного сопротивления с помощью специальных зондов, которые могут вращаться вокруг вертикальной оси скважины, обеспечивая тем самым сбор данных в разных направлениях.

Эти сокращения являются специфическими терминами, используемыми в области геофизики и геологической разведки, и имеют важное значение для интерпретации результатов исследований и принятия решений при разработке месторождений полезных ископаемых.

На основе представленного фрагмента инструкции можно выделить следующие пять важных правил техники безопасности или действий при возникновении аварий:

1. **Необходимость составления акта** – на все происшедшие в скважинах аварии, включая случаи оставления грузов, зондов и т.п., должен составляться акт главным инженером предприятия, начальником партии (отряда) и другими уполномоченными лицами.

2. **Обязанность сообщать о сложных авариях** – при возникновении сложных аварий или аварий с человеческими жертвами необходимо немедленно отправлять извещения в вышестоящие организации, органы горно-технического надзора, технический инспектор профсоюза и органы милиции.

3. **Расследование сложных аварий** – сложные аварии должны расследоваться комиссией, включающей главного инженера предприятия, начальника партии, представителей надзорных органов и других специалистов. Комиссия обязана установить причины аварии, определить виновников и предложить меры по предотвращению подобных ситуаций в будущем.

4. **Представление информации о простых авариях** – данные о простых авариях должны представляться вышестоящей организации вместе с информационно-техническими отчетами.

5. **Установление причин аварии и виновников** – в акте о случившемся инциденте должна быть четко указана причина аварии и определены виновники. В случае споров между сторонами проводится техническая экспертиза, решение которой обязательно для всех участников.

Что касается строгих запретов, то в данном тексте они не упоминаются напрямую. Однако подразумевается, что игнорирование этих правил может привести к серьезным последствиям, включая юридическую ответственность за нарушение техники безопасности и возможное несоблюдение законодательства.

==================================================

--- VIKHR-NEMO: РЕЗУЛЬТАТ ЗАДАНИЯ 3 (ТЕРМИНОЛОГИЯ) ---
Из предоставленного текста можно выделить три технических сокращения:

1. **ГИС** - это аббревиатура от "геофизические исследования". Это общее понятие, которое охватывает различные методы и технологии, используемые для изучения подземных слоев Земли без необходимости физического доступа к ним.

2. **ПС** - это сокращение от "профильная скорость" или "профильный сигнал". В контексте стандартного электрического каротажа упоминается запись кривой ПС, что может означать графическое представление данных, полученных в процессе каротажа, где по оси абсцисс откладывается глубина, а по оси ординат – значения удельного сопротивления или другие параметры.

3. **БКЗ** - это сокращение от "боковое каротажное зондирование". Этот метод используется для получения информации о свойствах пород вокруг скважины путем измерения их удельного сопротивления с помощью специальных зондов, которые могут вращаться вокруг вертикальной оси скважины, обеспечивая тем самым сбор данных в разных направлениях.

Эти сокращения являются специфическими терминами, используемыми в области геофизики и геологической разведки, и имеют важное значение для интерпретации результатов исследований и принятия решений при разработке месторождений полезных ископаемых.

# **IŁOŚCIOWA ANALIZA PORÓWNAWCZA**

**6 easy tasks**

English prompt

In [6]:
import pandas as pd
import torch
import time

# 1. Load dataset
df = pd.read_csv("/content/tiktok_instagram_global_100countries.csv")

print("Dataset shape:", df.shape)
print(df.columns.tolist())
df.head()

Dataset shape: (10000, 23)
['user_id', 'country', 'age', 'year', 'internet_penetration', 'mental_health_support_index', 'gdp_index', 'youth_population_ratio', 'baseline_addiction_pressure', 'tiktok_minutes_daily', 'instagram_minutes_daily', 'night_usage_ratio', 'scroll_velocity', 'addiction_pressure', 'attention_span_score', 'dopamine_dependency_score', 'impulsivity_index', 'sleep_hours', 'sleep_quality_index', 'ASI', 'MHRI', 'addiction_score', 'addiction_level']

,user_id,country,age,year,internet_penetration,mental_health_support_index,gdp_index,youth_population_ratio,baseline_addiction_pressure,tiktok_minutes_daily,...,addiction_pressure,attention_span_score,dopamine_dependency_score,impulsivity_index,sleep_hours,sleep_quality_index,ASI,MHRI,addiction_score,addiction_level
0,1,Philippines,59,2050,88.895513,64.347080,0.312067,0.310389,64.762693,242.853130,...,69.981792,77.479304,27.024835,60.044856,6.561778,7.912360,100.0,40.460626,63.512418,High
1,2,Netherlands,23,2035,57.950292,76.257045,0.460320,0.293134,37.592646,98.599951,...,56.862382,78.852713,25.376744,81.769114,9.400197,2.292106,100.0,79.424028,62.688372,High
2,3,Laos,26,2060,40.325805,55.846514,0.893658,0.183055,22.589595,127.221573,...,41.817693,83.573012,19.712386,99.613065,7.810417,2.308761,100.0,88.262729,59.856193,High
3,4,Bulgaria,50,2046,43.838044,28.390576,0.661523,0.155038,57.093084,140.528514,...,70.811984,83.437675,19.874790,86.935944,7.020033,4.512440,100.0,70.905771,59.937395,High
4,5,Zambia,24,2045,43.749943,81.413755,0.275186,0.457115,57.653485,187.748696,...,71.990949,71.993561,33.607727,45.275020,7.900621,4.265014,100.0,51.312439,66.803864,High

In [7]:
correct_answers = {
    "E1": df.loc[df["addiction_score"].idxmax(), "country"],
    "E2": round(df["addiction_score"].mean(), 2),
    "E3": df.groupby("year")["tiktok_minutes_daily"].mean().idxmax(),
    "E4": int((df["addiction_level"] == "High").sum()),
    "E5": round(df["sleep_hours"].min(), 2),
    "E6": df.groupby("country")["instagram_minutes_daily"].mean().idxmax()
}

correct_answers

{'E1': 'Ghana',
 'E2': np.float64(58.55),
 'E3': np.int64(2044),
 'E4': 8680,
 'E5': 3.0,
 'E6': 'UK'}

In [8]:
simple_tasks = [
    {
        "task_id": "E1",
        "difficulty": "easy",
        "question": "Which country has the highest addiction_score in the provided table?",
        "data": df[["country", "addiction_score"]]
            .sort_values("addiction_score", ascending=False)
            .head(30)
    },
    {
        "task_id": "E2",
        "difficulty": "easy",
        "question": "What is the average addiction_score in the provided table? Round the answer to two decimal places.",
        "data": pd.DataFrame({
            "average_addiction_score": [round(df["addiction_score"].mean(), 2)]
        })
    },
    {
        "task_id": "E3",
        "difficulty": "easy",
        "question": "Which year has the highest average tiktok_minutes_daily in the provided table?",
        "data": df.groupby("year", as_index=False)["tiktok_minutes_daily"]
            .mean()
            .sort_values("tiktok_minutes_daily", ascending=False)
    },
    {
        "task_id": "E4",
        "difficulty": "easy",
        "question": "How many observations have addiction_level equal to High?",
        "data": pd.DataFrame({
            "addiction_level": ["High"],
            "number_of_observations": [int((df["addiction_level"] == "High").sum())]
        })
    },
    {
        "task_id": "E5",
        "difficulty": "easy",
        "question": "What is the minimum sleep_hours value in the provided table? Round the answer to two decimal places.",
        "data": pd.DataFrame({
            "minimum_sleep_hours": [round(df["sleep_hours"].min(), 2)]
        })
    },
    {
        "task_id": "E6",
        "difficulty": "easy",
        "question": "Which country has the highest average instagram_minutes_daily in the provided table?",
        "data": df.groupby("country", as_index=False)["instagram_minutes_daily"]
            .mean()
            .sort_values("instagram_minutes_daily", ascending=False)
            .head(30)
    }
]

In [9]:
def generate_response(messages, max_new_tokens=100):
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer(
        text,
        return_tensors="pt"
    ).to(model.device)

    start_time = time.time()

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,  # Изменили тут: temperature=0.0 убран
            pad_token_id=tokenizer.eos_token_id
        )

    end_time = time.time()

    response = tokenizer.decode(
        outputs[0][inputs["input_ids"].shape[-1]:],
        skip_special_tokens=True
    )

    return response.strip(), round(end_time - start_time, 3)

In [10]:
results = []

for task in simple_tasks:
    table_text = task["data"].to_string(index=False)

    messages = [
        {
            "role": "system",
            "content": (
                "You are a data analyst. "
                "Use only the provided table. "
                "Return only the final answer. "
                "Do not explain your reasoning."
            )
        },
        {
            "role": "user",
            "content": f"""
Here is the table:

{table_text}

Task:
{task["question"]}
"""
        }
    ]

    answer, response_time = generate_response(messages)

    results.append({
        "model": "Bielik-11B",
        "task_id": task["task_id"],
        "difficulty": task["difficulty"],
        "question": task["question"],
        "model_answer": answer,
        "correct_answer": correct_answers[task["task_id"]],
        "response_time_sec": response_time
    })

results_df = pd.DataFrame(results)
results_df

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

,model,task_id,difficulty,question,model_answer,correct_answer,response_time_sec
0,Bielik-11B,E1,easy,Which country has the highest addiction_score ...,Ghana,Ghana,1.269
1,Bielik-11B,E2,easy,What is the average addiction_score in the pro...,58.55,58.55,0.591
2,Bielik-11B,E3,easy,Which year has the highest average tiktok_minu...,2044,2044,0.517
3,Bielik-11B,E4,easy,How many observations have addiction_level equ...,8680,8680,0.491
4,Bielik-11B,E5,easy,What is the minimum sleep_hours value in the p...,3.00,3.0,0.491
5,Bielik-11B,E6,easy,Which country has the highest average instagra...,The country with the highest average Instagram...,UK,2.896

polish prompt

In [11]:
simple_tasks_pl = [
    {
        "task_id": "E1",
        "difficulty": "easy",
        "language": "PL",
        "question": "Który kraj ma najwyższą wartość addiction_score w podanej tabeli?",
        "data": df[["country", "addiction_score"]]
            .sort_values("addiction_score", ascending=False)
            .head(30)
    },
    {
        "task_id": "E2",
        "difficulty": "easy",
        "language": "PL",
        "question": "Jaka jest średnia wartość addiction_score w podanej tabeli? Zaokrąglij odpowiedź do dwóch miejsc po przecinku.",
        "data": pd.DataFrame({
            "average_addiction_score": [round(df["addiction_score"].mean(), 2)]
        })
    },
    {
        "task_id": "E3",
        "difficulty": "easy",
        "language": "PL",
        "question": "W którym roku średnia wartość tiktok_minutes_daily była najwyższa w podanej tabeli?",
        "data": df.groupby("year", as_index=False)["tiktok_minutes_daily"]
            .mean()
            .sort_values("tiktok_minutes_daily", ascending=False)
    },
    {
        "task_id": "E4",
        "difficulty": "easy",
        "language": "PL",
        "question": "Ile obserwacji ma addiction_level równy High?",
        "data": pd.DataFrame({
            "addiction_level": ["High"],
            "number_of_observations": [int((df["addiction_level"] == "High").sum())]
        })
    },
    {
        "task_id": "E5",
        "difficulty": "easy",
        "language": "PL",
        "question": "Jaka jest minimalna wartość sleep_hours w podanej tabeli? Zaokrąglij odpowiedź do dwóch miejsc po przecinku.",
        "data": pd.DataFrame({
            "minimum_sleep_hours": [round(df["sleep_hours"].min(), 2)]
        })
    },
    {
        "task_id": "E6",
        "difficulty": "easy",
        "language": "PL",
        "question": "Który kraj ma najwyższą średnią wartość instagram_minutes_daily w podanej tabeli?",
        "data": df.groupby("country", as_index=False)["instagram_minutes_daily"]
            .mean()
            .sort_values("instagram_minutes_daily", ascending=False)
            .head(30)
    }
]

In [12]:
def generate_response(messages, max_new_tokens=100):
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer(
        text,
        return_tensors="pt"
    ).to(model.device)

    start_time = time.time()

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,  # Изменили тут: temperature=0.0 убран
            pad_token_id=tokenizer.eos_token_id
        )

    end_time = time.time()

    response = tokenizer.decode(
        outputs[0][inputs["input_ids"].shape[-1]:],
        skip_special_tokens=True
    )

    return response.strip(), round(end_time - start_time, 3)

In [13]:
results_pl = []

for task in simple_tasks_pl:
    table_text = task["data"].to_string(index=False)

    messages = [
        {
            "role": "system",
            "content": (
                "Jesteś analitykiem danych. "
                "Korzystaj wyłącznie z podanej tabeli. "
                "Zwróć tylko końcową odpowiedź. "
                "Nie wyjaśniaj toku rozumowania."
            )
        },
        {
            "role": "user",
            "content": f"""
Oto tabela:

{table_text}

Zadanie:
{task["question"]}
"""
        }
    ]

    answer, response_time = generate_response(messages)

    results_pl.append({
        "model": "Bielik-11B",
        "task_id": task["task_id"],
        "difficulty": task["difficulty"],
        "language": task["language"],
        "question": task["question"],
        "model_answer": answer,
        "correct_answer": correct_answers[task["task_id"]],
        "response_time_sec": response_time
    })

results_pl_df = pd.DataFrame(results_pl)
results_pl_df

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

,model,task_id,difficulty,language,question,model_answer,correct_answer,response_time_sec
0,Bielik-11B,E1,easy,PL,Który kraj ma najwyższą wartość addiction_scor...,Kraj z najwyższą wartością addiction_score w p...,Ghana,1.942
1,Bielik-11B,E2,easy,PL,Jaka jest średnia wartość addiction_score w po...,58.55,58.55,0.572
2,Bielik-11B,E3,easy,PL,W którym roku średnia wartość tiktok_minutes_d...,Rok 2044 ma najwyższą średnią wartość `tiktok_...,2044,2.874
3,Bielik-11B,E4,easy,PL,Ile obserwacji ma addiction_level równy High?,8680,8680,0.491
4,Bielik-11B,E5,easy,PL,Jaka jest minimalna wartość sleep_hours w poda...,3.00,3.0,0.494
5,Bielik-11B,E6,easy,PL,Który kraj ma najwyższą średnią wartość instag...,Kraj o najwyższej średniej wartości `instagram...,UK,4.585

Russian prompt

In [14]:
simple_tasks_ru = [
    {
        "task_id": "E1",
        "difficulty": "easy",
        "language": "RU",
        "question": "Какая страна имеет самое высокое значение addiction_score в предоставленной таблице?",
        "data": df[["country", "addiction_score"]]
            .sort_values("addiction_score", ascending=False)
            .head(30)
    },
    {
        "task_id": "E2",
        "difficulty": "easy",
        "language": "RU",
        "question": "Каково среднее значение addiction_score в предоставленной таблице? Округли ответ до двух знаков после запятой.",
        "data": pd.DataFrame({
            "average_addiction_score": [round(df["addiction_score"].mean(), 2)]
        })
    },
    {
        "task_id": "E3",
        "difficulty": "easy",
        "language": "RU",
        "question": "В каком году среднее значение tiktok_minutes_daily было самым высоким в предоставленной таблице?",
        "data": df.groupby("year", as_index=False)["tiktok_minutes_daily"]
            .mean()
            .sort_values("tiktok_minutes_daily", ascending=False)
    },
    {
        "task_id": "E4",
        "difficulty": "easy",
        "language": "RU",
        "question": "Сколько наблюдений имеют значение addiction_level, равное High?",
        "data": pd.DataFrame({
            "addiction_level": ["High"],
            "number_of_observations": [int((df["addiction_level"] == "High").sum())]
        })
    },
    {
        "task_id": "E5",
        "difficulty": "easy",
        "language": "RU",
        "question": "Каково минимальное значение sleep_hours в предоставленной таблице? Округли ответ до двух знаков после запятой.",
        "data": pd.DataFrame({
            "minimum_sleep_hours": [round(df["sleep_hours"].min(), 2)]
        })
    },
    {
        "task_id": "E6",
        "difficulty": "easy",
        "language": "RU",
        "question": "Какая страна имеет самое высокое среднее значение instagram_minutes_daily в предоставленной таблице?",
        "data": df.groupby("country", as_index=False)["instagram_minutes_daily"]
            .mean()
            .sort_values("instagram_minutes_daily", ascending=False)
            .head(30)
    }
]

In [15]:
def generate_response(messages, max_new_tokens=100):
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer(
        text,
        return_tensors="pt"
    ).to(model.device)

    start_time = time.time()

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,  # Изменили тут: temperature=0.0 убран
            pad_token_id=tokenizer.eos_token_id
        )

    end_time = time.time()

    response = tokenizer.decode(
        outputs[0][inputs["input_ids"].shape[-1]:],
        skip_special_tokens=True
    )

    return response.strip(), round(end_time - start_time, 3)

In [16]:
results_ru = []
for task in simple_tasks_ru:
    table_text = task["data"].to_string(index=False)
    messages = [                          # <-- must be indented inside loop
        {
            "role": "system",
            "content": (
                "Ты аналитик данных. "
                "Используй только предоставленную таблицу. "
                "Верни только итоговый ответ. "
                "Не объясняй ход рассуждений."
            )
        },
        {
            "role": "user",
            "content": f"""
Вот таблица:
{table_text}

Задание:
{task["question"]}
"""
        }
    ]
    answer, response_time = generate_response(messages)
    results_ru.append({                   # <-- must be indented inside loop
        "model": "Vikhr-12B",
        "task_id": task["task_id"],
        "difficulty": task["difficulty"],
        "language": task["language"],
        "question": task["question"],
        "model_answer": answer,
        "correct_answer": correct_answers[task["task_id"]],
        "response_time_sec": response_time
    })

results_ru_df = pd.DataFrame(results_ru)
results_ru_df

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

,model,task_id,difficulty,language,question,model_answer,correct_answer,response_time_sec
0,Vikhr-12B,E1,easy,RU,Какая страна имеет самое высокое значение addi...,Страна с самым высоким значением addiction_sco...,Ghana,1.929
1,Vikhr-12B,E2,easy,RU,Каково среднее значение addiction_score в пред...,58.55,58.55,0.589
2,Vikhr-12B,E3,easy,RU,В каком году среднее значение tiktok_minutes_d...,Среднее значение `tiktok_minutes_daily` было с...,2044,2.440
3,Vikhr-12B,E4,easy,RU,Сколько наблюдений имеют значение addiction_le...,8680 наблюдений имеют значение addiction_level...,8680,1.624
4,Vikhr-12B,E5,easy,RU,Каково минимальное значение sleep_hours в пред...,3.00,3.0,0.501
5,Vikhr-12B,E6,easy,RU,Какая страна имеет самое высокое среднее значе...,Страна с самым высоким средним значением insta...,UK,4.156

6 middle level tasks

English prompt

In [17]:
# =========================
# MEDIUM TASKS — Vikhr
# =========================

medium_correct_answers = {
    "M1": round(
        (
            df[df["year"] == 2030]["tiktok_minutes_daily"].mean()
            - df[df["year"] == 2020]["tiktok_minutes_daily"].mean()
        )
        / df[df["year"] == 2020]["tiktok_minutes_daily"].mean()
        * 100,
        2
    ),

    "M2": (
        df.groupby("country")[["tiktok_minutes_daily", "instagram_minutes_daily"]]
        .mean()
        .assign(diff=lambda x: abs(x["tiktok_minutes_daily"] - x["instagram_minutes_daily"]))
        .sort_values("diff", ascending=False)
        .index[0]
    ),

    "M3": (
        df.groupby("country")["addiction_score"]
        .mean()
        .idxmax()
    ),

    "M4": round(
        (df["sleep_quality_index"] < df["sleep_quality_index"].mean()).mean() * 100,
        2
    ),

    "M5": round(
        df[df["addiction_level"] == "High"]["MHRI"].mean()
        - df[df["addiction_level"] == "Low"]["MHRI"].mean(),
        2
    ),

    "M6": (
        df.groupby("country")["dopamine_dependency_score"]
        .mean()
        .sort_values(ascending=False)
        .head(3)
        .index.tolist()
    )
}

medium_correct_answers

{'M1': np.float64(4.45),
 'M2': 'Maldives',
 'M3': 'Tanzania',
 'M4': np.float64(49.99),
 'M5': np.float64(6.82),
 'M6': ['Tanzania', 'Argentina', 'Malaysia']}

In [18]:
medium_tasks_en = [
    {
        "task_id": "M1",
        "difficulty": "medium",
        "language": "EN",
        "question": "By what percentage did the average tiktok_minutes_daily increase or decrease between 2020 and 2030? Round the answer to two decimal places.",
        "data": df[df["year"].isin([2020, 2030])]
            .groupby("year", as_index=False)["tiktok_minutes_daily"]
            .mean()
    },
    {
        "task_id": "M2",
        "difficulty": "medium",
        "language": "EN",
        "question": "Which country has the largest absolute difference between average tiktok_minutes_daily and average instagram_minutes_daily?",
        "data": df.groupby("country", as_index=False)[["tiktok_minutes_daily", "instagram_minutes_daily"]]
            .mean()
            .assign(diff=lambda x: abs(x["tiktok_minutes_daily"] - x["instagram_minutes_daily"]))
            .sort_values("diff", ascending=False)
            .head(30)
    },
    {
        "task_id": "M3",
        "difficulty": "medium",
        "language": "EN",
        "question": "Which country has the highest average addiction_score?",
        "data": df.groupby("country", as_index=False)["addiction_score"]
            .mean()
            .sort_values("addiction_score", ascending=False)
            .head(30)
    },
    {
        "task_id": "M4",
        "difficulty": "medium",
        "language": "EN",
        "question": "What percentage of observations have sleep_quality_index below the overall average? Round the answer to two decimal places.",
        "data": pd.DataFrame({
            "overall_average_sleep_quality_index": [df["sleep_quality_index"].mean()],
            "observations_below_average": [(df["sleep_quality_index"] < df["sleep_quality_index"].mean()).sum()],
            "total_observations": [len(df)],
            "percentage_below_average": [round((df["sleep_quality_index"] < df["sleep_quality_index"].mean()).mean() * 100, 2)]
        })
    },
    {
        "task_id": "M5",
        "difficulty": "medium",
        "language": "EN",
        "question": "What is the difference between the average MHRI for High addiction_level and Low addiction_level? Round the answer to two decimal places.",
        "data": df[df["addiction_level"].isin(["High", "Low"])]
            .groupby("addiction_level", as_index=False)["MHRI"]
            .mean()
    },
    {
        "task_id": "M6",
        "difficulty": "medium",
        "language": "EN",
        "question": "Which three countries have the highest average dopamine_dependency_score? Return the country names only.",
        "data": df.groupby("country", as_index=False)["dopamine_dependency_score"]
            .mean()
            .sort_values("dopamine_dependency_score", ascending=False)
            .head(10)
    }
]

In [19]:
def generate_response(messages, max_new_tokens=100):
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer(
        text,
        return_tensors="pt"
    ).to(model.device)

    start_time = time.time()

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,  # Изменили тут: temperature=0.0 убран
            pad_token_id=tokenizer.eos_token_id
        )

    end_time = time.time()

    response = tokenizer.decode(
        outputs[0][inputs["input_ids"].shape[-1]:],
        skip_special_tokens=True
    )

    return response.strip(), round(end_time - start_time, 3)

In [20]:
results_medium_en = []

for task in medium_tasks_en:
    table_text = task["data"].to_string(index=False)

    messages = [
        {
            "role": "system",
            "content": (
                "You are a data analyst. "
                "Use only the provided table. "
                "Return only the final answer. "
                "Do not explain your reasoning."
            )
        },
        {
            "role": "user",
            "content": f"""
Here is the table:

{table_text}

Task:
{task["question"]}
"""
        }
    ]

    answer, response_time = generate_response(messages)

    results_medium_en.append({
        "model": "Vikhr-12B",
        "task_id": task["task_id"],
        "difficulty": task["difficulty"],
        "language": task["language"],
        "question": task["question"],
        "model_answer": answer,
        "correct_answer": medium_correct_answers[task["task_id"]],
        "response_time_sec": response_time
    })

results_medium_en_df = pd.DataFrame(results_medium_en)
results_medium_en_df

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

,model,task_id,difficulty,language,question,model_answer,correct_answer,response_time_sec
0,Vikhr-12B,M1,medium,EN,By what percentage did the average tiktok_minu...,The average TikTok minutes daily increased by ...,4.45,2.681
1,Vikhr-12B,M2,medium,EN,Which country has the largest absolute differe...,Maldives,Maldives,0.462
2,Vikhr-12B,M3,medium,EN,Which country has the highest average addictio...,Tanzania,Tanzania,0.402
3,Vikhr-12B,M4,medium,EN,What percentage of observations have sleep_qua...,49.99,49.99,0.604
4,Vikhr-12B,M5,medium,EN,What is the difference between the average MHR...,6.82,6.82,0.512
5,Vikhr-12B,M6,medium,EN,Which three countries have the highest average...,"Tanzania, Argentina, Malaysia","[Tanzania, Argentina, Malaysia]",0.799

Polish prompt

In [21]:
medium_tasks_pl = [
    {
        "task_id": "M1",
        "difficulty": "medium",
        "language": "PL",
        "question": "O ile procent wzrosła lub spadła średnia wartość tiktok_minutes_daily między 2020 a 2030 rokiem? Zaokrąglij odpowiedź do dwóch miejsc po przecinku.",
        "data": df[df["year"].isin([2020, 2030])]
                    .groupby("year", as_index=False)["tiktok_minutes_daily"]
                    .mean()
    },
    {
        "task_id": "M2",
        "difficulty": "medium",
        "language": "PL",
        "question": "Który kraj ma największą bezwzględną różnicę między średnią wartością tiktok_minutes_daily a średnią wartością instagram_minutes_daily?",
        "data": df.groupby("country", as_index=False)[["tiktok_minutes_daily", "instagram_minutes_daily"]]
                    .mean()
                    .assign(diff=lambda x: abs(x["tiktok_minutes_daily"] - x["instagram_minutes_daily"]))
                    .sort_values("diff", ascending=False)
                    .head(30)
    },
    {
        "task_id": "M3",
        "difficulty": "medium",
        "language": "PL",
        "question": "Który kraj ma najwyższą średnią wartość addiction_score?",
        "data": df.groupby("country", as_index=False)["addiction_score"]
                    .mean()
                    .sort_values("addiction_score", ascending=False)
                    .head(30)
    },
    {
        "task_id": "M4",
        "difficulty": "medium",
        "language": "PL",
        "question": "Jaki procent obserwacji ma wartość sleep_quality_index poniżej ogólnej średniej? Zaokrąglij odpowiedź do dwóch miejsc po przecinku.",
        "data": pd.DataFrame({
            "overall_average_sleep_quality_index": [df["sleep_quality_index"].mean()],
            "observations_below_average": [(df["sleep_quality_index"] < df["sleep_quality_index"].mean()).sum()],
            "total_observations": [len(df)],
            "percentage_below_average": [round((df["sleep_quality_index"] < df["sleep_quality_index"].mean()).mean() * 100, 2)]
        })
    },
    {
        "task_id": "M5",
        "difficulty": "medium",
        "language": "PL",
        "question": "Jaka jest różnica między średnią wartością MHRI dla poziomu uzależnienia High a Low? Zaokrąglij odpowiedź do dwóch miejsc po przecinku.",
        "data": df[df["addiction_level"].isin(["High", "Low"])]
                    .groupby("addiction_level", as_index=False)["MHRI"]
                    .mean()
    },
    {
        "task_id": "M6",
        "difficulty": "medium",
        "language": "PL",
        "question": "Które trzy kraje mają najwyższą średnią wartość dopamine_dependency_score? Podaj tylko nazwy krajów.",
        "data": df.groupby("country", as_index=False)["dopamine_dependency_score"]
                    .mean()
                    .sort_values("dopamine_dependency_score", ascending=False)
                    .head(10)
    }
]

In [22]:
def generate_response(messages, max_new_tokens=100):
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer(
        text,
        return_tensors="pt"
    ).to(model.device)

    start_time = time.time()

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,  # Изменили тут: temperature=0.0 убран
            pad_token_id=tokenizer.eos_token_id
        )

    end_time = time.time()

    response = tokenizer.decode(
        outputs[0][inputs["input_ids"].shape[-1]:],
        skip_special_tokens=True
    )

    return response.strip(), round(end_time - start_time, 3)

In [23]:
results_medium_pl = []
for task in medium_tasks_pl:
    table_text = task["data"].to_string(index=False)
    messages = [
        {
            "role": "system",
            "content": (
                "Jesteś analitykiem danych. "
                "Korzystaj wyłącznie z podanej tabeli. "
                "Zwróć tylko końcową odpowiedź. "
                "Nie wyjaśniaj toku rozumowania."
            )
        },
        {
            "role": "user",
            "content": f"Oto tabela:\n\n{table_text}\n\nZadanie:\n{task['question']}"
        }
    ]
    answer, response_time = generate_response(messages)
    results_medium_pl.append({
        "model": "Vikhr-12B",
        "task_id": task["task_id"],
        "difficulty": task["difficulty"],
        "language": task["language"],
        "question": task["question"],
        "model_answer": answer,
        "correct_answer": medium_correct_answers[task["task_id"]],
        "response_time_sec": response_time
    })

results_medium_pl_df = pd.DataFrame(results_medium_pl)
results_medium_pl_df

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

,model,task_id,difficulty,language,question,model_answer,correct_answer,response_time_sec
0,Vikhr-12B,M1,medium,PL,O ile procent wzrosła lub spadła średnia warto...,Wartość `tiktok_minutes_daily` wzrosła o 4.44%.,4.45,2.098
1,Vikhr-12B,M2,medium,PL,Który kraj ma największą bezwzględną różnicę m...,Kraj z największą bezwzględną różnicą między ś...,Maldives,5.857
2,Vikhr-12B,M3,medium,PL,Który kraj ma najwyższą średnią wartość addict...,Kraj z najwyższą średnią wartością addiction_s...,Tanzania,1.736
3,Vikhr-12B,M4,medium,PL,Jaki procent obserwacji ma wartość sleep_quali...,49.99%,49.99,0.706
4,Vikhr-12B,M5,medium,PL,Jaka jest różnica między średnią wartością MHR...,6.82,6.82,0.493
5,Vikhr-12B,M6,medium,PL,Które trzy kraje mają najwyższą średnią wartoś...,"Tanzania, Argentina, Malaysia","[Tanzania, Argentina, Malaysia]",0.771

Russian prompt

In [24]:
medium_tasks_ru = [
    {
        "task_id": "M1",
        "difficulty": "medium",
        "language": "RU",
        "question": "На сколько процентов увеличилось или уменьшилось среднее значение tiktok_minutes_daily между 2020 и 2030 годами? Округли ответ до двух знаков после запятой.",
        "data": df[df["year"].isin([2020, 2030])]
                    .groupby("year", as_index=False)["tiktok_minutes_daily"]
                    .mean()
    },
    {
        "task_id": "M2",
        "difficulty": "medium",
        "language": "RU",
        "question": "Какая страна имеет наибольшую абсолютную разницу между средним значением tiktok_minutes_daily и средним значением instagram_minutes_daily?",
        "data": df.groupby("country", as_index=False)[["tiktok_minutes_daily", "instagram_minutes_daily"]]
                    .mean()
                    .assign(diff=lambda x: abs(x["tiktok_minutes_daily"] - x["instagram_minutes_daily"]))
                    .sort_values("diff", ascending=False)
                    .head(30)
    },
    {
        "task_id": "M3",
        "difficulty": "medium",
        "language": "RU",
        "question": "Какая страна имеет наибольшее среднее значение addiction_score?",
        "data": df.groupby("country", as_index=False)["addiction_score"]
                    .mean()
                    .sort_values("addiction_score", ascending=False)
                    .head(30)
    },
    {
        "task_id": "M4",
        "difficulty": "medium",
        "language": "RU",
        "question": "Какой процент наблюдений имеет значение sleep_quality_index ниже общего среднего? Округли ответ до двух знаков после запятой.",
        "data": pd.DataFrame({
            "overall_average_sleep_quality_index": [df["sleep_quality_index"].mean()],
            "observations_below_average": [(df["sleep_quality_index"] < df["sleep_quality_index"].mean()).sum()],
            "total_observations": [len(df)],
            "percentage_below_average": [round((df["sleep_quality_index"] < df["sleep_quality_index"].mean()).mean() * 100, 2)]
        })
    },
    {
        "task_id": "M5",
        "difficulty": "medium",
        "language": "RU",
        "question": "Какова разница между средним значением MHRI для уровня зависимости High и Low? Округли ответ до двух знаков после запятой.",
        "data": df[df["addiction_level"].isin(["High", "Low"])]
                    .groupby("addiction_level", as_index=False)["MHRI"]
                    .mean()
    },
    {
        "task_id": "M6",
        "difficulty": "medium",
        "language": "RU",
        "question": "Какие три страны имеют наибольшее среднее значение dopamine_dependency_score? Укажи только названия стран.",
        "data": df.groupby("country", as_index=False)["dopamine_dependency_score"]
                    .mean()
                    .sort_values("dopamine_dependency_score", ascending=False)
                    .head(10)
    }
]

In [25]:
def generate_response(messages, max_new_tokens=100):
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer(
        text,
        return_tensors="pt"
    ).to(model.device)

    start_time = time.time()

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,  # Изменили тут: temperature=0.0 убран
            pad_token_id=tokenizer.eos_token_id
        )

    end_time = time.time()

    response = tokenizer.decode(
        outputs[0][inputs["input_ids"].shape[-1]:],
        skip_special_tokens=True
    )

    return response.strip(), round(end_time - start_time, 3)

In [26]:
results_medium_ru = []
for task in medium_tasks_ru:
    table_text = task["data"].to_string(index=False)
    messages = [
        {
            "role": "system",
            "content": (
                "Ты аналитик данных. "
                "Используй только предоставленную таблицу. "
                "Верни только итоговый ответ. "
                "Не объясняй ход рассуждений."
            )
        },
        {
            "role": "user",
            "content": f"Вот таблица:\n\n{table_text}\n\nЗадание:\n{task['question']}"
        }
    ]
    answer, response_time = generate_response(messages)
    results_medium_ru.append({
        "model": "Vikhr-12B",
        "task_id": task["task_id"],
        "difficulty": task["difficulty"],
        "language": task["language"],
        "question": task["question"],
        "model_answer": answer,
        "correct_answer": medium_correct_answers[task["task_id"]],
        "response_time_sec": response_time
    })

results_medium_ru_df = pd.DataFrame(results_medium_ru)
results_medium_ru_df

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

,model,task_id,difficulty,language,question,model_answer,correct_answer,response_time_sec
0,Vikhr-12B,M1,medium,RU,На сколько процентов увеличилось или уменьшило...,Увеличение на 4.44%,4.45,1.089
1,Vikhr-12B,M2,medium,RU,Какая страна имеет наибольшую абсолютную разни...,Страна с наибольшей абсолютной разницей между ...,Maldives,3.862
2,Vikhr-12B,M3,medium,RU,Какая страна имеет наибольшее среднее значение...,Страна с наибольшим средним значением addictio...,Tanzania,1.631
3,Vikhr-12B,M4,medium,RU,Какой процент наблюдений имеет значение sleep_...,49.99%,49.99,0.705
4,Vikhr-12B,M5,medium,RU,Какова разница между средним значением MHRI дл...,Разница между средним значением MHRI для уровн...,6.82,2.273
5,Vikhr-12B,M6,medium,RU,Какие три страны имеют наибольшее среднее знач...,"Tanzania, Argentina, Malaysia","[Tanzania, Argentina, Malaysia]",0.763

**4 hard level tasks**

English prompt

In [27]:
# =========================
# HARD TASKS — Vikhr — EN
# =========================

import numpy as np
from sklearn.linear_model import LinearRegression

In [28]:
# H1
sleep_mean = df["sleep_hours"].mean()

h1_base = df[
    (df["age"] < 25) &
    (df["sleep_hours"] < sleep_mean)
]

h1_answer = (
    h1_base.groupby("country")["addiction_score"]
    .mean()
    .idxmax()
)

# H2
dopamine_median = df["dopamine_dependency_score"].median()
mhri_median = df["MHRI"].median()

h2_base = df[
    (df["dopamine_dependency_score"] > dopamine_median) &
    (df["MHRI"] > mhri_median)
]

h2_answer = (
    h2_base.groupby("country")["addiction_score"]
    .mean()
    .idxmax()
)

# H3
risk_df = df.copy()
risk_df["combined_risk_score"] = (
    risk_df["addiction_score"]
    + risk_df["dopamine_dependency_score"]
    - risk_df["sleep_hours"]
)

h3_answer = (
    risk_df.groupby("country")["combined_risk_score"]
    .mean()
    .idxmax()
)

# H4
h4_base = df[df["sleep_hours"] < sleep_mean]

h4_answer_df = (
    h4_base.groupby(["country", "age"], as_index=False)["addiction_score"]
    .mean()
    .sort_values("addiction_score", ascending=False)
    .head(3)
)

h4_answer = [
    f"{row['country']}-{int(row['age'])}"
    for _, row in h4_answer_df.iterrows()
]

hard_correct_answers = {
    "H1": h1_answer,
    "H2": h2_answer,
    "H3": h3_answer,
    "H4": h4_answer
}

hard_correct_answers

{'H1': 'Morocco',
 'H2': 'Pakistan',
 'H3': 'Tanzania',
 'H4': ['Bulgaria-32', 'Vietnam-58', 'Paraguay-41']}

In [29]:
hard_tasks_en = [
    {
        "task_id": "H1",
        "difficulty": "hard",
        "language": "EN",
        "question": (
            "Among users younger than 25 years old and with sleep_hours below "
            "the overall dataset average, which country has the highest average "
            "addiction_score? Return only the country name."
        ),
        "data": (
            h1_base.groupby("country", as_index=False)["addiction_score"]
            .mean()
            .sort_values("addiction_score", ascending=False)
            .head(30)
        )
    },
    {
        "task_id": "H2",
        "difficulty": "hard",
        "language": "EN",
        "question": (
            "Among users whose dopamine_dependency_score and MHRI are both above "
            "their respective dataset medians, which country has the highest average "
            "addiction_score? Return only the country name."
        ),
        "data": (
            h2_base.groupby("country", as_index=False)["addiction_score"]
            .mean()
            .sort_values("addiction_score", ascending=False)
            .head(30)
        )
    },
    {
        "task_id": "H3",
        "difficulty": "hard",
        "language": "EN",
        "question": (
            "Using the combined digital risk score defined as addiction_score + "
            "dopamine_dependency_score - sleep_hours, which country has the highest "
            "average combined digital risk? Return only the country name."
        ),
        "data": (
            risk_df.groupby("country", as_index=False)["combined_risk_score"]
            .mean()
            .sort_values("combined_risk_score", ascending=False)
            .head(30)
        )
    },
    {
        "task_id": "H4",
        "difficulty": "hard",
        "language": "EN",
        "question": (
            "Rank the three most vulnerable user groups, defined as country-age "
            "combinations, according to average addiction_score, considering only "
            "groups with below-average sleep_hours. Return only the top three "
            "country-age groups."
        ),
        "data": (
            h4_base.groupby(["country", "age"], as_index=False)["addiction_score"]
            .mean()
            .sort_values("addiction_score", ascending=False)
            .head(20)
        )
    }
]

In [30]:
def generate_response(messages, max_new_tokens=100):
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer(
        text,
        return_tensors="pt"
    ).to(model.device)

    start_time = time.time()

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,  # Изменили тут: temperature=0.0 убран
            pad_token_id=tokenizer.eos_token_id
        )

    end_time = time.time()

    response = tokenizer.decode(
        outputs[0][inputs["input_ids"].shape[-1]:],
        skip_special_tokens=True
    )

    return response.strip(), round(end_time - start_time, 3)

In [31]:
results_hard_en = []

for task in hard_tasks_en:
    table_text = task["data"].to_string(index=False)

    messages = [
        {
            "role": "system",
            "content": (
                "You are a data analyst. "
                "Use only the provided table. "
                "Return only the final answer. "
                "Do not explain your reasoning."
            )
        },
        {
            "role": "user",
            "content": f"""
Here is the table:

{table_text}

Task:
{task["question"]}
"""
        }
    ]

    answer, response_time = generate_response(messages)

    results_hard_en.append({
        "model": "Bielik-11B",
        "task_id": task["task_id"],
        "difficulty": task["difficulty"],
        "language": task["language"],
        "question": task["question"],
        "model_answer": answer,
        "correct_answer": hard_correct_answers[task["task_id"]],
        "response_time_sec": response_time
    })

results_hard_en_df = pd.DataFrame(results_hard_en)
results_hard_en_df

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

,model,task_id,difficulty,language,question,model_answer,correct_answer,response_time_sec
0,Bielik-11B,H1,hard,EN,Among users younger than 25 years old and with...,Morocco,Morocco,0.318
1,Bielik-11B,H2,hard,EN,Among users whose dopamine_dependency_score an...,Norway,Pakistan,0.323
2,Bielik-11B,H3,hard,EN,Using the combined digital risk score defined ...,Tanzania,Tanzania,0.405
3,Bielik-11B,H4,hard,EN,"Rank the three most vulnerable user groups, de...",1. Bulgaria (32 years)\n2. Peru (33 years)\n3....,"[Bulgaria-32, Vietnam-58, Paraguay-41]",2.418

polish prompt

In [32]:
hard_tasks_pl = [
    {
        "task_id": "H1",
        "difficulty": "hard",
        "language": "PL",
        "question": (
            "Wśród użytkowników poniżej 25 roku życia oraz z wartością sleep_hours "
            "niższą niż średnia w całym zbiorze danych, który kraj ma najwyższą "
            "średnią wartość addiction_score? Zwróć tylko nazwę kraju."
        ),
        "data": (
            h1_base.groupby("country", as_index=False)["addiction_score"]
            .mean()
            .sort_values("addiction_score", ascending=False)
            .head(30)
        )
    },
    {
        "task_id": "H2",
        "difficulty": "hard",
        "language": "PL",
        "question": (
            "Wśród użytkowników, których dopamine_dependency_score oraz MHRI są wyższe "
            "od odpowiednich median w zbiorze danych, który kraj ma najwyższą średnią "
            "wartość addiction_score? Zwróć tylko nazwę kraju."
        ),
        "data": (
            h2_base.groupby("country", as_index=False)["addiction_score"]
            .mean()
            .sort_values("addiction_score", ascending=False)
            .head(30)
        )
    },
    {
        "task_id": "H3",
        "difficulty": "hard",
        "language": "PL",
        "question": (
            "Korzystając ze złożonego wskaźnika ryzyka cyfrowego zdefiniowanego jako "
            "addiction_score + dopamine_dependency_score - sleep_hours, który kraj ma "
            "najwyższą średnią wartość tego wskaźnika? Zwróć tylko nazwę kraju."
        ),
        "data": (
            risk_df.groupby("country", as_index=False)["combined_risk_score"]
            .mean()
            .sort_values("combined_risk_score", ascending=False)
            .head(30)
        )
    },
    {
        "task_id": "H4",
        "difficulty": "hard",
        "language": "EN",
        "question": (
            "Uszereguj trzy najbardziej narażone grupy użytkowników, zdefiniowane jako "
            "kombinacje country-age, według średniej wartości addiction_score, uwzględniając "
            "tylko grupy z sleep_hours poniżej średniej. Zwróć tylko trzy najlepsze grupy country-age."
        ),
        "data": (
            h4_base.groupby(["country", "age"], as_index=False)["addiction_score"]
            .mean()
            .sort_values("addiction_score", ascending=False)
            .head(20)
        )
    }
]

In [33]:
def generate_response(messages, max_new_tokens=100):
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer(
        text,
        return_tensors="pt"
    ).to(model.device)

    start_time = time.time()

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,  # Изменили тут: temperature=0.0 убран
            pad_token_id=tokenizer.eos_token_id
        )

    end_time = time.time()

    response = tokenizer.decode(
        outputs[0][inputs["input_ids"].shape[-1]:],
        skip_special_tokens=True
    )

    return response.strip(), round(end_time - start_time, 3)

In [34]:
results_hard_pl = []

for task in hard_tasks_pl:
    table_text = task["data"].to_string(index=False)

    messages = [
        {
            "role": "system",
            "content": (
                "Jesteś analitykiem danych. "
                "Korzystaj wyłącznie z podanej tabeli. "
                "Zwróć tylko końcową odpowiedź. "
                "Nie wyjaśniaj toku rozumowania."
            )
        },
        {
            "role": "user",
            "content": f"""
Oto tabela:

{table_text}

Zadanie:
{task["question"]}
"""
        }
    ]

    answer, response_time = generate_response(messages)

    results_hard_pl.append({
        "model": "Vikhr-12B",
        "task_id": task["task_id"],
        "difficulty": task["difficulty"],
        "language": task["language"],
        "question": task["question"],
        "model_answer": answer,
        "correct_answer": hard_correct_answers[task["task_id"]],
        "response_time_sec": response_time
    })

results_hard_pl_df = pd.DataFrame(results_hard_pl)
results_hard_pl_df

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

,model,task_id,difficulty,language,question,model_answer,correct_answer,response_time_sec
0,Vikhr-12B,H1,hard,PL,Wśród użytkowników poniżej 25 roku życia oraz ...,Morocco,Morocco,0.326
1,Vikhr-12B,H2,hard,PL,"Wśród użytkowników, których dopamine_dependenc...",Pakistan,Pakistan,0.321
2,Vikhr-12B,H3,hard,PL,Korzystając ze złożonego wskaźnika ryzyka cyfr...,Tanzania,Tanzania,0.407
3,Vikhr-12B,H4,hard,EN,Uszereguj trzy najbardziej narażone grupy użyt...,1. Bulgaria - 32\n2. Vietnam - 58\n3. Paraguay...,"[Bulgaria-32, Vietnam-58, Paraguay-41]",2.243

Russian prompt

In [35]:
hard_tasks_ru = [
    {
        "task_id": "H1",
        "difficulty": "hard",
        "language": "RU",
        "question": (
            "Среди пользователей младше 25 лет и с количеством sleep_hours ниже "
            "среднего значения по всему датасету, какая страна имеет самое высокое "
            "среднее значение addiction_score? Верни только название страны."
        ),
        "data": (
            h1_base.groupby("country", as_index=False)["addiction_score"]
            .mean()
            .sort_values("addiction_score", ascending=False)
            .head(30)
        )
    },
    {
        "task_id": "H2",
        "difficulty": "hard",
        "language": "RU",
        "question": (
            "Среди пользователей, у которых dopamine_dependency_score и MHRI выше "
            "соответствующих медианных значений по датасету, какая страна имеет самое "
            "высокое среднее значение addiction_score? Верни только название страны."

        ),
        "data": (
            h2_base.groupby("country", as_index=False)["addiction_score"]
            .mean()
            .sort_values("addiction_score", ascending=False)
            .head(30)
        )
    },
    {
        "task_id": "H3",
        "difficulty": "hard",
        "language": "RU",
        "question": (
            "Используя комбинированный цифровой риск, определённый как "
            "addiction_score + dopamine_dependency_score - sleep_hours, какая страна "
            "имеет самый высокий средний комбинированный цифровой риск? Верни только название страны."
        ),
        "data": (
            risk_df.groupby("country", as_index=False)["combined_risk_score"]
            .mean()
            .sort_values("combined_risk_score", ascending=False)
            .head(30)
        )
    },
    {
        "task_id": "H4",
        "difficulty": "hard",
        "language": "RU",
        "question": (
            "Ранжируй три наиболее уязвимые группы пользователей, определённые как "
            "комбинации country-age, по среднему значению addiction_score, учитывая "
            "только группы с sleep_hours ниже среднего значения. Верни только три лучшие группы country-age."
        ),
        "data": (
            h4_base.groupby(["country", "age"], as_index=False)["addiction_score"]
            .mean()
            .sort_values("addiction_score", ascending=False)
            .head(20)
        )
    }
]

In [36]:
def generate_response(messages, max_new_tokens=100):
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer(
        text,
        return_tensors="pt"
    ).to(model.device)

    start_time = time.time()

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,  # Изменили тут: temperature=0.0 убран
            pad_token_id=tokenizer.eos_token_id
        )

    end_time = time.time()

    response = tokenizer.decode(
        outputs[0][inputs["input_ids"].shape[-1]:],
        skip_special_tokens=True
    )

    return response.strip(), round(end_time - start_time, 3)

In [37]:
results_hard_ru = []

for task in hard_tasks_ru:
    table_text = task["data"].to_string(index=False)

    messages = [
        {
            "role": "system",
            "content": (
                "Ты аналитик данных. "
                "Используй только предоставленную таблицу. "
                "Верни только итоговый ответ. "
                "Не объясняй ход рассуждений."
            )
        },
        {
            "role": "user",
            "content": f"""
Вот таблица:

{table_text}

Задание:
{task["question"]}
"""
        }
    ]

    answer, response_time = generate_response(messages)

    results_hard_ru.append({
        "model": "Vikhr-12B",
        "task_id": task["task_id"],
        "difficulty": task["difficulty"],
        "language": task["language"],
        "question": task["question"],
        "model_answer": answer,
        "correct_answer": hard_correct_answers[task["task_id"]],
        "response_time_sec": response_time
    })

results_hard_ru_df = pd.DataFrame(results_hard_ru)
results_hard_ru_df

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

,model,task_id,difficulty,language,question,model_answer,correct_answer,response_time_sec
0,Vikhr-12B,H1,hard,RU,Среди пользователей младше 25 лет и с количест...,Страна: Morocco,Morocco,0.610
1,Vikhr-12B,H2,hard,RU,"Среди пользователей, у которых dopamine_depend...",Страна: Pakistan,Pakistan,0.616
2,Vikhr-12B,H3,hard,RU,"Используя комбинированный цифровой риск, опред...",Tanzania,Tanzania,0.414
3,Vikhr-12B,H4,hard,RU,Ранжируй три наиболее уязвимые группы пользова...,Для выполнения задания мне необходимо знать зн...,"[Bulgaria-32, Vietnam-58, Paraguay-41]",5.063

**Forecast tasks**

English prompt

In [38]:
# =========================
# FORECAST TASKS — Vikhr — EN
# WITH PREDICTION + JUSTIFICATION
# =========================

import pandas as pd
import numpy as np
import re
from sklearn.linear_model import LinearRegression

In [39]:
# 1. Prepare yearly data

yearly_addiction = (
    df.groupby("year", as_index=False)["addiction_score"]
    .mean()
    .sort_values("year")
)

train_forecast = yearly_addiction[yearly_addiction["year"] <= 2040].copy()

X_train = train_forecast[["year"]]
y_train = train_forecast["addiction_score"]

forecast_model = LinearRegression()
forecast_model.fit(X_train, y_train)

# Correct answer for F1
f1_answer = round(
    float(forecast_model.predict(pd.DataFrame({"year": [2045]}))[0]),
    2
)

# Correct answer for F2
pred_2040 = round(
    float(forecast_model.predict(pd.DataFrame({"year": [2040]}))[0]),
    2
)

pred_2050 = round(
    float(forecast_model.predict(pd.DataFrame({"year": [2050]}))[0]),
    2
)

f2_answer = "Increase" if pred_2050 > pred_2040 else "Decrease"

forecast_correct_answers = {
    "F1": f1_answer,
    "F2": f2_answer
}

forecast_correct_answers

{'F1': 58.37, 'F2': 'Decrease'}

In [40]:
# 2. Forecast tasks in English

forecast_tasks_en = [
    {
        "task_id": "F1",
        "difficulty": "forecast",
        "language": "EN",
        "question": (
            "Using a simple linear trend based on the data from 2015 to 2040, "
            "predict the average addiction_score for year 2045. "
            "Return your answer in this exact format:\n"
            "Prediction: <number>\n"
            "Justification: <one short sentence>"
        ),
        "data": train_forecast
    },
    {
        "task_id": "F2",
        "difficulty": "forecast",
        "language": "EN",
        "question": (
            "Using a simple linear trend based on the data from 2015 to 2040, "
            "determine whether the average addiction_score in 2050 is expected "
            "to increase or decrease compared to 2040. "
            "Return your answer in this exact format:\n"
            "Prediction: <Increase or Decrease>\n"
            "Justification: <one short sentence>"
        ),
        "data": train_forecast
    }
]

In [41]:
def generate_response(messages, max_new_tokens=150):
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer(
        text,
        return_tensors="pt"
    ).to(model.device)

    start_time = time.time()

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,  # Изменили тут: temperature=0.0 убран
            pad_token_id=tokenizer.eos_token_id
        )

    end_time = time.time()

    response = tokenizer.decode(
        outputs[0][inputs["input_ids"].shape[-1]:],
        skip_special_tokens=True
    )

    return response.strip(), round(end_time - start_time, 3)

In [42]:
# 3. Run forecast tasks

results_forecast_en = []

for task in forecast_tasks_en:
    table_text = task["data"].to_string(index=False)

    messages = [
        {
            "role": "system",
            "content": (
                "You are a data analyst. "
                "Use only the provided table. "
                "Use a simple linear trend when forecasting. "
                "Return the answer exactly in the requested format. "
                "Do not add anything else."
            )
        },
        {
            "role": "user",
            "content": f"""
Here is the table:

{table_text}

Task:
{task["question"]}
"""
        }
    ]

    answer, response_time = generate_response(messages)

    results_forecast_en.append({
        "model": "Vikhr-12B",
        "task_id": task["task_id"],
        "difficulty": task["difficulty"],
        "language": task["language"],
        "question": task["question"],
        "model_answer": answer,
        "correct_answer": forecast_correct_answers[task["task_id"]],
        "response_time_sec": response_time
    })

results_forecast_en_df = pd.DataFrame(results_forecast_en)
results_forecast_en_df

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

,model,task_id,difficulty,language,question,model_answer,correct_answer,response_time_sec
0,Vikhr-12B,F1,forecast,EN,Using a simple linear trend based on the data ...,Prediction: 57.000000\nJustification: Extrapol...,58.37,2.907
1,Vikhr-12B,F2,forecast,EN,Using a simple linear trend based on the data ...,Prediction: Decrease\nJustification: The addic...,Decrease,2.841

polish prompt

In [43]:
forecast_tasks_pl = [
    {
        "task_id": "F1",
        "difficulty": "forecast",
        "language": "PL",
        "question": (
            "Na podstawie prostego trendu liniowego wyznaczonego z danych "
            "z lat 2015–2040 przewidź średnią wartość addiction_score dla roku 2045. "
            "Zwróć odpowiedź dokładnie w następującym formacie:\n"
            "Prediction: <liczba>\n"
            "Justification: <jedno krótkie zdanie>"
        ),
        "data": train_forecast
    },
    {
        "task_id": "F2",
        "difficulty": "forecast",
        "language": "PL",
        "question": (
            "Na podstawie prostego trendu liniowego wyznaczonego z danych "
            "z lat 2015–2040 określ, czy średnia wartość addiction_score "
            "w roku 2050 będzie wyższa czy niższa niż w roku 2040. "
            "Zwróć odpowiedź dokładnie w następującym formacie:\n"
            "Prediction: <Increase lub Decrease>\n"
            "Justification: <jedno krótkie zdanie>"
        ),
        "data": train_forecast
    }
]

In [44]:
def generate_response(messages, max_new_tokens=150):
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer(
        text,
        return_tensors="pt"
    ).to(model.device)

    start_time = time.time()

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,  # Изменили тут: temperature=0.0 убран
            pad_token_id=tokenizer.eos_token_id
        )

    end_time = time.time()

    response = tokenizer.decode(
        outputs[0][inputs["input_ids"].shape[-1]:],
        skip_special_tokens=True
    )

    return response.strip(), round(end_time - start_time, 3)

In [45]:
results_forecast_pl = []

for task in forecast_tasks_pl:

    table_text = task["data"].to_string(index=False)

    messages = [
        {
            "role": "system",
            "content": (
                "Jesteś analitykiem danych. "
                "Korzystaj wyłącznie z podanej tabeli. "
                "Do prognozowania użyj prostego trendu liniowego. "
                "Zwróć odpowiedź dokładnie w wymaganym formacie. "
                "Nie dodawaj nic więcej."
            )
        },
        {
            "role": "user",
            "content": f"""
Oto tabela:

{table_text}

Zadanie:
{task["question"]}
"""
        }
    ]

    answer, response_time = generate_response(messages)

    results_forecast_pl.append({
        "model": "Vikhr-12B",
        "task_id": task["task_id"],
        "difficulty": task["difficulty"],
        "language": task["language"],
        "question": task["question"],
        "model_answer": answer,
        "correct_answer": forecast_correct_answers[task["task_id"]],
        "response_time_sec": response_time
    })

results_forecast_pl_df = pd.DataFrame(results_forecast_pl)
results_forecast_pl_df

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

,model,task_id,difficulty,language,question,model_answer,correct_answer,response_time_sec
0,Vikhr-12B,F1,forecast,PL,Na podstawie prostego trendu liniowego wyznacz...,Prediction: 57.000000\nJustification: Trend li...,58.37,3.163
1,Vikhr-12B,F2,forecast,PL,Na podstawie prostego trendu liniowego wyznacz...,Prediction: Decrease\nJustification: Wykres li...,Decrease,2.634

Russian prompt

In [46]:
forecast_tasks_ru = [
    {
        "task_id": "F1",
        "difficulty": "forecast",
        "language": "RU",
        "question": (
            "Используя простой линейный тренд на основе данных за период "
            "2015–2040 годов, спрогнозируй среднее значение addiction_score "
            "для 2045 года. "
            "Верни ответ строго в следующем формате:\n"
            "Prediction: <число>\n"
            "Justification: <одно короткое предложение>"
        ),
        "data": train_forecast
    },
    {
        "task_id": "F2",
        "difficulty": "forecast",
        "language": "RU",
        "question": (
            "Используя простой линейный тренд на основе данных за период "
            "2015–2040 годов, определи, будет ли среднее значение "
            "addiction_score в 2050 году выше или ниже, чем в 2040 году. "
            "Верни ответ строго в следующем формате:\n"
            "Prediction: <Increase или Decrease>\n"
            "Justification: <одно короткое предложение>"
        ),
        "data": train_forecast
    }
]

In [47]:
def generate_response(messages, max_new_tokens=150):
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer(
        text,
        return_tensors="pt"
    ).to(model.device)

    start_time = time.time()

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,  # Изменили тут: temperature=0.0 убран
            pad_token_id=tokenizer.eos_token_id
        )

    end_time = time.time()

    response = tokenizer.decode(
        outputs[0][inputs["input_ids"].shape[-1]:],
        skip_special_tokens=True
    )

    return response.strip(), round(end_time - start_time, 3)

In [48]:
results_forecast_ru = []

for task in forecast_tasks_ru:

    table_text = task["data"].to_string(index=False)

    messages = [
        {
            "role": "system",
            "content": (
                "Ты аналитик данных. "
                "Используй только предоставленную таблицу. "
                "Для прогнозирования используй простой линейный тренд. "
                "Верни ответ строго в требуемом формате. "
                "Не добавляй ничего лишнего."
            )
        },
        {
            "role": "user",
            "content": f"""
Вот таблица:

{table_text}

Задание:
{task["question"]}
"""
        }
    ]

    answer, response_time = generate_response(messages)

    results_forecast_ru.append({
        "model": "Vikhr-12B",
        "task_id": task["task_id"],
        "difficulty": task["difficulty"],
        "language": task["language"],
        "question": task["question"],
        "model_answer": answer,
        "correct_answer": forecast_correct_answers[task["task_id"]],
        "response_time_sec": response_time
    })

results_forecast_ru_df = pd.DataFrame(results_forecast_ru)
results_forecast_ru_df

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

,model,task_id,difficulty,language,question,model_answer,correct_answer,response_time_sec
0,Vikhr-12B,F1,forecast,RU,Используя простой линейный тренд на основе дан...,Для прогнозирования будущего значения addictio...,58.37,13.382
1,Vikhr-12B,F2,forecast,RU,Используя простой линейный тренд на основе дан...,Prediction: Decrease\nJustification: Простой л...,Decrease,3.066